// AUTO-GENERATED by This-Directory-Only/scripts/extract_arena_exercises.py
// Do not edit by hand. Re-run the script (or deploy) to refresh.
window.ARENA_EXERCISES_BY_NOTEBOOK = {
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part0_prereqs/0.0_Prerequisites_exercises.ipynb": [],
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part1_ray_tracing/0.1_Ray_Tracing_exercises.ipynb": [
    {
      "title": "Exercise - implement `make_rays_1d`",
      "anchor": "exercise-implement-make-rays-1d"
    },
    {
      "title": "Exercise - implement `intersect_ray_1d`",
      "anchor": "exercise-implement-intersect-ray-1d"
    },
    {
      "title": "Exercise - implement `intersect_rays_1d`",
      "anchor": "exercise-implement-intersect-rays-1d"
    },
    {
      "title": "Exercise - implement `make_rays_2d`",
      "anchor": "exercise-implement-make-rays-2d"
    },
    {
      "title": "Exercise - implement `triangle_ray_intersects`",
      "anchor": "exercise-implement-triangle-ray-intersects"
    },
    {
      "title": "Exercise - implement `raytrace_triangle`",
      "anchor": "exercise-implement-raytrace-triangle"
    },
    {
      "title": "Exercise - implement `raytrace_mesh`",
      "anchor": "exercise-implement-raytrace-mesh"
    },
    {
      "title": "Exercise - rotation matrix",
      "anchor": "exercise-rotation-matrix"
    },
    {
      "title": "Exercise - use GPUs",
      "anchor": "exercise-use-gpus"
    },
    {
      "title": "Exercise (bonus) - add lighting",
      "anchor": "exercise-bonus-add-lighting"
    }
  ],
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part2_cnns/0.2_CNNs_&_ResNets_exercises.ipynb": [
    {
      "title": "Exercise - implement `ReLU`",
      "anchor": "exercise-implement-relu"
    },
    {
      "title": "Exercise - implement `Linear`",
      "anchor": "exercise-implement-linear"
    },
    {
      "title": "Exercise - implement the simple MLP",
      "anchor": "exercise-implement-the-simple-mlp"
    },
    {
      "title": "Exercise - add a validation loop",
      "anchor": "exercise-add-a-validation-loop"
    },
    {
      "title": "Exercise - implement `Conv2d`",
      "anchor": "exercise-implement-conv2d"
    },
    {
      "title": "Exercise - implement `BatchNorm2d`",
      "anchor": "exercise-implement-batchnorm2d"
    },
    {
      "title": "Exercise - implement `AveragePool`",
      "anchor": "exercise-implement-averagepool"
    },
    {
      "title": "Exercise - implement `ResidualBlock`",
      "anchor": "exercise-implement-residualblock"
    },
    {
      "title": "Exercise - implement `BlockGroup`",
      "anchor": "exercise-implement-blockgroup"
    },
    {
      "title": "Exercise - implement `ResNet34`",
      "anchor": "exercise-implement-resnet34"
    },
    {
      "title": "Exercise - verify your model's predictions",
      "anchor": "exercise-verify-your-model-s-predictions"
    },
    {
      "title": "Exercise - prepare ResNet for feature extraction",
      "anchor": "exercise-prepare-resnet-for-feature-extraction"
    },
    {
      "title": "Exercise - write training loop for feature extraction",
      "anchor": "exercise-write-training-loop-for-feature-extraction"
    },
    {
      "title": "Exercise - fill in the correct size and stride",
      "anchor": "exercise-fill-in-the-correct-size-and-stride"
    },
    {
      "title": "Exercise - trace",
      "anchor": "exercise-trace"
    },
    {
      "title": "Exercise - matrix-vector multiplication",
      "anchor": "exercise-matrix-vector-multiplication"
    },
    {
      "title": "Exercise - matrix-matrix multiplication",
      "anchor": "exercise-matrix-matrix-multiplication"
    },
    {
      "title": "Exercise - implement minimal 1D conv (part 1)",
      "anchor": "exercise-implement-minimal-1d-conv-part-1"
    },
    {
      "title": "Exercise - implement minimal 1D conv (part 2)",
      "anchor": "exercise-implement-minimal-1d-conv-part-2"
    },
    {
      "title": "Exercise - implement 2D minimal convolutions",
      "anchor": "exercise-implement-2d-minimal-convolutions"
    },
    {
      "title": "Exercise - implement padding",
      "anchor": "exercise-implement-padding"
    },
    {
      "title": "Exercise - implement 1D convolutions",
      "anchor": "exercise-implement-1d-convolutions"
    },
    {
      "title": "Exercise - implement 2D convolutions",
      "anchor": "exercise-implement-2d-convolutions"
    },
    {
      "title": "Exercise - implement 2D max pooling",
      "anchor": "exercise-implement-2d-max-pooling"
    }
  ],
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part3_optimization/0.3_Optimization_exercises.ipynb": [
    {
      "title": "Exercise - implement `opt_fn_with_sgd`",
      "anchor": "exercise-implement-opt-fn-with-sgd"
    },
    {
      "title": "Exercise - implement SGD",
      "anchor": "exercise-implement-sgd"
    },
    {
      "title": "Exercise - implement RMSprop",
      "anchor": "exercise-implement-rmsprop"
    },
    {
      "title": "Exercise - implement Adam",
      "anchor": "exercise-implement-adam"
    },
    {
      "title": "Exercise - implement AdamW",
      "anchor": "exercise-implement-adamw"
    },
    {
      "title": "Exercise - experiment with different optimizers & params",
      "anchor": "exercise-experiment-with-different-optimizers-params"
    },
    {
      "title": "Exercise - rewrite SGD to use parameter groups",
      "anchor": "exercise-rewrite-sgd-to-use-parameter-groups"
    },
    {
      "title": "Exercise - rewrite training loop with wandb",
      "anchor": "exercise-rewrite-training-loop-with-wandb"
    },
    {
      "title": "Exercise - define a sweep config & update `args`",
      "anchor": "exercise-define-a-sweep-config-update-args"
    },
    {
      "title": "Exercise - implement `broadcast`",
      "anchor": "exercise-implement-broadcast"
    },
    {
      "title": "Exercise - implement `all_reduce`",
      "anchor": "exercise-implement-all-reduce"
    },
    {
      "title": "Exercise - complete `DistResNetTrainer`",
      "anchor": "exercise-complete-distresnettrainer"
    }
  ],
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part4_backprop/0.4_Backprop_exercises.ipynb": [
    {
      "title": "Exercise - implement `log_back`",
      "anchor": "exercise-implement-log-back"
    },
    {
      "title": "Exercise - implement `unbroadcast`",
      "anchor": "exercise-implement-unbroadcast"
    },
    {
      "title": "Exercise - implement both `multiply_back` functions",
      "anchor": "exercise-implement-both-multiply-back-functions"
    },
    {
      "title": "Exercise - implement `forward_and_back`",
      "anchor": "exercise-implement-forward-and-back"
    },
    {
      "title": "Exercise - implement `BackwardFuncLookup`",
      "anchor": "exercise-implement-backwardfunclookup"
    },
    {
      "title": "Exercise - implement `log_forward`",
      "anchor": "exercise-implement-log-forward"
    },
    {
      "title": "Exercise - implement `multiply_forward`",
      "anchor": "exercise-implement-multiply-forward"
    },
    {
      "title": "Exercise - implement `wrap_forward_fn`",
      "anchor": "exercise-implement-wrap-forward-fn"
    },
    {
      "title": "Exercise - implement `topological_sort`",
      "anchor": "exercise-implement-topological-sort"
    },
    {
      "title": "Exercise - implement `backprop`",
      "anchor": "exercise-implement-backprop"
    },
    {
      "title": "Exercise - `negative`",
      "anchor": "exercise-negative"
    },
    {
      "title": "Exercise - `exp`",
      "anchor": "exercise-exp"
    },
    {
      "title": "Exercise - `reshape`",
      "anchor": "exercise-reshape"
    },
    {
      "title": "Exercise - `permute`",
      "anchor": "exercise-permute"
    },
    {
      "title": "Exercise - `sum`",
      "anchor": "exercise-sum"
    },
    {
      "title": "Exercise - `max`",
      "anchor": "exercise-max"
    },
    {
      "title": "Exercise - functional `ReLU`",
      "anchor": "exercise-functional-relu"
    },
    {
      "title": "Exercise - 2D `matmul`",
      "anchor": "exercise-2d-matmul"
    },
    {
      "title": "Exercise - implement `Linear`",
      "anchor": "exercise-implement-linear"
    },
    {
      "title": "Exercise - implement `cross_entropy`",
      "anchor": "exercise-implement-cross-entropy"
    },
    {
      "title": "Exercise - implement `SGD`",
      "anchor": "exercise-implement-sgd"
    }
  ],
  "content/ARENA_5.0-main/chapter0_fundamentals/exercises/part5_vaes_and_gans/0.5_VAEs_&_GANs_exercises.ipynb": [
    {
      "title": "Exercise - implement autoencoder",
      "anchor": "exercise-implement-autoencoder"
    },
    {
      "title": "Exercise - write autoencoder training loop",
      "anchor": "exercise-write-autoencoder-training-loop"
    },
    {
      "title": "Exercise - build your VAE",
      "anchor": "exercise-build-your-vae"
    },
    {
      "title": "Exercise - write your VAE training loop",
      "anchor": "exercise-write-your-vae-training-loop"
    },
    {
      "title": "Exercise - some more modules",
      "anchor": "exercise-some-more-modules"
    },
    {
      "title": "Exercise - building your GAN",
      "anchor": "exercise-building-your-gan"
    },
    {
      "title": "Exercise - Weight initialisation",
      "anchor": "exercise-weight-initialisation"
    },
    {
      "title": "Exercise - implement GAN training loop",
      "anchor": "exercise-implement-gan-training-loop"
    },
    {
      "title": "Exercise - minimal 1D transposed convolutions",
      "anchor": "exercise-minimal-1d-transposed-convolutions"
    },
    {
      "title": "Exercise - 1D transposed convolutions",
      "anchor": "exercise-1d-transposed-convolutions"
    },
    {
      "title": "Exercise - 2D transposed convolutions",
      "anchor": "exercise-2d-transposed-convolutions"
    },
    {
      "title": "Exercise - transposed conv module",
      "anchor": "exercise-transposed-conv-module"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part1_transformer_from_scratch/1.1_Transformer_from_Scratch_exercises.ipynb": [
    {
      "title": "Exercise - implement `LayerNorm`",
      "anchor": "exercise-implement-layernorm"
    },
    {
      "title": "Exercise - implement `Embed`",
      "anchor": "exercise-implement-embed"
    },
    {
      "title": "Exercise - implement `PosEmbed`",
      "anchor": "exercise-implement-posembed"
    },
    {
      "title": "Exercise - implement `apply_causal_mask`",
      "anchor": "exercise-implement-apply-causal-mask"
    },
    {
      "title": "Exercise - implement `Attention`",
      "anchor": "exercise-implement-attention"
    },
    {
      "title": "Exercise - implement `MLP`",
      "anchor": "exercise-implement-mlp"
    },
    {
      "title": "Exercise - implement `TransformerBlock`",
      "anchor": "exercise-implement-transformerblock"
    },
    {
      "title": "Exercise - implement `Unembed`",
      "anchor": "exercise-implement-unembed"
    },
    {
      "title": "Exercise - implement `DemoTransformer`",
      "anchor": "exercise-implement-demotransformer"
    },
    {
      "title": "Exercise - write training loop",
      "anchor": "exercise-write-training-loop"
    },
    {
      "title": "Exercise (optional) - log completions",
      "anchor": "exercise-optional-log-completions"
    },
    {
      "title": "Exercise - implement `sample`",
      "anchor": "exercise-implement-sample"
    },
    {
      "title": "Exercise - `sample_basic`",
      "anchor": "exercise-sample-basic"
    },
    {
      "title": "Exercise - `apply_temperature`",
      "anchor": "exercise-apply-temperature"
    },
    {
      "title": "Exercise - `apply_frequency_penalty`",
      "anchor": "exercise-apply-frequency-penalty"
    },
    {
      "title": "Exercise - `sample_top_k`",
      "anchor": "exercise-sample-top-k"
    },
    {
      "title": "Exercise - `sample_top_p`",
      "anchor": "exercise-sample-top-p"
    },
    {
      "title": "Exercise - implement `beam_search`",
      "anchor": "exercise-implement-beam-search"
    },
    {
      "title": "Exercise - implement KV caching",
      "anchor": "exercise-implement-kv-caching"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part2_intro_to_mech_interp/1.2_Intro_to_Mech_Interp_exercises.ipynb": [
    {
      "title": "Exercise - inspect your model",
      "anchor": "exercise-inspect-your-model"
    },
    {
      "title": "Exercise - how many tokens does your model guess correctly?",
      "anchor": "exercise-how-many-tokens-does-your-model-guess-correctly"
    },
    {
      "title": "Exercise - verify activations",
      "anchor": "exercise-verify-activations"
    },
    {
      "title": "Exercise - visualise & inspect attention patterns",
      "anchor": "exercise-visualise-inspect-attention-patterns"
    },
    {
      "title": "Exercise - write your own detectors",
      "anchor": "exercise-write-your-own-detectors"
    },
    {
      "title": "Exercise - plot per-token loss on repeated sequence",
      "anchor": "exercise-plot-per-token-loss-on-repeated-sequence"
    },
    {
      "title": "Exercise - make an induction-head detector",
      "anchor": "exercise-make-an-induction-head-detector"
    },
    {
      "title": "Exercise - calculate induction scores with hooks",
      "anchor": "exercise-calculate-induction-scores-with-hooks"
    },
    {
      "title": "Exercise - find induction heads in GPT2-small",
      "anchor": "exercise-find-induction-heads-in-gpt2-small"
    },
    {
      "title": "Exercise - build logit attribution tool",
      "anchor": "exercise-build-logit-attribution-tool"
    },
    {
      "title": "Exercise - interpret logit attribution for the induction heads",
      "anchor": "exercise-interpret-logit-attribution-for-the-induction-heads"
    },
    {
      "title": "Exercise - induction head ablation",
      "anchor": "exercise-induction-head-ablation"
    },
    {
      "title": "Exercise - mean ablation",
      "anchor": "exercise-mean-ablation"
    },
    {
      "title": "Exercise - deriving properties of a factored matrix",
      "anchor": "exercise-deriving-properties-of-a-factored-matrix"
    },
    {
      "title": "Exercise - compute OV circuit for `1.4`",
      "anchor": "exercise-compute-ov-circuit-for-1-4"
    },
    {
      "title": "Exercise - compute circuit accuracy",
      "anchor": "exercise-compute-circuit-accuracy"
    },
    {
      "title": "Exercise - compute effective circuit",
      "anchor": "exercise-compute-effective-circuit"
    },
    {
      "title": "Exercise - interpret full QK-circuit for `0.7`",
      "anchor": "exercise-interpret-full-qk-circuit-for-0-7"
    },
    {
      "title": "Exercise - analyse the relative importance",
      "anchor": "exercise-analyse-the-relative-importance"
    },
    {
      "title": "Exercise - decompose attention scores",
      "anchor": "exercise-decompose-attention-scores"
    },
    {
      "title": "Exercise - compute the K-comp circuit",
      "anchor": "exercise-compute-the-k-comp-circuit"
    },
    {
      "title": "Exercise - calculate composition scores",
      "anchor": "exercise-calculate-composition-scores"
    },
    {
      "title": "Exercise - Setting a Baseline",
      "anchor": "exercise-setting-a-baseline"
    },
    {
      "title": "Exercise - batching, and using the `FactoredMatrix` class",
      "anchor": "exercise-batching-and-using-the-factoredmatrix-class"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part31_linear_probes/1.3.1_Linear_Probes_exercises.ipynb": [
    {
      "title": "Exercise - implement `extract_activations`",
      "anchor": "exercise-implement-extract-activations"
    },
    {
      "title": "Exercise - implement `get_pca_components`",
      "anchor": "exercise-implement-get-pca-components"
    },
    {
      "title": "Exercise - implement layer sweep",
      "anchor": "exercise-implement-layer-sweep"
    },
    {
      "title": "Exercise - implement `MMProbe`",
      "anchor": "exercise-implement-mmprobe"
    },
    {
      "title": "Exercise - implement `LRProbe`",
      "anchor": "exercise-implement-lrprobe"
    },
    {
      "title": "Exercise - cross-dataset generalization matrix",
      "anchor": "exercise-cross-dataset-generalization-matrix"
    },
    {
      "title": "Exercise - implement few-shot evaluation",
      "anchor": "exercise-implement-few-shot-evaluation"
    },
    {
      "title": "Exercise - implement the batch-aware intervention hook",
      "anchor": "exercise-implement-the-batch-aware-intervention-hook"
    },
    {
      "title": "Exercise - construct instructed-pairs dataset",
      "anchor": "exercise-construct-instructed-pairs-dataset"
    },
    {
      "title": "Exercise - implement `DeceptionSteeringHook`",
      "anchor": "exercise-implement-deceptionsteeringhook"
    },
    {
      "title": "Exercise - implement `score_dialogue`",
      "anchor": "exercise-implement-score-dialogue"
    },
    {
      "title": "Exercise - implement `extract_full_sequence_activations`",
      "anchor": "exercise-implement-extract-full-sequence-activations"
    },
    {
      "title": "Exercise - implement `attention_probe_forward`",
      "anchor": "exercise-implement-attention-probe-forward"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part32_function_vectors_and_model_steering/1.3.2_Function_Vectors_&_Model_Steering_exercises.ipynb": [
    {
      "title": "Exercise - visualize attention heads",
      "anchor": "exercise-visualize-attention-heads"
    },
    {
      "title": "Exercise (optional) - generate your own antonym pairs",
      "anchor": "exercise-optional-generate-your-own-antonym-pairs"
    },
    {
      "title": "Exercise - forward pass on antonym dataset",
      "anchor": "exercise-forward-pass-on-antonym-dataset"
    },
    {
      "title": "Exercise - intervene with $h$",
      "anchor": "exercise-intervene-with-h"
    },
    {
      "title": "Exercise - combine the last two functions",
      "anchor": "exercise-combine-the-last-two-functions"
    },
    {
      "title": "Exercise - compute change in accuracy",
      "anchor": "exercise-compute-change-in-accuracy"
    },
    {
      "title": "Exercise - implement `calculate_fn_vectors_and_intervene`",
      "anchor": "exercise-implement-calculate-fn-vectors-and-intervene"
    },
    {
      "title": "Exercise - calculate the function vector",
      "anchor": "exercise-calculate-the-function-vector"
    },
    {
      "title": "Exercise - intervene with function vector, in multi-token generation",
      "anchor": "exercise-intervene-with-function-vector-in-multi-token-generation"
    },
    {
      "title": "Exercise - generalize results to another task (optional)",
      "anchor": "exercise-generalize-results-to-another-task-optional"
    },
    {
      "title": "Exercise - replicate the steering vector results",
      "anchor": "exercise-replicate-the-steering-vector-results"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part33_interp_with_saes/1.3.3_Interpretability_with_SAEs_exercises.ipynb": [
    {
      "title": "Exercise - find interesting latents",
      "anchor": "exercise-find-interesting-latents"
    },
    {
      "title": "Exercise - get the activation distribution",
      "anchor": "exercise-get-the-activation-distribution"
    },
    {
      "title": "Exercise - find max activating examples",
      "anchor": "exercise-find-max-activating-examples"
    },
    {
      "title": "Exercise - get top / bottom logits",
      "anchor": "exercise-get-top-bottom-logits"
    },
    {
      "title": "Exercise - autointerp",
      "anchor": "exercise-autointerp"
    },
    {
      "title": "Exercise - explore attention SAE dashboards",
      "anchor": "exercise-explore-attention-sae-dashboards"
    },
    {
      "title": "Exercise - derive attention DFA",
      "anchor": "exercise-derive-attention-dfa"
    },
    {
      "title": "Exercise - verify model + SAEs can still solve this",
      "anchor": "exercise-verify-model-saes-can-still-solve-this"
    },
    {
      "title": "Exercise - find name mover features with max activations",
      "anchor": "exercise-find-name-mover-features-with-max-activations"
    },
    {
      "title": "Exercise - identify name mover heads",
      "anchor": "exercise-identify-name-mover-heads"
    },
    {
      "title": "Exercise - find name mover features with DLA",
      "anchor": "exercise-find-name-mover-features-with-dla"
    },
    {
      "title": "Exercise (optional) - replicate these results, with sentiment",
      "anchor": "exercise-optional-replicate-these-results-with-sentiment"
    },
    {
      "title": "Exercise - find duplicate token features with ablation",
      "anchor": "exercise-find-duplicate-token-features-with-ablation"
    },
    {
      "title": "Exercise - compare ablation to attribution patching",
      "anchor": "exercise-compare-ablation-to-attribution-patching"
    },
    {
      "title": "Exercise - implement `generate_with_steering`",
      "anchor": "exercise-implement-generate-with-steering"
    },
    {
      "title": "Exercise - study these SAEs",
      "anchor": "exercise-study-these-saes"
    },
    {
      "title": "Exercise - create UMAP",
      "anchor": "exercise-create-umap"
    },
    {
      "title": "Exercise - add clustering",
      "anchor": "exercise-add-clustering"
    },
    {
      "title": "Exercise - implement autointerp scoring",
      "anchor": "exercise-implement-autointerp-scoring"
    },
    {
      "title": "Exercise - implement patch scoping",
      "anchor": "exercise-implement-patch-scoping"
    },
    {
      "title": "Exercise - replicate patch scoping scale tuning results",
      "anchor": "exercise-replicate-patch-scoping-scale-tuning-results"
    },
    {
      "title": "Exercise - identify good and bad training curves",
      "anchor": "exercise-identify-good-and-bad-training-curves"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part34_activation_oracles/1.3.4_Activation_Oracles_exercises.ipynb": [
    {
      "title": "Exercise - test \"answering question\" hypothesis",
      "anchor": "exercise-test-answering-question-hypothesis"
    },
    {
      "title": "Exercise - test \"logit lens\" hypothesis",
      "anchor": "exercise-test-logit-lens-hypothesis"
    },
    {
      "title": "Exercise - Extract function results without the function definition",
      "anchor": "exercise-extract-function-results-without-the-function-definition"
    },
    {
      "title": "Exercise - Implement `collect_activations_multiple_layers`",
      "anchor": "exercise-implement-collect-activations-multiple-layers"
    },
    {
      "title": "Exercise - Implement `find_pattern_in_tokens`",
      "anchor": "exercise-implement-find-pattern-in-tokens"
    },
    {
      "title": "Exercise - Implement `get_hf_activation_steering_hook`",
      "anchor": "exercise-implement-get-hf-activation-steering-hook"
    },
    {
      "title": "Exercise - Implement `create_oracle_input`",
      "anchor": "exercise-implement-create-oracle-input"
    },
    {
      "title": "Exercise - Build `utils.run_oracle()` from components",
      "anchor": "exercise-build-utils-run-oracle-from-components"
    },
    {
      "title": "Exercise - Extract secret word",
      "anchor": "exercise-extract-secret-word"
    },
    {
      "title": "Exercise - Compare oracle prompts and input types",
      "anchor": "exercise-compare-oracle-prompts-and-input-types"
    },
    {
      "title": "Exercise - Systematic taboo evaluation",
      "anchor": "exercise-systematic-taboo-evaluation"
    },
    {
      "title": "Exercise - Come up with more goal extraction examples",
      "anchor": "exercise-come-up-with-more-goal-extraction-examples"
    },
    {
      "title": "Exercise - Detect misalignment from activations",
      "anchor": "exercise-detect-misalignment-from-activations"
    },
    {
      "title": "Exercise - Model-diffing with activation differences",
      "anchor": "exercise-model-diffing-with-activation-differences"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part41_indirect_object_identification/1.4.1_Indirect_Object_Identification_exercises.ipynb": [
    {
      "title": "Exercise - implement the performance evaluation function",
      "anchor": "exercise-implement-the-performance-evaluation-function"
    },
    {
      "title": "Exercise - implement `residual_stack_to_logit_diff`",
      "anchor": "exercise-implement-residual-stack-to-logit-diff"
    },
    {
      "title": "Exercise - create a metric",
      "anchor": "exercise-create-a-metric"
    },
    {
      "title": "Exercise - implement head-to-residual patching",
      "anchor": "exercise-implement-head-to-residual-patching"
    },
    {
      "title": "Exercise (optional) - implement head-to-block patching",
      "anchor": "exercise-optional-implement-head-to-block-patching"
    },
    {
      "title": "Exercise - implement head-to-head patching",
      "anchor": "exercise-implement-head-to-head-patching"
    },
    {
      "title": "Exercise (optional) - implement head-to-head-input patching",
      "anchor": "exercise-optional-implement-head-to-head-input-patching"
    },
    {
      "title": "Exercise - implement path patching to the final residual stream value",
      "anchor": "exercise-implement-path-patching-to-the-final-residual-stream-value"
    },
    {
      "title": "Exercise - implement path patching from head to head",
      "anchor": "exercise-implement-path-patching-from-head-to-head"
    },
    {
      "title": "Exercise - replicate writing direction results",
      "anchor": "exercise-replicate-writing-direction-results"
    },
    {
      "title": "Exercise - replicate copying score results",
      "anchor": "exercise-replicate-copying-score-results"
    },
    {
      "title": "Exercise - perform head validation",
      "anchor": "exercise-perform-head-validation"
    },
    {
      "title": "Exercise - constructing the minimal circuit",
      "anchor": "exercise-constructing-the-minimal-circuit"
    },
    {
      "title": "Exercise - calculate minimality scores",
      "anchor": "exercise-calculate-minimality-scores"
    },
    {
      "title": "Exercise - validate prev token heads via patching",
      "anchor": "exercise-validate-prev-token-heads-via-patching"
    },
    {
      "title": "Exercise - decompose S-Inhibition heads",
      "anchor": "exercise-decompose-s-inhibition-heads"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part42_sae_circuits/1.4.2_SAE_Circuits_exercises.ipynb": [
    {
      "title": "Exercise (1/3) - implement the `SparseTensor` class",
      "anchor": "exercise-1-3-implement-the-sparsetensor-class"
    },
    {
      "title": "Exercise (2/3) - implement `latent_acts_to_later_latent_acts`",
      "anchor": "exercise-2-3-implement-latent-acts-to-later-latent-acts"
    },
    {
      "title": "Exercise (3/3) - implement `latent_to_latent_gradients`",
      "anchor": "exercise-3-3-implement-latent-to-latent-gradients"
    },
    {
      "title": "Exercise - get latent-to-token gradients",
      "anchor": "exercise-get-latent-to-token-gradients"
    },
    {
      "title": "Exercise - get latent-to-logit gradients",
      "anchor": "exercise-get-latent-to-logit-gradients"
    },
    {
      "title": "Exercise (optional) - find induction circuits in attention SAEs",
      "anchor": "exercise-optional-find-induction-circuits-in-attention-saes"
    },
    {
      "title": "Exercise - compute de-embedding",
      "anchor": "exercise-compute-de-embedding"
    },
    {
      "title": "Exercise - correct the de-embedding function",
      "anchor": "exercise-correct-the-de-embedding-function"
    },
    {
      "title": "Exercise - implement `TranscoderReplacementHooks`",
      "anchor": "exercise-implement-transcoderreplacementhooks"
    },
    {
      "title": "Exercise - implement `compute_salient_logits`",
      "anchor": "exercise-implement-compute-salient-logits"
    },
    {
      "title": "Exercise (1/3) - implement `build_embedding_nodes`",
      "anchor": "exercise-1-3-implement-build-embedding-nodes"
    },
    {
      "title": "Exercise (2/3) - implement `build_intermediate_nodes`",
      "anchor": "exercise-2-3-implement-build-intermediate-nodes"
    },
    {
      "title": "Exercise (1/2) - implement `prepare_backward_batches`",
      "anchor": "exercise-1-2-implement-prepare-backward-batches"
    },
    {
      "title": "Exercise (2/2) - implement `compute_adjacency_matrix`",
      "anchor": "exercise-2-2-implement-compute-adjacency-matrix"
    },
    {
      "title": "Exercise - implement `compute_influence`",
      "anchor": "exercise-implement-compute-influence"
    },
    {
      "title": "Exercise (1/2) - implement `prune_nodes`",
      "anchor": "exercise-1-2-implement-prune-nodes"
    },
    {
      "title": "Exercise (2/2) - implement `prune_edges`",
      "anchor": "exercise-2-2-implement-prune-edges"
    },
    {
      "title": "Exercise - cross-prompt feature swapping",
      "anchor": "exercise-cross-prompt-feature-swapping"
    },
    {
      "title": "Exercise - sustained interventions during generation",
      "anchor": "exercise-sustained-interventions-during-generation"
    },
    {
      "title": "Exercise - implement `map_through_ln`, `map_through_attn`, `map_through_mlp`",
      "anchor": "exercise-implement-map-through-ln-map-through-attn-map-through-mlp"
    },
    {
      "title": "Exercise - implement `compute_adjacency_matrix_manual`",
      "anchor": "exercise-implement-compute-adjacency-matrix-manual"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part51_balanced_bracket_classifier/1.5.1_Balanced_Bracket_Classifier_exercises.ipynb": [
    {
      "title": "Exercise - handwritten solution (for loop)",
      "anchor": "exercise-handwritten-solution-for-loop"
    },
    {
      "title": "Exercise -  handwritten solution (vectorized)",
      "anchor": "exercise-handwritten-solution-vectorized"
    },
    {
      "title": "Exercise - get the `post_final_ln_dir`",
      "anchor": "exercise-get-the-post-final-ln-dir"
    },
    {
      "title": "Exercise - get the `pre_final_ln_dir`",
      "anchor": "exercise-get-the-pre-final-ln-dir"
    },
    {
      "title": "Exercise - breaking down the residual stream by component",
      "anchor": "exercise-breaking-down-the-residual-stream-by-component"
    },
    {
      "title": "Exercise - compute output in unbalanced direction for each component",
      "anchor": "exercise-compute-output-in-unbalanced-direction-for-each-component"
    },
    {
      "title": "Exercise - classify bracket strings by failure type",
      "anchor": "exercise-classify-bracket-strings-by-failure-type"
    },
    {
      "title": "Exercise - get attention probabilities",
      "anchor": "exercise-get-attention-probabilities"
    },
    {
      "title": "Exercise - calculate the pre-head 2.0 unbalanced direction",
      "anchor": "exercise-calculate-the-pre-head-2-0-unbalanced-direction"
    },
    {
      "title": "Exercise - compute component magnitudes",
      "anchor": "exercise-compute-component-magnitudes"
    },
    {
      "title": "Exercise - get output by neuron",
      "anchor": "exercise-get-output-by-neuron"
    },
    {
      "title": "Exercise - implement the same function, using less memory",
      "anchor": "exercise-implement-the-same-function-using-less-memory"
    },
    {
      "title": "Exercise - extracting queries and keys using hooks",
      "anchor": "exercise-extracting-queries-and-keys-using-hooks"
    },
    {
      "title": "Exercise - validate the hypothesis",
      "anchor": "exercise-validate-the-hypothesis"
    },
    {
      "title": "Exercise - cosine similarity of input directions (optional)",
      "anchor": "exercise-cosine-similarity-of-input-directions-optional"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part52_grokking_and_modular_arithmetic/1.5.2_Grokking_&_Modular_Arithmetic_exercises.ipynb": [
    {
      "title": "Exercise - extract key activations",
      "anchor": "exercise-extract-key-activations"
    },
    {
      "title": "Exercise - answer some initial questions",
      "anchor": "exercise-answer-some-initial-questions"
    },
    {
      "title": "Exercise - derive the functional form",
      "anchor": "exercise-derive-the-functional-form"
    },
    {
      "title": "Exercise - define the effective weight matrices",
      "anchor": "exercise-define-the-effective-weight-matrices"
    },
    {
      "title": "Exercise - create the 1D Fourier basis",
      "anchor": "exercise-create-the-1d-fourier-basis"
    },
    {
      "title": "Exercise - 1D Fourier transform",
      "anchor": "exercise-1d-fourier-transform"
    },
    {
      "title": "Exercise - create the 2D Fourier basis",
      "anchor": "exercise-create-the-2d-fourier-basis"
    },
    {
      "title": "Exercise - Implementing the 2D Fourier Transform",
      "anchor": "exercise-implementing-the-2d-fourier-transform"
    },
    {
      "title": "Exercise - spot patterns in the activations",
      "anchor": "exercise-spot-patterns-in-the-activations"
    },
    {
      "title": "Exercise - calculate the mean squared coefficient",
      "anchor": "exercise-calculate-the-mean-squared-coefficient"
    },
    {
      "title": "Exercise - verify the quadratic term matters, and that $\\gamma > 0$",
      "anchor": "exercise-verify-the-quadratic-term-matters-and-that-gamma-0"
    },
    {
      "title": "Exercise - find neuron clusters",
      "anchor": "exercise-find-neuron-clusters"
    },
    {
      "title": "Exercise - validate neuron clusters",
      "anchor": "exercise-validate-neuron-clusters"
    },
    {
      "title": "Exercise - validate by only taking quadratic terms",
      "anchor": "exercise-validate-by-only-taking-quadratic-terms"
    },
    {
      "title": "Exercise - implement excluded loss",
      "anchor": "exercise-implement-excluded-loss"
    },
    {
      "title": "Exercise - define `fourier_embed`",
      "anchor": "exercise-define-fourier-embed"
    },
    {
      "title": "Exercise - Examine the SVD of $W_E$",
      "anchor": "exercise-examine-the-svd-of-w-e"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part53_othellogpt/1.5.3_OthelloGPT_exercises.ipynb": [
    {
      "title": "Exercise - calculate probe cosine similarities",
      "anchor": "exercise-calculate-probe-cosine-similarities"
    },
    {
      "title": "Exercise - define your probe directions",
      "anchor": "exercise-define-your-probe-directions"
    },
    {
      "title": "Exercise - define the `apply_scale` function",
      "anchor": "exercise-define-the-apply-scale-function"
    },
    {
      "title": "Exercise - compute attn and mlp contributions",
      "anchor": "exercise-compute-attn-and-mlp-contributions"
    },
    {
      "title": "Exercise - repeat this for the \"blank\" probe",
      "anchor": "exercise-repeat-this-for-the-blank-probe"
    },
    {
      "title": "Exercise - calculate neuron input weights",
      "anchor": "exercise-calculate-neuron-input-weights"
    },
    {
      "title": "Exercise - test your hypothesis (output behaviour)",
      "anchor": "exercise-test-your-hypothesis-output-behaviour"
    },
    {
      "title": "Exercise - create a patching metric",
      "anchor": "exercise-create-a-patching-metric"
    },
    {
      "title": "Exercise - write a patching function",
      "anchor": "exercise-write-a-patching-function"
    },
    {
      "title": "Exercise - compare the unembeds for C0 and D1",
      "anchor": "exercise-compare-the-unembeds-for-c0-and-d1"
    },
    {
      "title": "Exercise - compute fraction of variance explained by unembedding subspace",
      "anchor": "exercise-compute-fraction-of-variance-explained-by-unembedding-subspace"
    },
    {
      "title": "Exercise - figure out what's going on with one of these games",
      "anchor": "exercise-figure-out-what-s-going-on-with-one-of-these-games"
    },
    {
      "title": "Exercise - investigate more neurons",
      "anchor": "exercise-investigate-more-neurons"
    },
    {
      "title": "Exercise - investigate this spectrum plot",
      "anchor": "exercise-investigate-this-spectrum-plot"
    },
    {
      "title": "Exercise - make more spectrum plots",
      "anchor": "exercise-make-more-spectrum-plots"
    },
    {
      "title": "Exercise - fill in the missing code below",
      "anchor": "exercise-fill-in-the-missing-code-below"
    },
    {
      "title": "Exercise - train all 3 modes at once (bonus)",
      "anchor": "exercise-train-all-3-modes-at-once-bonus"
    }
  ],
  "content/ARENA_5.0-main/chapter1_transformer_interp/exercises/part54_toy_models_of_superposition_and_saes/1.5.4_Toy_Models_of_Superposition_&_SAEs_exercises.ipynb": [
    {
      "title": "Exercise - implement `forward`",
      "anchor": "exercise-implement-forward"
    },
    {
      "title": "Exercise - implement `generate_batch`",
      "anchor": "exercise-implement-generate-batch"
    },
    {
      "title": "Exercise - implement `calculate_loss`",
      "anchor": "exercise-implement-calculate-loss"
    },
    {
      "title": "Exercise - interpret these diagrams",
      "anchor": "exercise-interpret-these-diagrams"
    },
    {
      "title": "Exercise - implement `generate_correlated_batch`",
      "anchor": "exercise-implement-generate-correlated-batch"
    },
    {
      "title": "Exercise - generate more correlated feature plots",
      "anchor": "exercise-generate-more-correlated-feature-plots"
    },
    {
      "title": "Exercise - implement `NeuronModel`",
      "anchor": "exercise-implement-neuronmodel"
    },
    {
      "title": "Exercise - interpret these plots",
      "anchor": "exercise-interpret-these-plots"
    },
    {
      "title": "Exercise (optional) - replicate plots more faithfully",
      "anchor": "exercise-optional-replicate-plots-more-faithfully"
    },
    {
      "title": "Exercise - implement `NeuronComputationModel`",
      "anchor": "exercise-implement-neuroncomputationmodel"
    },
    {
      "title": "Exercise - compute dimensionality",
      "anchor": "exercise-compute-dimensionality"
    },
    {
      "title": "Exercise - implement `__init__`",
      "anchor": "exercise-implement-init"
    },
    {
      "title": "Exercise - implement `W_dec_normalized`",
      "anchor": "exercise-implement-w-dec-normalized"
    },
    {
      "title": "Exercise - implement `generate_batch`",
      "anchor": "exercise-implement-generate-batch"
    },
    {
      "title": "Exercise - implement `forward`",
      "anchor": "exercise-implement-forward"
    },
    {
      "title": "Exercise - implement `resample_simple`",
      "anchor": "exercise-implement-resample-simple"
    },
    {
      "title": "Exercise - implement `resample_advanced`",
      "anchor": "exercise-implement-resample-advanced"
    },
    {
      "title": "Exercise - implement Gated SAEs",
      "anchor": "exercise-implement-gated-saes"
    },
    {
      "title": "Exercise - demonstrate advantage of Gated models",
      "anchor": "exercise-demonstrate-advantage-of-gated-models"
    },
    {
      "title": "Exercise - implement custom gradient functions",
      "anchor": "exercise-implement-custom-gradient-functions"
    },
    {
      "title": "Exercise - implement JumpReLU SAEs",
      "anchor": "exercise-implement-jumprelu-saes"
    }
  ],
  "content/ARENA_5.0-main/chapter2_rl/exercises/part1_intro_to_rl/2.1_Intro_to_RL_exercises.ipynb": [
    {
      "title": "Exercise - reason about toy environment",
      "anchor": "exercise-reason-about-toy-environment"
    },
    {
      "title": "Exercise - implement `policy_eval_numerical`",
      "anchor": "exercise-implement-policy-eval-numerical"
    },
    {
      "title": "Exercise - implement `policy_eval_exact`",
      "anchor": "exercise-implement-policy-eval-exact"
    },
    {
      "title": "Exercise - implement `policy_improvement`",
      "anchor": "exercise-implement-policy-improvement"
    },
    {
      "title": "Exercise - implement `find_optimal_policy`",
      "anchor": "exercise-implement-find-optimal-policy"
    },
    {
      "title": "Exercise - implement `Cheater`",
      "anchor": "exercise-implement-cheater"
    },
    {
      "title": "Exercise - Implement Q-learning and SARSA",
      "anchor": "exercise-implement-q-learning-and-sarsa"
    },
    {
      "title": "Exercise - Implement SARSA($\\lambda$)",
      "anchor": "exercise-implement-sarsa-lambda"
    },
    {
      "title": "Exercise - implement `RandomAgent`",
      "anchor": "exercise-implement-randomagent"
    },
    {
      "title": "Exercise - Implement reward averaging",
      "anchor": "exercise-implement-reward-averaging"
    },
    {
      "title": "Exercise - implement cheater agent",
      "anchor": "exercise-implement-cheater-agent"
    },
    {
      "title": "Exercise - implement UCB selection",
      "anchor": "exercise-implement-ucb-selection"
    }
  ],
  "content/ARENA_5.0-main/chapter2_rl/exercises/part21_dqn/2.2.1_DQN_exercises.ipynb": [
    {
      "title": "Exercise - implement `QNetwork`",
      "anchor": "exercise-implement-qnetwork"
    },
    {
      "title": "Exercise - implement linear scheduler",
      "anchor": "exercise-implement-linear-scheduler"
    },
    {
      "title": "Exercise - implement the epsilon greedy policy",
      "anchor": "exercise-implement-the-epsilon-greedy-policy"
    },
    {
      "title": "Exercise - read & understand other probe environments",
      "anchor": "exercise-read-understand-other-probe-environments"
    },
    {
      "title": "Exercise - fill in the agent class",
      "anchor": "exercise-fill-in-the-agent-class"
    },
    {
      "title": "Exercise - write DQN training loop",
      "anchor": "exercise-write-dqn-training-loop"
    }
  ],
  "content/ARENA_5.0-main/chapter2_rl/exercises/part22_vpg/2.2.2_VPG_exercises.ipynb": [
    {
      "title": "Exercise - implement `PolicyNetwork`",
      "anchor": "exercise-implement-policynetwork"
    },
    {
      "title": "Exercise - implement `Rollout Buffer`",
      "anchor": "exercise-implement-rollout-buffer"
    },
    {
      "title": "Exercise - implement `VPGAgent`",
      "anchor": "exercise-implement-vpgagent"
    },
    {
      "title": "Exercise - implement `compute_returns`",
      "anchor": "exercise-implement-compute-returns"
    },
    {
      "title": "Exercise - implement `compute_logprobs`",
      "anchor": "exercise-implement-compute-logprobs"
    },
    {
      "title": "Exercise - implement `compute_importance_weights`",
      "anchor": "exercise-implement-compute-importance-weights"
    },
    {
      "title": "Exercise - implement `normalize_returns`",
      "anchor": "exercise-implement-normalize-returns"
    },
    {
      "title": "Exercise - implement `compute_reinforce_loss`",
      "anchor": "exercise-implement-compute-reinforce-loss"
    },
    {
      "title": "Exercise - implement `VPGTrainer`",
      "anchor": "exercise-implement-vpgtrainer"
    }
  ],
  "content/ARENA_5.0-main/chapter2_rl/exercises/part3_ppo/2.3_PPO_exercises.ipynb": [
    {
      "title": "Exercise - implement `get_actor_and_critic`",
      "anchor": "exercise-implement-get-actor-and-critic"
    },
    {
      "title": "Exercise - implement `compute_advantages`",
      "anchor": "exercise-implement-compute-advantages"
    },
    {
      "title": "Exercise - implement `minibatch_indices`",
      "anchor": "exercise-implement-minibatch-indices"
    },
    {
      "title": "Exercise - implement `PPOAgent`",
      "anchor": "exercise-implement-ppoagent"
    },
    {
      "title": "Exercise - write `calc_clipped_surrogate_objective`",
      "anchor": "exercise-write-calc-clipped-surrogate-objective"
    },
    {
      "title": "Exercise - write `calc_value_function_loss`",
      "anchor": "exercise-write-calc-value-function-loss"
    },
    {
      "title": "Exercise - write `calc_entropy_bonus`",
      "anchor": "exercise-write-calc-entropy-bonus"
    },
    {
      "title": "Exercise - implement `PPOScheduler`",
      "anchor": "exercise-implement-pposcheduler"
    },
    {
      "title": "Exercise - complete the `PPOTrainer` class",
      "anchor": "exercise-complete-the-ppotrainer-class"
    },
    {
      "title": "Exercise - implement reward shaping",
      "anchor": "exercise-implement-reward-shaping"
    },
    {
      "title": "Exercise - rewrite `get_actor_and_critic`",
      "anchor": "exercise-rewrite-get-actor-and-critic"
    },
    {
      "title": "Exercise - implement `Actor` and `Critic`",
      "anchor": "exercise-implement-actor-and-critic"
    },
    {
      "title": "Exercise - additional rewrites",
      "anchor": "exercise-additional-rewrites"
    },
    {
      "title": "Exercise - design a reward function for Pendulum",
      "anchor": "exercise-design-a-reward-function-for-pendulum"
    }
  ],
  "content/ARENA_5.0-main/chapter2_rl/exercises/part4_rlhf/2.4_RLHF_exercises.ipynb": [
    {
      "title": "Exercise - implement `HookedTransformerWithValueHead`",
      "anchor": "exercise-implement-hookedtransformerwithvaluehead"
    },
    {
      "title": "Exercise - implement `reward_fn_char_count`",
      "anchor": "exercise-implement-reward-fn-char-count"
    },
    {
      "title": "Exercise - brainstorm your reward function",
      "anchor": "exercise-brainstorm-your-reward-function"
    },
    {
      "title": "Exercise - implement `normalize_reward`",
      "anchor": "exercise-implement-normalize-reward"
    },
    {
      "title": "Exercise - implement `get_advantages`",
      "anchor": "exercise-implement-get-advantages"
    },
    {
      "title": "Exercise - implement `calc_kl_penalty`",
      "anchor": "exercise-implement-calc-kl-penalty"
    },
    {
      "title": "Exercise - (re)implement `compute_entropy_bonus`",
      "anchor": "exercise-re-implement-compute-entropy-bonus"
    },
    {
      "title": "Exercise - implement `get_logprobs`",
      "anchor": "exercise-implement-get-logprobs"
    },
    {
      "title": "Exercise - implement `get_optimizer`",
      "anchor": "exercise-implement-get-optimizer"
    },
    {
      "title": "Exercise - complete `RLHFTrainer`",
      "anchor": "exercise-complete-rlhftrainer"
    },
    {
      "title": "Exercise - use a more complex reward function",
      "anchor": "exercise-use-a-more-complex-reward-function"
    },
    {
      "title": "Exercise - complete `Lora`",
      "anchor": "exercise-complete-lora"
    },
    {
      "title": "Exercise - complete `LoraHooks`",
      "anchor": "exercise-complete-lorahooks"
    },
    {
      "title": "Exercise - complete `TransformerWithValueHeadLora`",
      "anchor": "exercise-complete-transformerwithvalueheadlora"
    },
    {
      "title": "Exercise: Construct GRPO trainer",
      "anchor": "exercise-construct-grpo-trainer"
    }
  ],
  "content/ARENA_5.0-main/chapter3_llm_evals/exercises/part1_intro_to_evals/3.1_Intro_to_Evals_exercises.ipynb": [
    {
      "title": "Exercise - retry with exponential back-off (optional)",
      "anchor": "exercise-retry-with-exponential-back-off-optional"
    },
    {
      "title": "Exercise - replicate alignment faking",
      "anchor": "exercise-replicate-alignment-faking"
    },
    {
      "title": "Exercise - Build threat models",
      "anchor": "exercise-build-threat-models"
    },
    {
      "title": "Exercise - Design a specification",
      "anchor": "exercise-design-a-specification"
    },
    {
      "title": "Exercise - Engineer eval question prompt",
      "anchor": "exercise-engineer-eval-question-prompt"
    }
  ],
  "content/ARENA_5.0-main/chapter3_llm_evals/exercises/part2_dataset_generation/3.2_Dataset_Generation_exercises.ipynb": [
    {
      "title": "Exercise - Generate structured MCQ outputs",
      "anchor": "exercise-generate-structured-mcq-outputs"
    },
    {
      "title": "Exercise - Write prompts for question generation",
      "anchor": "exercise-write-prompts-for-question-generation"
    },
    {
      "title": "Exercise - Write few-shot prompts for generation",
      "anchor": "exercise-write-few-shot-prompts-for-generation"
    },
    {
      "title": "Exercise - Add variance prompts",
      "anchor": "exercise-add-variance-prompts"
    },
    {
      "title": "Exercise - Write prompt-generation function with concurrency",
      "anchor": "exercise-write-prompt-generation-function-with-concurrency"
    },
    {
      "title": "Exercise - Write a scoring function",
      "anchor": "exercise-write-a-scoring-function"
    },
    {
      "title": "Exercise - Checks and summary statistics",
      "anchor": "exercise-checks-and-summary-statistics"
    },
    {
      "title": "Exercise - Filter dataset",
      "anchor": "exercise-filter-dataset"
    },
    {
      "title": "Exercise - Generate a final question set",
      "anchor": "exercise-generate-a-final-question-set"
    }
  ],
  "content/ARENA_5.0-main/chapter3_llm_evals/exercises/part3_running_evals_with_inspect/3.3_Running_Evals_with_Inspect_exercises.ipynb": [
    {
      "title": "Exercise - write `record_to_sample` for your dataset",
      "anchor": "exercise-write-record-to-sample-for-your-dataset"
    },
    {
      "title": "Exercise - implement `prompt_template` solver",
      "anchor": "exercise-implement-prompt-template-solver"
    },
    {
      "title": "Exercise - implement `multiple_choice_format` solver",
      "anchor": "exercise-implement-multiple-choice-format-solver"
    },
    {
      "title": "Exercise - implement `make_choice` solver",
      "anchor": "exercise-implement-make-choice-solver"
    },
    {
      "title": "Exercise - implement `self_critique_format` solver",
      "anchor": "exercise-implement-self-critique-format-solver"
    },
    {
      "title": "Exercise (optional) - Write your own solvers",
      "anchor": "exercise-optional-write-your-own-solvers"
    },
    {
      "title": "Exercise - Write a simple scorer",
      "anchor": "exercise-write-a-simple-scorer"
    },
    {
      "title": "Exercise (optional) - Write your own scorer(s)",
      "anchor": "exercise-optional-write-your-own-scorer-s"
    },
    {
      "title": "Exercise - implement `record_to_sample_shuffle`",
      "anchor": "exercise-implement-record-to-sample-shuffle"
    },
    {
      "title": "Exercise - implement `record_to_sample_full`",
      "anchor": "exercise-implement-record-to-sample-full"
    },
    {
      "title": "Exercise - implement the `benchmark_eval` task",
      "anchor": "exercise-implement-the-benchmark-eval-task"
    },
    {
      "title": "Exercise - finalize & run your eval",
      "anchor": "exercise-finalize-run-your-eval"
    },
    {
      "title": "Exercise - run full eval sweeps",
      "anchor": "exercise-run-full-eval-sweeps"
    },
    {
      "title": "Exercise (optional) - Extract data from log files",
      "anchor": "exercise-optional-extract-data-from-log-files"
    },
    {
      "title": "Exercise (optional) - Use plotly (and Claude) to plot the results of your evaluation",
      "anchor": "exercise-optional-use-plotly-and-claude-to-plot-the-results-of-your-evaluation"
    }
  ],
  "content/ARENA_5.0-main/chapter3_llm_evals/exercises/part4_llm_agents/3.4_LLM_Agents_exercises.ipynb": [
    {
      "title": "Exercise - Build a simple arithmetic task",
      "anchor": "exercise-build-a-simple-arithmetic-task"
    },
    {
      "title": "Exercise - Write `CalculateTool`",
      "anchor": "exercise-write-calculatetool"
    },
    {
      "title": "Exercise - Build an `ArithmeticAgent`",
      "anchor": "exercise-build-an-arithmeticagent"
    },
    {
      "title": "Exercise - Use eval to run the agent",
      "anchor": "exercise-use-eval-to-run-the-agent"
    },
    {
      "title": "Exercise - Implement `get_permitted_links()`",
      "anchor": "exercise-implement-get-permitted-links"
    },
    {
      "title": "Exercise - Build tools for the WikiGame",
      "anchor": "exercise-build-tools-for-the-wikigame"
    },
    {
      "title": "Exercise - Build a WikiAgent",
      "anchor": "exercise-build-a-wikiagent"
    },
    {
      "title": "Exercise - Run the task",
      "anchor": "exercise-run-the-task"
    },
    {
      "title": "Exercise - Engineer prompts",
      "anchor": "exercise-engineer-prompts"
    },
    {
      "title": "Exercise - Implement the ReAct framework",
      "anchor": "exercise-implement-the-react-framework"
    },
    {
      "title": "Exercise - Let the LLM see its entire chat history",
      "anchor": "exercise-let-the-llm-see-its-entire-chat-history"
    },
    {
      "title": "Exercise - Implement a reflexion tool",
      "anchor": "exercise-implement-a-reflexion-tool"
    },
    {
      "title": "Exercise - Implement additional rules",
      "anchor": "exercise-implement-additional-rules"
    }
  ],
  "content/ARENA_5.0-main/chapter4_alignment_science/exercises/part1_emergent_misalignment/4.1_Emergent_Misalignment_exercises.ipynb": [
    {
      "title": "Exercise - test_generalization",
      "anchor": "exercise-test-generalization"
    },
    {
      "title": "Exercise - Implementing an Autorater",
      "anchor": "exercise-implementing-an-autorater"
    },
    {
      "title": "Exercise - Implement Steering Hook",
      "anchor": "exercise-implement-steering-hook"
    },
    {
      "title": "Exercise - Generate Calibration Responses",
      "anchor": "exercise-generate-calibration-responses"
    },
    {
      "title": "Exercise - Extract Contrastive Steering Vector",
      "anchor": "exercise-extract-contrastive-steering-vector"
    },
    {
      "title": "Exercise - Coherence Autorater",
      "anchor": "exercise-coherence-autorater"
    },
    {
      "title": "Exercise - Evaluate Steering Effectiveness",
      "anchor": "exercise-evaluate-steering-effectiveness"
    },
    {
      "title": "Exercise - `compute_response_kl`",
      "anchor": "exercise-compute-response-kl"
    },
    {
      "title": "Exercise - Extract LoRA norms across training",
      "anchor": "exercise-extract-lora-norms-across-training"
    },
    {
      "title": "Exercise - Compute PCA trajectory",
      "anchor": "exercise-compute-pca-trajectory"
    },
    {
      "title": "Exercise - Compute local cosine similarity",
      "anchor": "exercise-compute-local-cosine-similarity"
    },
    {
      "title": "Exercise - Find transition point",
      "anchor": "exercise-find-transition-point"
    }
  ],
  "content/ARENA_5.0-main/chapter4_alignment_science/exercises/part2_science_of_misalignment/4.2_Science_of_Misalignment_exercises.ipynb": [
    {
      "title": "Exercise - Implement bypass detection",
      "anchor": "exercise-implement-bypass-detection"
    },
    {
      "title": "Exercise - Integration: Complete Bash Simulator",
      "anchor": "exercise-integration-complete-bash-simulator"
    },
    {
      "title": "Exercise - main experiment loop",
      "anchor": "exercise-main-experiment-loop"
    },
    {
      "title": "Exercise - Write system prompt variants",
      "anchor": "exercise-write-system-prompt-variants"
    },
    {
      "title": "Exercise - Post-task shutdown control",
      "anchor": "exercise-post-task-shutdown-control"
    },
    {
      "title": "Exercise - Replicate Scratchpad Alignment Faking",
      "anchor": "exercise-replicate-scratchpad-alignment-faking"
    },
    {
      "title": "Exercise - Build Regex Classifier",
      "anchor": "exercise-build-regex-classifier"
    },
    {
      "title": "Exercise - Build LLM Autorater",
      "anchor": "exercise-build-llm-autorater"
    },
    {
      "title": "Exercise - Build Response Judge (optional)",
      "anchor": "exercise-build-response-judge-optional"
    },
    {
      "title": "Exercise - Red-Team Your Results",
      "anchor": "exercise-red-team-your-results"
    }
  ],
  "content/ARENA_5.0-main/chapter4_alignment_science/exercises/part3_interpreting_reasoning_models/4.3_Interpreting_Reasoning_Models_exercises.ipynb": [
    {
      "title": "Exercise - heuristic-based categorization",
      "anchor": "exercise-heuristic-based-categorization"
    },
    {
      "title": "Exercise - implement an autorater",
      "anchor": "exercise-implement-an-autorater"
    },
    {
      "title": "Exercise - calculate forced answer importance",
      "anchor": "exercise-calculate-forced-answer-importance"
    },
    {
      "title": "Exercise - compare resampling importance",
      "anchor": "exercise-compare-resampling-importance"
    },
    {
      "title": "Exercise - compute counterfactual importance",
      "anchor": "exercise-compute-counterfactual-importance"
    },
    {
      "title": "Exercise - replicate Figure 3b (sentence category effect)",
      "anchor": "exercise-replicate-figure-3b-sentence-category-effect"
    },
    {
      "title": "Exercise - replicate causal graph",
      "anchor": "exercise-replicate-causal-graph"
    },
    {
      "title": "Exercise - implement resampling (optional)",
      "anchor": "exercise-implement-resampling-optional"
    },
    {
      "title": "Exercise - extract attention matrices",
      "anchor": "exercise-extract-attention-matrices"
    },
    {
      "title": "Exercise - compute vertical attention scores (Part 1: Simple version)",
      "anchor": "exercise-compute-vertical-attention-scores-part-1-simple-version"
    },
    {
      "title": "Exercise - compute vertical attention scores (Part 2: Full version with depth control)",
      "anchor": "exercise-compute-vertical-attention-scores-part-2-full-version-with-depth-control"
    },
    {
      "title": "Exercise - identify receiver heads from real CoT",
      "anchor": "exercise-identify-receiver-heads-from-real-cot"
    },
    {
      "title": "Exercise - compute receiver head scores",
      "anchor": "exercise-compute-receiver-head-scores"
    },
    {
      "title": "Exercise - implement RoPE attention",
      "anchor": "exercise-implement-rope-attention"
    },
    {
      "title": "Exercise - compute suppressed attention",
      "anchor": "exercise-compute-suppressed-attention"
    },
    {
      "title": "Exercise - measure suppression effect with KL divergence",
      "anchor": "exercise-measure-suppression-effect-with-kl-divergence"
    },
    {
      "title": "Exercise - compare DTF (inverse resilience) across categories",
      "anchor": "exercise-compare-dtf-inverse-resilience-across-categories"
    }
  ],
  "content/ARENA_5.0-main/chapter4_alignment_science/exercises/part4_persona_vectors/4.4_LLM_Psychology_&_Persona_Vectors_exercises.ipynb": [
    {
      "title": "Exercise - Design LLM judge prompt for role-playing",
      "anchor": "exercise-design-llm-judge-prompt-for-role-playing"
    },
    {
      "title": "Exercise - Generate responses for all personas",
      "anchor": "exercise-generate-responses-for-all-personas"
    },
    {
      "title": "Exercise - Extract response activations",
      "anchor": "exercise-extract-response-activations"
    },
    {
      "title": "Exercise - Extract persona vectors",
      "anchor": "exercise-extract-persona-vectors"
    },
    {
      "title": "Exercise - Compute cosine similarity matrix",
      "anchor": "exercise-compute-cosine-similarity-matrix"
    },
    {
      "title": "Exercise - PCA analysis and Assistant Axis",
      "anchor": "exercise-pca-analysis-and-assistant-axis"
    },
    {
      "title": "Exercise - Build a ConversationAnalyzer class",
      "anchor": "exercise-build-a-conversationanalyzer-class"
    },
    {
      "title": "Exercise - Autorater for delusional behavior",
      "anchor": "exercise-autorater-for-delusional-behavior"
    },
    {
      "title": "Exercise - Implement steering hook",
      "anchor": "exercise-implement-steering-hook"
    },
    {
      "title": "Exercise - Steering experiments",
      "anchor": "exercise-steering-experiments"
    },
    {
      "title": "Exercise - Implement `ActivationCapper`",
      "anchor": "exercise-implement-activationcapper"
    },
    {
      "title": "Exercise - Run a multi-turn capping experiment",
      "anchor": "exercise-run-a-multi-turn-capping-experiment"
    },
    {
      "title": "Exercise - Generate contrastive responses",
      "anchor": "exercise-generate-contrastive-responses"
    },
    {
      "title": "Exercise - Extract contrastive trait vectors",
      "anchor": "exercise-extract-contrastive-trait-vectors"
    },
    {
      "title": "Exercise - Implement the ActivationSteerer",
      "anchor": "exercise-implement-the-activationsteerer"
    },
    {
      "title": "Exercise - Steering experiments (sycophancy)",
      "anchor": "exercise-steering-experiments-sycophancy"
    },
    {
      "title": "Exercise - Projection-based monitoring",
      "anchor": "exercise-projection-based-monitoring"
    },
    {
      "title": "Exercise - Multi-trait pipeline",
      "anchor": "exercise-multi-trait-pipeline"
    },
    {
      "title": "Exercise - Multi-trait geometry",
      "anchor": "exercise-multi-trait-geometry"
    }
  ],
  "content/ARENA_5.0-main/chapter4_alignment_science/exercises/part5_investigator_agents/4.5_Investigator_Agents_exercises.ipynb": [
    {
      "title": "Exercise - Load character files",
      "anchor": "exercise-load-character-files"
    },
    {
      "title": "Exercise - Implement the LLM-driven red-team message generator",
      "anchor": "exercise-implement-the-llm-driven-red-team-message-generator"
    },
    {
      "title": "Exercise - Run dynamic persona conversation",
      "anchor": "exercise-run-dynamic-persona-conversation"
    },
    {
      "title": "Exercise - Grade with the official rubric",
      "anchor": "exercise-grade-with-the-official-rubric"
    },
    {
      "title": "Exercise - Parallel red-team campaign with ThreadPoolExecutor",
      "anchor": "exercise-parallel-red-team-campaign-with-threadpoolexecutor"
    },
    {
      "title": "Exercise - Implement tool dispatch logic",
      "anchor": "exercise-implement-tool-dispatch-logic"
    },
    {
      "title": "Exercise - Implement the auditor conversation loop",
      "anchor": "exercise-implement-the-auditor-conversation-loop"
    },
    {
      "title": "Exercise - Build a simplified judge",
      "anchor": "exercise-build-a-simplified-judge"
    },
    {
      "title": "Exercise - Run Petri on AI psychosis (Python API)",
      "anchor": "exercise-run-petri-on-ai-psychosis-python-api"
    },
    {
      "title": "Exercise - Implement `measure_whistleblowing_propensity`",
      "anchor": "exercise-implement-measure-whistleblowing-propensity"
    },
    {
      "title": "Exercise - Trace a Petri investigation",
      "anchor": "exercise-trace-a-petri-investigation"
    },
    {
      "title": "Exercise - Implement custom tool",
      "anchor": "exercise-implement-custom-tool"
    },
    {
      "title": "Exercise - Rollback demo",
      "anchor": "exercise-rollback-demo"
    },
    {
      "title": "Exercise - Implement super-agent aggregation",
      "anchor": "exercise-implement-super-agent-aggregation"
    },
    {
      "title": "Exercise - Build a realism classifier",
      "anchor": "exercise-build-a-realism-classifier"
    }
  ]
};
