window.ARENA_STAGE1_PROBLEMS = [
  {
    id: "arena-0.0-prereqs",
    chapterId: "chapter0_fundamentals",
    chapterLabel: "Fundamentals",
    sectionLabel: "0.0 Prerequisites",
    title: "Prerequisites",
    summary:
      "Foundational array and tensor manipulation warm-up. This is a good first problem unit for testing the problem-registry flow because it is scoped tightly and maps cleanly onto Delta Drills prerequisite skills.",
    readinessScore: 78,
    readinessLabel: "Likely ready",
    readinessNote:
      "Stage 1 uses a placeholder readiness estimate. Later stages should replace this with a user-specific score computed from Delta Drills skill state.",
    prerequisiteTags: ["NumPy basics", "Array shapes", "Broadcasting intuition", "Einops familiarity"],
    skillWeights: [
      { skill: "NumPy", weight: 0.35 },
      { skill: "Broadcasting", weight: 0.3 },
      { skill: "Einops", weight: 0.2 },
      { skill: "Tensor shapes", weight: 0.15 },
    ],
    lessonPath: "ARENA_4.0-main/chapter0_fundamentals/instructions/pages/00_[0.0]_Prerequisites.md",
    notebookPath: "ARENA_4.0-main/chapter0_fundamentals/exercises/part0_prereqs/0.0_Prerequisites_exercises.ipynb",
    backupNotebookPath: "ARENA_3.0-main/chapter0_fundamentals/exercises/part0_prereqs/0.0_Prerequisites_exercises.ipynb",
    launchPath: "ARENA_4.0-main/chapter0_fundamentals/exercises/part0_prereqs/0.0_Prerequisites_exercises.ipynb",
    executionMode: "Notebook file launch placeholder",
  },
  {
    id: "arena-0.1-ray-tracing",
    chapterId: "chapter0_fundamentals",
    chapterLabel: "Fundamentals",
    sectionLabel: "0.1 Ray Tracing",
    title: "Ray Tracing",
    summary:
      "A more geometric fundamentals unit with a precise notebook target. This gives you a second stage-1 problem page that is clearly different from prerequisites while still staying in the safer early-fundamentals area.",
    readinessScore: 64,
    readinessLabel: "Borderline ready",
    readinessNote:
      "Placeholder readiness only. Use this page to verify that Delta Drills can describe why a user might need prerequisite review before launching.",
    prerequisiteTags: ["Vector math", "NumPy indexing", "Broadcasting", "Linear algebra basics"],
    skillWeights: [
      { skill: "NumPy", weight: 0.25 },
      { skill: "Broadcasting", weight: 0.25 },
      { skill: "Linear algebra", weight: 0.3 },
      { skill: "Geometry reasoning", weight: 0.2 },
    ],
    lessonPath: "ARENA_4.0-main/chapter0_fundamentals/instructions/pages/01_[0.1]_Ray_Tracing.md",
    notebookPath: "ARENA_4.0-main/chapter0_fundamentals/exercises/part1_ray_tracing/0.1_Ray_Tracing_exercises.ipynb",
    backupNotebookPath: "ARENA_3.0-main/chapter0_fundamentals/exercises/part1_ray_tracing/0.1_Ray_Tracing_exercises.ipynb",
    launchPath: "ARENA_4.0-main/chapter0_fundamentals/exercises/part1_ray_tracing/0.1_Ray_Tracing_exercises.ipynb",
    executionMode: "Notebook file launch placeholder",
  },
  {
    id: "arena-2.1-intro-to-rl",
    chapterId: "chapter2_rl",
    chapterLabel: "Reinforcement Learning",
    sectionLabel: "2.1 Intro to RL",
    title: "Intro to RL",
    summary:
      "An example of a heavier ARENA problem unit that still benefits from problem-level indexing inside Delta Drills. Stage 1 should let you inspect the exact notebook target and prerequisite profile before any deeper runtime integration exists.",
    readinessScore: 41,
    readinessLabel: "Needs prerequisite study",
    readinessNote:
      "This intentionally shows a lower placeholder readiness to exercise the dedicated problem-page UX for underprepared users.",
    prerequisiteTags: ["PyTorch basics", "Optimization", "Probability", "MDP intuition"],
    skillWeights: [
      { skill: "PyTorch", weight: 0.3 },
      { skill: "Optimization", weight: 0.2 },
      { skill: "Probability", weight: 0.25 },
      { skill: "RL concepts", weight: 0.25 },
    ],
    lessonPath: "ARENA_4.0-main/chapter2_rl/instructions/pages/10_[2.1]_Intro_to_RL.md",
    notebookPath: "ARENA_4.0-main/chapter2_rl/exercises/part1_intro_to_rl/2.1_Intro_to_RL_exercises.ipynb",
    backupNotebookPath: "ARENA_3.0-main/chapter2_rl/exercises/part1_intro_to_rl/2.1_Intro_to_RL_exercises.ipynb",
    launchPath: "ARENA_4.0-main/chapter2_rl/exercises/part1_intro_to_rl/2.1_Intro_to_RL_exercises.ipynb",
    executionMode: "Notebook file launch placeholder",
  },
  {
    id: "arena-3.1-intro-to-evals",
    chapterId: "chapter3_llm_evals",
    chapterLabel: "LLM Evals",
    sectionLabel: "3.1 Intro to Evals",
    title: "Intro to Evals",
    summary:
      "A stage-1 test case for later chapters. This page is mainly for verifying that Delta Drills can represent exact problem units, weighted skills, and launch metadata even when the eventual runtime path will likely need more infrastructure.",
    readinessScore: 53,
    readinessLabel: "Partially ready",
    readinessNote:
      "Use this as a test of chapter diversity in the registry rather than as proof of full browser execution support.",
    prerequisiteTags: ["Python fluency", "Prompting", "Evaluation design", "Basic statistics"],
    skillWeights: [
      { skill: "LLM evals", weight: 0.35 },
      { skill: "Prompting", weight: 0.2 },
      { skill: "Dataset reasoning", weight: 0.2 },
      { skill: "Statistics", weight: 0.25 },
    ],
    lessonPath: "ARENA_4.0-main/chapter3_llm_evals/instructions/pages/01_[3.1]_Intro_to_Evals.md",
    notebookPath: "ARENA_4.0-main/chapter3_llm_evals/exercises/part1_intro_to_evals/3.1_Intro_to_Evals_exercises.ipynb",
    backupNotebookPath: "ARENA_3.0-main/chapter3_llm_evals/exercises/part1_intro_to_evals/3.1_Intro_to_Evals_exercises.ipynb",
    launchPath: "ARENA_4.0-main/chapter3_llm_evals/exercises/part1_intro_to_evals/3.1_Intro_to_Evals_exercises.ipynb",
    executionMode: "Notebook file launch placeholder",
  },
];
