"""watch.py — health checks for vocab/

Validates the three canonical JSON files:
  - atoms.json          (atom vocabulary)
  - concept_edges.json  (semantic source of truth)
  - prereq_manual.json  (curriculum sequencing overrides)

Does NOT directly validate prereqs.json — that's generated by
scripts/derive_prereqs.py and validated separately by scripts/validate_graph.py.
"""
import sys
import os
import json
from collections import defaultdict, deque

HERE = os.path.dirname(os.path.abspath(__file__))
ATOMS_PATH = os.path.join(HERE, "atoms.json")
CONCEPT_PATH = os.path.join(HERE, "concept_edges.json")
MANUAL_PATH = os.path.join(HERE, "prereq_manual.json")

ATOM_REQUIRED_FIELDS = {"id", "label", "definition", "domain", "dd_coverage", "status"}
CONCEPT_EDGE_REQUIRED = {"from", "to", "kind", "status", "evidence"}
MANUAL_EDGE_REQUIRED = {"from", "to", "status", "rationale"}
VALID_STATUSES = {"seed", "proposed", "accepted", "deprecated"}
VALID_KINDS = {"is-a", "refines", "uses", "part-of", "alternative-to"}
DIRECTED_KINDS = VALID_KINDS - {"alternative-to"}


def _load(path):
    with open(path) as f:
        return json.load(f)


# ── Import checks ──────────────────────────────
def check_imports():
    for p in (ATOMS_PATH, CONCEPT_PATH, MANUAL_PATH):
        assert os.path.exists(p), f"missing {p}"
        _load(p)


# ── Public API checks ─────────────────────────
def check_public_api():
    atoms = _load(ATOMS_PATH)
    concept = _load(CONCEPT_PATH)
    manual = _load(MANUAL_PATH)
    assert "atoms" in atoms and isinstance(atoms["atoms"], list)
    assert "edges" in concept and isinstance(concept["edges"], list)
    assert "edges" in manual and isinstance(manual["edges"], list)
    assert atoms["atoms"], "atoms list is empty"


def _check_cycles(edges):
    adj = defaultdict(list)
    nodes = set()
    for e in edges:
        adj[e["from"]].append(e["to"])
        nodes.add(e["from"])
        nodes.add(e["to"])
    indeg = {n: 0 for n in nodes}
    for u in nodes:
        for v in adj[u]:
            indeg[v] += 1
    q = deque(n for n in nodes if indeg[n] == 0)
    visited = 0
    while q:
        u = q.popleft()
        visited += 1
        for v in adj[u]:
            indeg[v] -= 1
            if indeg[v] == 0:
                q.append(v)
    return [n for n in nodes if indeg[n] > 0] if visited != len(nodes) else []


# ── Invariant checks ──────────────────────────
def check_invariants():
    atoms = _load(ATOMS_PATH)["atoms"]
    concept = _load(CONCEPT_PATH)["edges"]
    manual = _load(MANUAL_PATH)["edges"]

    ids = []
    for a in atoms:
        missing = ATOM_REQUIRED_FIELDS - set(a.keys())
        assert not missing, f"atom {a.get('id', '?')} missing: {missing}"
        assert a["status"] in VALID_STATUSES, f"atom {a['id']} bad status: {a['status']}"
        ids.append(a["id"])
    dupes = [i for i in ids if ids.count(i) > 1]
    assert not dupes, f"duplicate atom ids: {dupes[:5]}"
    known = set(ids)

    seen_concept = set()
    for i, e in enumerate(concept):
        missing = CONCEPT_EDGE_REQUIRED - set(e.keys())
        assert not missing, f"concept[{i}] missing: {missing}"
        assert e["kind"] in VALID_KINDS, f"concept[{i}] bad kind: {e['kind']}"
        assert e["status"] in VALID_STATUSES, f"concept[{i}] bad status: {e['status']}"
        assert e["from"] in known, f"concept[{i}] unknown from: {e['from']}"
        assert e["to"] in known, f"concept[{i}] unknown to: {e['to']}"
        assert e["from"] != e["to"], f"concept[{i}] self-loop: {e['from']}"
        key = (e["from"], e["to"], e["kind"])
        assert key not in seen_concept, f"concept[{i}] duplicate: {key}"
        seen_concept.add(key)

    seen_manual = set()
    for i, e in enumerate(manual):
        missing = MANUAL_EDGE_REQUIRED - set(e.keys())
        assert not missing, f"manual[{i}] missing: {missing}"
        assert e["status"] in VALID_STATUSES, f"manual[{i}] bad status: {e['status']}"
        assert e["from"] in known, f"manual[{i}] unknown from: {e['from']}"
        assert e["to"] in known, f"manual[{i}] unknown to: {e['to']}"
        assert e["from"] != e["to"], f"manual[{i}] self-loop: {e['from']}"
        key = (e["from"], e["to"])
        assert key not in seen_manual, f"manual[{i}] duplicate: {key}"
        seen_manual.add(key)

    for kind in DIRECTED_KINDS:
        sub = [e for e in concept if e["kind"] == kind]
        cyc = _check_cycles(sub)
        assert not cyc, f"cycle in concept '{kind}' subgraph: {cyc[:5]}"