"""watch.py — health checks for chatgpt (runtime artifacts)

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import json
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED_PUBLIC = os.path.normpath(os.path.join(HERE, "..", "..", "Local_Deployed_Shared"))


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# This folder is runtime artifacts, not Python modules. Verify the artifacts
# the backend depends on are at least readable when present.
def check_imports():
    # api_key.txt is required for the AI repair pipeline to run, but its
    # absence is OK at watch time (someone may have rotated keys). Just verify
    # that *if* present, it isn't an empty file or accidentally checked-in.
    api_key_path = os.path.join(HERE, "api_key.txt")
    if os.path.isfile(api_key_path):
        size = os.path.getsize(api_key_path)
        assert size > 10, f"api_key.txt is implausibly small ({size} bytes)"


# ── Public API checks ─────────────────────────
# Verify the override / id-set artifacts the backend reads on startup parse
# correctly with the expected schema.
OVERRIDE_LAYERS = (
    "function_mode_overrides.jsonl",
    "function_mode_overrides_round2.jsonl",
    "function_mode_overrides_round3.jsonl",
    "einops_prompt_rewrite_overrides.jsonl",
    "numpy_einsum_prompt_rewrite_overrides.jsonl",
)


PROMPT_REWRITE_LAYERS = {
    "einops_prompt_rewrite_overrides.jsonl",
    "numpy_einsum_prompt_rewrite_overrides.jsonl",
}


def check_public_api():
    for fname in OVERRIDE_LAYERS:
        path = os.path.join(HERE, fname)
        if not os.path.isfile(path):
            continue
        for lineno, raw in enumerate(_read(path).splitlines(), 1):
            line = raw.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError as exc:
                raise AssertionError(f"{fname}:{lineno} not valid JSON: {exc}")
            assert isinstance(rec, dict), f"{fname}:{lineno} expected JSON object"
            assert isinstance(rec.get("id"), int), f"{fname}:{lineno} 'id' must be an int"
            if fname in PROMPT_REWRITE_LAYERS:
                qt = rec.get("question_text")
                assert isinstance(qt, str) and qt.strip(), (
                    f"{fname}:{lineno} 'question_text' missing/empty"
                )
            else:
                # round-1/2/3 carry runnable starter+test scaffolding
                assert isinstance(rec.get("starter_code"), str), (
                    f"{fname}:{lineno} id={rec['id']} missing 'starter_code'"
                )
                tcs = rec.get("test_cases")
                assert isinstance(tcs, list) and tcs, (
                    f"{fname}:{lineno} id={rec['id']} 'test_cases' must be non-empty list"
                )
                first = tcs[0]
                assert isinstance(first, dict), (
                    f"{fname}:{lineno} id={rec['id']} test_cases[0] must be object"
                )
                for required in ("setup_code", "call", "expected_expr"):
                    assert required in first, (
                        f"{fname}:{lineno} id={rec['id']} test_cases[0] missing {required!r}"
                    )

    for fname in ("function_mode_broken_ids.json", "function_mode_deleted_ids.json"):
        path = os.path.join(HERE, fname)
        if not os.path.isfile(path):
            continue
        try:
            data = json.loads(_read(path))
        except json.JSONDecodeError as exc:
            raise AssertionError(f"{fname} not valid JSON: {exc}")
        assert isinstance(data, list), f"{fname} must be a JSON array"
        for i, item in enumerate(data):
            assert isinstance(item, int), f"{fname}[{i}] must be int, got {type(item).__name__}"


# ── Invariant checks ──────────────────────────
# Structural rules:
#  1. api_key.txt must NEVER appear in the public bundle (Local_Deployed_Shared/).
#  2. einops_prompt_rewrite_overrides.jsonl rewrites must not still leak the
#     einops arrow pattern that prompted the rewrite in the first place.
#  3. broken_ids and deleted_ids should not collide with override ids — that
#     would mean we're both overriding and skipping the same question, which
#     is internally inconsistent.
def check_invariants():
    if os.path.isdir(SHARED_PUBLIC):
        for forbidden in ("api_key.txt", ".openai_key"):
            forbidden_path = os.path.join(SHARED_PUBLIC, forbidden)
            assert not os.path.isfile(forbidden_path), (
                f"secret {forbidden!r} must never live in the public bundle "
                f"({SHARED_PUBLIC}); it leaked from {HERE}"
            )

    # Prompt rewrites must not regress: einops rewrites should never re-leak the
    # arrow pattern, and numpy/einsum rewrites should never re-leak the strongest
    # canonical-function tokens (argmax/cumsum/tile/etc.) that prompted the rewrite.
    einops_path = os.path.join(HERE, "einops_prompt_rewrite_overrides.jsonl")
    if os.path.isfile(einops_path):
        for lineno, raw in enumerate(_read(einops_path).splitlines(), 1):
            line = raw.strip()
            if not line:
                continue
            rec = json.loads(line)
            qt = rec.get("question_text", "")
            assert "->" not in qt, (
                f"einops_prompt_rewrite_overrides.jsonl:{lineno} id={rec.get('id')} "
                f"still contains '->' (rewrite did not strip the pattern)"
            )

    numpy_einsum_path = os.path.join(HERE, "numpy_einsum_prompt_rewrite_overrides.jsonl")
    if os.path.isfile(numpy_einsum_path):
        # Strongest leaks — direct function-name verbs the rewrite must not use.
        # Excludes mechanics tokens like reshape/arange that often appear in setup.
        strong_leaks = (
            "argmax", "argmin", "argsort", "argpartition",
            "cumsum", "cumprod",
            "argwhere", "flatnonzero",
            "histogram", "bincount", "digitize",
            "tensordot", "matmul", "kron",
            "einsum",
            "rot90", "fliplr", "flipud", "swapaxes",
            "isclose", "allclose", "corrcoef",
        )
        leak_re = re.compile(r"(?<![a-zA-Z])(" + "|".join(strong_leaks) + r")(?![a-zA-Z])", re.IGNORECASE)
        for lineno, raw in enumerate(_read(numpy_einsum_path).splitlines(), 1):
            line = raw.strip()
            if not line:
                continue
            rec = json.loads(line)
            qt = rec.get("question_text", "")
            m = leak_re.search(qt)
            assert not m, (
                f"numpy_einsum_prompt_rewrite_overrides.jsonl:{lineno} id={rec.get('id')} "
                f"rewrite still names the canonical function {m.group()!r}"
            )

    overrides_ids: set[int] = set()
    for fname in (
        "function_mode_overrides.jsonl",
        "function_mode_overrides_round2.jsonl",
        "function_mode_overrides_round3.jsonl",
    ):
        path = os.path.join(HERE, fname)
        if not os.path.isfile(path):
            continue
        for line in _read(path).splitlines():
            line = line.strip()
            if not line:
                continue
            overrides_ids.add(int(json.loads(line)["id"]))

    for fname in ("function_mode_broken_ids.json", "function_mode_deleted_ids.json"):
        path = os.path.join(HERE, fname)
        if not os.path.isfile(path):
            continue
        skipped = set(json.loads(_read(path)))
        overlap = overrides_ids & skipped
        assert not overlap, (
            f"{fname} overlaps with function_mode_overrides[/round2/round3].jsonl on ids "
            f"{sorted(overlap)} — a question cannot both have an override and be skipped"
        )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
