#!/usr/bin/env python3
"""Author 8 standalone Colab drills for ResNet + CNN-module-pattern atoms.

Targets atoms used across ARENA chapter 0 part 2 (CNN/ResNet). Companion to
batch-3 (`author_cnn_deep_batch3.py`) — core conv mechanics — and batch-4
(`author_cnn_extras_batch4.py`) — affine/avgpool/block-group/freeze. This
batch covers the *full ResNet vocabulary*: pooling-as-reduce, BN running
stats EMA, the residual skip-add, 1×1 channel reshape, the ResNet stem,
register_buffer state, head-replace transfer, and state_dict load.

Atom layout (8 atoms × 1 exercise = 8 single-exercise notebooks):
  maxpool-reduce              — MaxPool2d == einops.reduce('max')
  batchnorm-running-stats     — running_mean/var EMA + train/eval switch
  residual-skip-add           — out = conv(x) + x + Identity vs 1x1 shortcut
  1x1-conv-channel-reshape    — Conv2d(1x1) == per-pixel Linear(IC→OC)
  resnet-stem                 — Conv(7,s=2,p=3) + BN + ReLU + MaxPool(3,s=2,p=1)
  register-buffer             — non-trainable state in state_dict
  replace-final-head          — transfer learning: swap model.fc
  state-dict-load             — load_state_dict + strict=False + _IncompatibleKeys

Constraints (Doughty ACE 2024 + Maier 2021):
  - One LO + one Bloom per exercise.
  - <= 2 KCs per exercise.
  - Solutions verify in `This-Directory-Only/backend/.venv/bin/python`
    (torch 2.12.0+cpu + einops 0.8.2).
  - Shape/algebra drills stay assertion-only; ResNet stem stays
    assertion-only (shape check is the load-bearing observation).
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _emit_standalone import emit_standalone

TOPIC = "prereqs_resnet_modules"

# ─────────────────────────────────────────────────────────────────────────────
# Recap snippets — one per atom.
# ─────────────────────────────────────────────────────────────────────────────

RECAP_MAXPOOL_REDUCE = (
    "## MaxPool2d == einops.reduce(max) — quick refresher\n"
    "\n"
    "`nn.MaxPool2d(p)` with non-overlapping windows is exactly an einops "
    "`reduce` with the `max` op:\n"
    "\n"
    "```\n"
    "y = einops.reduce(x, 'b c (h p1) (w p2) -> b c h w', 'max', p1=p, p2=p)\n"
    "```\n"
    "\n"
    "**Reading the einops string** (same as AvgPool — only the op differs):\n"
    "- `(h p1)` factors the H-axis into `h * p1` — `h` is the output spatial "
    "axis, `p1` is the pool-window axis being reduced.\n"
    "- `'max'` takes the maximum value across the dropped axes (vs `'mean'` "
    "for AvgPool).\n"
    "\n"
    "**Why MaxPool is the canonical CNN pool.** It introduces translation "
    "robustness — small shifts in the input don't change the max-of-window "
    "if the activating pixel stays inside the window. AlexNet, VGG, and "
    "ResNet's stem all use MaxPool right after the first conv.\n"
    "\n"
    "**Why ResNet uses Max in the stem but Avg at the head.** The stem's "
    "MaxPool selects salient activations early. The head's global AvgPool "
    "(after the last BlockGroup) averages across the whole feature map to "
    "produce one scalar per channel — that smoothing is what a classifier "
    "wants. Max would be too noisy for the final pool.\n"
    "\n"
    "**Compared to AvgPool.** Identical einops pattern; identical shape "
    "math. The op `'max'` vs `'mean'` is the ONLY difference. Same KC "
    "(pool-as-einops-reduce) — drilling Max separately reinforces that the "
    "axis-factoring trick is op-agnostic."
)

RECAP_BN_RUNNING_STATS = (
    "## BatchNorm running stats (EMA) — quick refresher\n"
    "\n"
    "BatchNorm has two distinct modes set by `model.train()` vs "
    "`model.eval()`:\n"
    "\n"
    "**Training mode** — normalize with THIS batch's statistics, then "
    "update a rolling exponential moving average (EMA):\n"
    "\n"
    "```\n"
    "batch_mean = x.mean(dim=(0, 2, 3))                       # per-channel mean\n"
    "batch_var_biased   = x.var(dim=(0, 2, 3), unbiased=False)# for the normalize step (/ N)\n"
    "batch_var_unbiased = x.var(dim=(0, 2, 3), unbiased=True) # for the EMA update    (/ (N-1))\n"
    "x_hat = (x - batch_mean[None, :, None, None]) / sqrt(batch_var_biased[None, :, None, None] + eps)\n"
    "running_mean = (1 - momentum) * running_mean + momentum * batch_mean\n"
    "running_var  = (1 - momentum) * running_var  + momentum * batch_var_unbiased   # Bessel-corrected\n"
    "```\n"
    "\n"
    "(The biased estimator gives the actual batch variance; the "
    "unbiased estimator gives a better estimate of the POPULATION "
    "variance, which is what `running_var` represents.)\n"
    "\n"
    "**Eval mode** — normalize with the FROZEN running stats (no batch "
    "lookup, no EMA update):\n"
    "\n"
    "```\n"
    "x_hat = (x - running_mean[None, :, None, None]) / sqrt(running_var[None, :, None, None] + eps)\n"
    "```\n"
    "\n"
    "**Why `momentum` is called momentum but acts like the OPPOSITE of "
    "Adam's momentum.** PyTorch's BN convention: `running = (1-m)*running "
    "+ m*batch`. So `momentum=0.1` (the default) means each batch "
    "contributes 10% of the new EMA value — a *short* memory. Closer to 0 "
    "is more inertia. Counter-intuitive but it's the API.\n"
    "\n"
    "**Why this matters for inference.** A model deployed in eval mode "
    "with bad running stats produces garbage outputs even with correct "
    "weights. The stats are part of the model's behavior — that's why "
    "they're saved in `state_dict` (as **buffers**, not parameters — see "
    "the `register-buffer` atom)."
)

RECAP_RESIDUAL_SKIP = (
    "## Residual skip-connection add — quick refresher\n"
    "\n"
    "A `ResidualBlock` adds its input back to its output:\n"
    "\n"
    "```\n"
    "out = self.conv_branch(x) + self.skip(x)        # the residual add\n"
    "```\n"
    "\n"
    "**Two cases for the skip branch:**\n"
    "\n"
    "1. **Same shape** — when `in_channels == out_channels` AND `stride == "
    "1`, the conv branch preserves shape. The skip is just the input:\n"
    "   ```\n"
    "   self.skip = nn.Identity()        # or just write x + self.conv(x)\n"
    "   ```\n"
    "\n"
    "2. **Different shape** — when channels change or `stride > 1`, the "
    "conv branch reshapes `(B, IC, H, W) → (B, OC, H', W')`. The skip "
    "branch needs a 1×1 projection to match:\n"
    "   ```\n"
    "   self.skip = nn.Conv2d(in_channels, out_channels,\n"
    "                         kernel_size=1, stride=first_stride)\n"
    "   ```\n"
    "   This is the 1×1 conv whose ONLY job is shape adjustment (see the "
    "`1x1-conv-channel-reshape` atom for the per-pixel-Linear "
    "interpretation).\n"
    "\n"
    "**Why the addition matters (vs concatenation).** Add preserves the "
    "channel count and keeps the gradient path FLAT: "
    "`∂out/∂x = ∂conv/∂x + 1`. That `+ 1` is the 'gradient highway' that "
    "lets ResNet train at hundreds of layers — gradients never vanish, "
    "they always have a direct route to every earlier layer.\n"
    "\n"
    "**Why ReLU comes AFTER the add (not before).** The full block is "
    "`ReLU(BN(conv(x)) + skip(x))`. Putting ReLU after the add keeps the "
    "skip clean (no nonlinearity along the highway) and lets the conv "
    "branch learn to OFFSET its skip contribution if it wants the output "
    "to be negative."
)

RECAP_1x1_CONV = (
    "## 1×1 Conv as per-pixel Linear — quick refresher\n"
    "\n"
    "`nn.Conv2d(IC, OC, kernel_size=1)` is exactly a **per-pixel linear** "
    "map from `IC` channels to `OC` channels:\n"
    "\n"
    "```\n"
    "y[b, oc, h, w] = sum_ic weight[oc, ic, 0, 0] * x[b, ic, h, w] + bias[oc]\n"
    "```\n"
    "\n"
    "There's no spatial mixing — each `(h, w)` position is processed "
    "independently. The op is identical to applying `nn.Linear(IC, OC)` "
    "after rearranging `(B, IC, H, W) → (B*H*W, IC)`, then rearranging "
    "back.\n"
    "\n"
    "**Three uses in ResNet-family models:**\n"
    "\n"
    "1. **Skip-branch projection** — match channel/stride between input "
    "and output of a residual block when they differ.\n"
    "2. **Bottleneck blocks** (ResNet-50+) — squeeze with `1×1, IC→IC/4`, "
    "do the expensive `3×3, IC/4→IC/4`, then expand with `1×1, IC/4→IC`. "
    "Three convs but cheaper than one big 3×3.\n"
    "3. **Channel reduction at the head** — collapse 2048 → 1000 with a "
    "single 1×1 conv instead of a flatten + Linear.\n"
    "\n"
    "**Shape preservation.** `kernel_size=1` with `padding=0` and "
    "`stride=1` preserves H and W exactly: `(B, IC, H, W) → (B, OC, H, "
    "W)`. With `stride=s`, it downsamples by `s` while reshaping "
    "channels — that's the form ResNet's skip branch uses when the conv "
    "branch has `stride=s`.\n"
    "\n"
    "**Parameter count vs full Linear.** `Conv2d(IC, OC, 1)` has `IC*OC + "
    "OC` params — exactly the same as `Linear(IC, OC)`. The 'conv' "
    "wrapping is just so the op accepts `(B, C, H, W)` directly without "
    "manual reshapes."
)

RECAP_RESNET_STEM = (
    "## ResNet stem block — quick refresher\n"
    "\n"
    "The 'stem' is the FIRST stage of every ResNet — the four-op sequence "
    "that turns a `(B, 3, 224, 224)` ImageNet image into a `(B, 64, 56, "
    "56)` feature map ready for the first BlockGroup:\n"
    "\n"
    "```\n"
    "nn.Sequential(\n"
    "    nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False),\n"
    "    nn.BatchNorm2d(64),\n"
    "    nn.ReLU(inplace=True),\n"
    "    nn.MaxPool2d(kernel_size=3, stride=2, padding=1),\n"
    ")\n"
    "```\n"
    "\n"
    "**Shape walkthrough (224 input):**\n"
    "- Input:           `(B, 3, 224, 224)`\n"
    "- After 7×7 s=2 p=3 conv: `(B, 64, 112, 112)`  → `(224 + 2*3 - 7) // 2 + 1 = 112`\n"
    "- After BN + ReLU: `(B, 64, 112, 112)` (no shape change)\n"
    "- After 3×3 s=2 p=1 MaxPool: `(B, 64, 56, 56)` → `(112 + 2*1 - 3) // 2 + 1 = 56`\n"
    "\n"
    "**Why this exact recipe.**\n"
    "- **7×7 conv with stride 2** — large receptive field early, halves "
    "spatial size cheaply. The wide kernel captures edge/blob features "
    "that small kernels need multiple layers to see.\n"
    "- **`bias=False`** — pointless to learn a bias right before BatchNorm "
    "(which subtracts the mean and learns its own bias `beta`). Saves "
    "64 params and a tiny amount of compute.\n"
    "- **BatchNorm + ReLU** — the canonical 'conv block' suffix. Same "
    "pattern repeats inside every ResidualBlock.\n"
    "- **MaxPool with stride 2** — second 2× spatial reduction. Combined "
    "with the conv stride, the stem downsamples by 4× in total (224 → "
    "56) before any BlockGroup runs.\n"
    "\n"
    "**Why subsequent BlockGroups don't need a 'stem'.** Each BlockGroup's "
    "FIRST ResidualBlock has `stride=2` (except group 0), which performs "
    "the per-group 2× downsample. The stem is special because it has to "
    "go from 3 channels → 64 in one shot, with a big enough kernel to "
    "see meaningful image structure."
)

RECAP_REGISTER_BUFFER = (
    "## `register_buffer` — quick refresher\n"
    "\n"
    "A **buffer** is non-trainable state that belongs to a Module — it's "
    "saved in `state_dict`, moved by `.to(device)`, but NOT updated by "
    "the optimizer. The idiom:\n"
    "\n"
    "```\n"
    "class MyBN(nn.Module):\n"
    "    def __init__(self, num_features):\n"
    "        super().__init__()\n"
    "        self.weight = nn.Parameter(t.ones(num_features))     # trainable\n"
    "        self.bias   = nn.Parameter(t.zeros(num_features))    # trainable\n"
    "        self.register_buffer('running_mean', t.zeros(num_features))\n"
    "        self.register_buffer('running_var',  t.ones(num_features))\n"
    "```\n"
    "\n"
    "**Buffer vs Parameter — what differs:**\n"
    "\n"
    "| | `nn.Parameter` | `register_buffer` |\n"
    "|--|--|--|\n"
    "| Appears in `.parameters()` | yes | NO |\n"
    "| Appears in `.buffers()` | no | yes |\n"
    "| Appears in `state_dict` | yes | yes |\n"
    "| Follows `.to(device)` | yes | yes |\n"
    "| `requires_grad` defaults | True | False (no grad) |\n"
    "| Updated by optimizer | yes | NO |\n"
    "\n"
    "**Why buffers exist.** Sometimes a Module needs to remember state "
    "that's NOT learned — BatchNorm's running mean/var, attention masks, "
    "positional-encoding tables, scaling constants. Marking them as "
    "buffers gets them saved/loaded/moved automatically without "
    "letting the optimizer touch them.\n"
    "\n"
    "**Critical distinction from plain `self.tensor = ...`.** A plain "
    "tensor attribute (`self.running_mean = t.zeros(C)`) does NOT appear "
    "in `state_dict`, does NOT follow `.to(device)`, and gets silently "
    "broken when the model is saved/restored. Always use "
    "`register_buffer` for non-trainable tensor state.\n"
    "\n"
    "**Access pattern.** After registration, you read/write via "
    "`self.running_mean` like any attribute — PyTorch installs a "
    "descriptor that does the right thing under the hood."
)

RECAP_REPLACE_HEAD = (
    "## Replace final head (transfer learning) — quick refresher\n"
    "\n"
    "The transfer-learning recipe: take a model pretrained on a big task "
    "(e.g. ImageNet, 1000 classes), and swap its final linear classifier "
    "for a new head matching your task:\n"
    "\n"
    "```\n"
    "import torchvision.models as M\n"
    "model = M.resnet18(weights='DEFAULT')\n"
    "in_features = model.fc.in_features        # 512 for resnet18\n"
    "model.fc = nn.Linear(in_features, num_classes)   # new head, new shape\n"
    "```\n"
    "\n"
    "**Why `model.fc.in_features` first.** Different pretrained backbones "
    "have different feature widths — ResNet-18/34 have 512, ResNet-50+ "
    "have 2048, ViT-B/16 has 768. Read the dim off the OLD head; the new "
    "head's `in_features` must match what the backbone produces.\n"
    "\n"
    "**Why a brand-new `nn.Linear` works.** Setting `model.fc = "
    "nn.Linear(...)` REPLACES the attribute on the module. PyTorch's "
    "`__setattr__` notices it's an `nn.Module` and registers it as a "
    "child — `parameters()`, `state_dict()`, and `.to(device)` all pick "
    "it up automatically.\n"
    "\n"
    "**New head defaults to trainable.** Brand-new `nn.Linear` modules "
    "have `requires_grad=True` on their weight + bias. So if you've "
    "already frozen the backbone with `requires_grad = False`, the "
    "swapped head naturally becomes the ONLY trainable submodule. (See "
    "the `freeze-requires-grad` atom for the freeze step.)\n"
    "\n"
    "**Common pitfall — different head names.** Not every torchvision "
    "model calls its head `fc`. Common variants: `model.classifier` "
    "(VGG, AlexNet, MobileNet), `model.heads.head` (ViT). Check the "
    "model's `repr()` first or inspect `list(model.named_children())[-1]` "
    "to find the right attribute name."
)

RECAP_STATE_DICT_LOAD = (
    "## `load_state_dict` + `strict=False` — quick refresher\n"
    "\n"
    "A `state_dict` is an ordered dict mapping parameter / buffer names "
    "to tensors. Loading it onto a model:\n"
    "\n"
    "```\n"
    "result = model.load_state_dict(t.load('checkpoint.pt'), strict=True)\n"
    "```\n"
    "\n"
    "**`strict=True` (the default)** — every key in the checkpoint must "
    "exist on the model AND vice versa, with shape-compatible tensors. "
    "Any mismatch raises `RuntimeError`.\n"
    "\n"
    "**`strict=False`** — load whatever matches, return an "
    "`_IncompatibleKeys(missing_keys, unexpected_keys)` named tuple "
    "listing the discrepancies. Use this when:\n"
    "- You've swapped the head — old `fc.weight/bias` becomes "
    "**unexpected**; new `fc.weight/bias` becomes **missing**.\n"
    "- You're loading a smaller checkpoint into a bigger model (some "
    "layers stay at init).\n"
    "- You're cross-loading between subtly-different architectures.\n"
    "\n"
    "**The return value.**\n"
    "```\n"
    "result = model.load_state_dict(ckpt, strict=False)\n"
    "print(result.missing_keys)     # keys model has, ckpt didn't provide\n"
    "print(result.unexpected_keys)  # keys ckpt has, model doesn't want\n"
    "```\n"
    "\n"
    "**Shape mismatches are NOT silently fixed by `strict=False`.** If a "
    "key exists in both with INCOMPATIBLE shapes, it still raises "
    "(though as of recent PyTorch versions, this is surfaced via "
    "`assign=False` mode warnings, not an immediate hard error in all "
    "code paths). The safe pattern is: pop the mismatching keys from "
    "the state_dict BEFORE calling `load_state_dict`.\n"
    "\n"
    "**Why this is the transfer-learning workflow.** "
    "Pretrained-checkpoint + swapped-head means: missing = "
    "`['fc.weight', 'fc.bias']` (head was replaced AFTER load, or load "
    "skipped them), unexpected = same names from the old 1000-class "
    "head. `strict=False` says 'I know about this, move on'."
)


# ─────────────────────────────────────────────────────────────────────────────
# Exercise specs.
# ─────────────────────────────────────────────────────────────────────────────

SPECS = [
    # ═══════════════════════════════════════════════════════════════════════
    # maxpool-reduce
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "maxpool-reduce",
        "subtopic": "CNN: MaxPool as reduce",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_MAXPOOL_REDUCE,
        "exercise_index": 1,
        "exercise_title": "build MaxPool2d via einops.reduce",
        "slug": "build-maxpool2d-via-einops-reduce",
        "bloom_level": "Apply",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["maxpool", "einops-reduce", "translation-invariance", "resnet-stem"],
        "kcs": ["maxpool-as-reduce-max", "pool-axis-factor-pattern"],
        "lo": (
            "Apply `einops.reduce('max')` with axis-factoring to reproduce "
            "`nn.MaxPool2d` with non-overlapping windows, and verify "
            "against `F.max_pool2d`."
        ),
        "prompt_body": (
            "Implement `ex1_maxpool_via_reduce(x, p)`. Given input "
            "`x: (B, C, H, W)` and pool size `p` (assume `H` and `W` are "
            "divisible by `p`), return a `(B, C, H // p, W // p)` tensor "
            "whose entries are the **max** of each non-overlapping "
            "`p × p` window of `x`.\n\n"
            "**Use einops.reduce with axis factoring.** The pattern is:\n\n"
            "```\n"
            "einops.reduce(x, 'b c (h p1) (w p2) -> b c h w', 'max', p1=p, p2=p)\n"
            "```\n\n"
            "**Read it letter-by-letter** (same axis-factor pattern as the "
            "avgpool-reduce drill — only the reducer differs):\n"
            "- `(h p1)` factors the input H-axis into `h * p1`.\n"
            "- `'max'` takes the max across the dropped `p1, p2` axes.\n"
            "- Pass `p1=p, p2=p` so einops knows the factor sizes.\n\n"
            "**Boundary handling.** This drill assumes `H % p == 0` and "
            "`W % p == 0`. Real `nn.MaxPool2d` can also handle stride != "
            "kernel and padding — out of scope here.\n\n"
            "The test compares your output to `F.max_pool2d(x, kernel_size=p)` "
            "to fp tolerance."
        ),
        "stub": (
            "def ex1_maxpool_via_reduce(x: Tensor, p: int) -> Tensor:\n"
            '    """Non-overlapping MaxPool2d via einops.reduce max."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "from torch.nn import functional as F\n"
            "\n"
            "rng = t.Generator().manual_seed(0)\n"
            "\n"
            "# Hand-checkable case.\n"
            "x = t.tensor([\n"
            "    [[[1.0, 2.0, 3.0, 4.0],\n"
            "      [5.0, 6.0, 7.0, 8.0],\n"
            "      [9.0, 1.0, 2.0, 3.0],\n"
            "      [4.0, 5.0, 6.0, 7.0]]]\n"
            "])  # shape (1, 1, 4, 4)\n"
            "y = ex1_maxpool_via_reduce(x, p=2)\n"
            "assert y.shape == (1, 1, 2, 2), f'expected (1,1,2,2), got {tuple(y.shape)}'\n"
            "# Top-left 2x2 window: [[1,2],[5,6]] → max 6.\n"
            "# Top-right 2x2:       [[3,4],[7,8]] → max 8.\n"
            "# Bot-left 2x2:        [[9,1],[4,5]] → max 9.\n"
            "# Bot-right 2x2:       [[2,3],[6,7]] → max 7.\n"
            "expected = t.tensor([[[[6.0, 8.0],\n"
            "                       [9.0, 7.0]]]])\n"
            "assert t.allclose(y, expected), f'value mismatch:\\n{y}\\nvs\\n{expected}'\n"
            "\n"
            "# Cross-check against F.max_pool2d on random data, various sizes.\n"
            "for B, C, H, W, p in [(2, 3, 8, 8, 2), (1, 4, 16, 16, 4), (3, 2, 12, 6, 2), (1, 1, 32, 32, 8)]:\n"
            "    xr = t.randn(B, C, H, W, generator=rng)\n"
            "    yr = ex1_maxpool_via_reduce(xr, p)\n"
            "    yref = F.max_pool2d(xr, kernel_size=p)\n"
            "    assert yr.shape == yref.shape\n"
            "    assert t.allclose(yr, yref, atol=1e-5), (\n"
            "        f'mismatch for shape ({B},{C},{H},{W}) p={p}'\n"
            "    )\n"
            "\n"
            "# p == 1 → identity (each window is a single pixel; max of 1 pixel = itself).\n"
            "x_id = t.randn(1, 2, 4, 4, generator=rng)\n"
            "assert t.allclose(ex1_maxpool_via_reduce(x_id, 1), x_id, atol=1e-7)\n"
            "\n"
            "# Constant input → constant output (max of constants = constant).\n"
            "x_c = t.full((2, 3, 6, 6), -1.5)\n"
            "y_c = ex1_maxpool_via_reduce(x_c, 3)\n"
            "assert y_c.shape == (2, 3, 2, 2)\n"
            "assert t.allclose(y_c, t.full((2, 3, 2, 2), -1.5), atol=1e-6)\n"
            "\n"
            "# Sanity: max picks the LARGEST value (not the smallest — would be a common bug).\n"
            "x_sign = t.tensor([[[[-5.0, -3.0],\n"
            "                     [-2.0, -1.0]]]])\n"
            "y_sign = ex1_maxpool_via_reduce(x_sign, p=2)\n"
            "assert y_sign.item() == -1.0, f'max of negatives must pick -1, got {y_sign.item()}'"
        ),
        "solution_body": (
            "def ex1_maxpool_via_reduce(x: Tensor, p: int) -> Tensor:\n"
            "    return einops.reduce(\n"
            "        x,\n"
            "        'b c (h p1) (w p2) -> b c h w',\n"
            "        'max',\n"
            "        p1=p, p2=p,\n"
            "    )"
        ),
        "solution_notes": (
            "**Same einops pattern as AvgPool, different reducer.** The "
            "axis-factor trick `(h p1)` works for ANY commutative-monoid "
            "reduction — `'mean'`, `'max'`, `'min'`, `'sum'`, `'prod'`. "
            "Recognizing pool-as-reduce gives you N-dim pooling with "
            "arbitrary reducers for free.\n\n"
            "**Why MaxPool is in the ResNet stem.** After the 7×7 stride-2 "
            "conv, the stem applies `MaxPool2d(3, stride=2, padding=1)` — "
            "a 3×3 OVERLAPPING max-pool (stride < kernel). This drill is "
            "the non-overlapping `kernel == stride` case; the stem's "
            "overlapping variant uses the same op, different einops "
            "doesn't directly handle (overlap needs unfold + reduce).\n\n"
            "**Backward-pass subtlety.** Unlike AvgPool (every input "
            "contributes 1/p² to the output gradient), MaxPool routes the "
            "ENTIRE output gradient to the SINGLE max-position input — a "
            "sparse, switch-like backward. `einops.reduce(..., 'max')` "
            "handles this correctly via PyTorch's autograd, but if you "
            "ever roll your own pool, remember the sparsity."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # batchnorm-running-stats
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "batchnorm-running-stats",
        "subtopic": "CNN: BatchNorm running stats",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_BN_RUNNING_STATS,
        "exercise_index": 1,
        "exercise_title": "EMA-update running_mean and running_var in train mode",
        "slug": "ema-update-running-mean-and-running-var-in-train-mode",
        "bloom_level": "Apply",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["batchnorm", "running-stats", "ema", "momentum"],
        "kcs": ["bn-running-stats-ema-update", "bn-per-channel-batch-stats"],
        "lo": (
            "Apply BatchNorm's training-mode EMA update — compute "
            "per-channel batch_mean / batch_var, then blend them into "
            "running_mean / running_var via `running = (1-m)*running + "
            "m*batch`."
        ),
        "prompt_body": (
            "Implement `ex1_bn_ema_update(x, running_mean, running_var, "
            "momentum)`. Given:\n\n"
            "- `x`: input batch of shape `(B, C, H, W)`.\n"
            "- `running_mean`, `running_var`: current EMA stats of shape "
            "`(C,)`.\n"
            "- `momentum`: float in `[0, 1]`. PyTorch convention: each "
            "batch contributes `momentum` to the new EMA value.\n\n"
            "Return a tuple `(new_running_mean, new_running_var)` "
            "computed as follows:\n\n"
            "1. **Per-channel batch stats** — reduce over the (B, H, W) "
            "axes, leave the channel axis intact:\n"
            "   ```\n"
            "   batch_mean         = x.mean(dim=(0, 2, 3))\n"
            "   batch_var_unbiased = x.var(dim=(0, 2, 3), unbiased=True)\n"
            "   ```\n"
            "   **Important PyTorch quirk:** `BatchNorm2d` uses the "
            "BIASED variance (`unbiased=False`, `/N`) for the in-batch "
            "normalize step but the UNBIASED variance (`unbiased=True`, "
            "`/(N-1)`) for the value it EMA-blends into `running_var`. "
            "This drill is about the EMA update, so use "
            "`unbiased=True` — the running stat is meant as a "
            "population-variance estimate.\n\n"
            "2. **EMA blend** — each stat is updated as:\n"
            "   ```\n"
            "   new_running = (1 - momentum) * running + momentum * batch\n"
            "   ```\n\n"
            "Don't update `x` itself or do any normalization — this drill "
            "is specifically about the EMA arithmetic, isolated from "
            "the normalize step.\n\n"
            "**Edge case.** `momentum == 0` → running stats unchanged. "
            "`momentum == 1` → running stats replaced entirely by this "
            "batch."
        ),
        "stub": (
            "def ex1_bn_ema_update(\n"
            "    x: Tensor,\n"
            "    running_mean: Tensor,\n"
            "    running_var: Tensor,\n"
            "    momentum: float,\n"
            ") -> tuple[Tensor, Tensor]:\n"
            '    """Compute per-channel batch stats and EMA-blend them into running stats."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "rng = t.Generator().manual_seed(0)\n"
            "\n"
            "# Hand-checkable case: constant input → batch_mean=const, batch_var=0.\n"
            "x = t.full((2, 3, 4, 4), 5.0)\n"
            "rm = t.zeros(3)\n"
            "rv = t.ones(3)\n"
            "new_rm, new_rv = ex1_bn_ema_update(x, rm, rv, momentum=0.1)\n"
            "# new_rm = 0.9 * 0 + 0.1 * 5 = 0.5\n"
            "# new_rv = 0.9 * 1 + 0.1 * 0 = 0.9\n"
            "assert t.allclose(new_rm, t.full((3,), 0.5), atol=1e-6), (\n"
            "    f'expected new_rm=[0.5,0.5,0.5], got {new_rm.tolist()}'\n"
            ")\n"
            "assert t.allclose(new_rv, t.full((3,), 0.9), atol=1e-6), (\n"
            "    f'expected new_rv=[0.9,0.9,0.9], got {new_rv.tolist()}'\n"
            ")\n"
            "# Function must NOT mutate the inputs in-place.\n"
            "assert t.allclose(rm, t.zeros(3)), 'must not mutate running_mean in-place'\n"
            "assert t.allclose(rv, t.ones(3)),  'must not mutate running_var in-place'\n"
            "\n"
            "# momentum=0 → running stats unchanged.\n"
            "x2 = t.randn(4, 5, 6, 6, generator=rng)\n"
            "rm2 = t.randn(5, generator=rng)\n"
            "rv2 = t.rand(5,  generator=rng) + 0.1\n"
            "out_rm, out_rv = ex1_bn_ema_update(x2, rm2, rv2, momentum=0.0)\n"
            "assert t.allclose(out_rm, rm2, atol=1e-6), 'momentum=0 must leave running_mean unchanged'\n"
            "assert t.allclose(out_rv, rv2, atol=1e-6), 'momentum=0 must leave running_var unchanged'\n"
            "\n"
            "# momentum=1 → running stats fully replaced by this batch's stats.\n"
            "# Match PyTorch BN: running_var uses the UNBIASED estimator.\n"
            "out_rm1, out_rv1 = ex1_bn_ema_update(x2, rm2, rv2, momentum=1.0)\n"
            "batch_mean         = x2.mean(dim=(0, 2, 3))\n"
            "batch_var_unbiased = x2.var(dim=(0, 2, 3), unbiased=True)\n"
            "assert t.allclose(out_rm1, batch_mean,         atol=1e-5)\n"
            "assert t.allclose(out_rv1, batch_var_unbiased, atol=1e-5)\n"
            "\n"
            "# Cross-check against torch.nn.BatchNorm2d running stats after one training step.\n"
            "import torch.nn as nn\n"
            "B, C, H, W = 4, 6, 8, 8\n"
            "x3 = t.randn(B, C, H, W, generator=rng)\n"
            "bn = nn.BatchNorm2d(C, momentum=0.1, affine=False, track_running_stats=True)\n"
            "# Snapshot initial running stats (zeros and ones by default).\n"
            "rm_init = bn.running_mean.detach().clone()\n"
            "rv_init = bn.running_var.detach().clone()\n"
            "bn.train()\n"
            "_ = bn(x3)        # this updates bn.running_mean / running_var\n"
            "ours_rm, ours_rv = ex1_bn_ema_update(x3, rm_init, rv_init, momentum=0.1)\n"
            "assert t.allclose(ours_rm, bn.running_mean, atol=1e-5), (\n"
            "    f'ours rm {ours_rm.tolist()} vs torch {bn.running_mean.tolist()}'\n"
            ")\n"
            "assert t.allclose(ours_rv, bn.running_var, atol=1e-5), (\n"
            "    f'ours rv {ours_rv.tolist()} vs torch {bn.running_var.tolist()}'\n"
            ")\n"
            "\n"
            "# Per-channel correctness: heterogeneous channels.\n"
            "x4 = t.stack([t.full((2, 4, 4), c * 1.0) for c in range(5)], dim=1)  # (2, 5, 4, 4)\n"
            "rm4 = t.zeros(5)\n"
            "rv4 = t.ones(5)\n"
            "new_rm4, _ = ex1_bn_ema_update(x4, rm4, rv4, momentum=0.5)\n"
            "# channel c is constant c → batch_mean[c] = c. EMA(0, c, m=0.5) = 0.5 * c.\n"
            "assert t.allclose(new_rm4, t.tensor([0.0, 0.5, 1.0, 1.5, 2.0]), atol=1e-6), (\n"
            "    f'per-channel mismatch: {new_rm4.tolist()}'\n"
            ")"
        ),
        "solution_body": (
            "def ex1_bn_ema_update(\n"
            "    x: Tensor,\n"
            "    running_mean: Tensor,\n"
            "    running_var: Tensor,\n"
            "    momentum: float,\n"
            ") -> tuple[Tensor, Tensor]:\n"
            "    batch_mean = x.mean(dim=(0, 2, 3))\n"
            "    # NOTE: PyTorch uses BIASED var (/ N) for the normalize step\n"
            "    # but UNBIASED var (/ (N-1)) for the running_var EMA.\n"
            "    batch_var_unbiased = x.var(dim=(0, 2, 3), unbiased=True)\n"
            "    new_running_mean = (1 - momentum) * running_mean + momentum * batch_mean\n"
            "    new_running_var  = (1 - momentum) * running_var  + momentum * batch_var_unbiased\n"
            "    return new_running_mean, new_running_var"
        ),
        "solution_notes": (
            "**Why `unbiased=True` for the EMA (but biased for normalize).** "
            "`BatchNorm2d` is sneaky here: it uses the BIASED variance "
            "estimator (sum-sq-deviations / N) for the in-batch "
            "normalize step `x_hat = (x - mean) / sqrt(var + eps)`, but "
            "the UNBIASED estimator (/ (N-1)) for the value it blends "
            "into `running_var` via EMA. The reason: `running_var` is "
            "what gets used at inference time as an estimate of the "
            "POPULATION variance, and the unbiased estimator is the "
            "correct one for that. Passing `unbiased=False` here would "
            "silently disagree with PyTorch's reference by a "
            "`N/(N-1)` Bessel-correction factor (a few parts per "
            "thousand for typical batch×spatial sizes).\n\n"
            "**Why we don't update in place.** Returning fresh tensors "
            "keeps the drill pure-functional and lets the test confirm "
            "the inputs weren't clobbered. Real `BatchNorm2d` updates "
            "in-place via `.copy_()` on the registered buffers — the "
            "side-effect channel.\n\n"
            "**Why the EMA goes UNUSED at inference.** In `model.eval()` "
            "mode, BatchNorm normalizes with `running_mean` / "
            "`running_var` and does NOT call `mean()` / `var()` on the "
            "incoming batch. So inference batches don't contribute to "
            "the EMA — only training-mode forward passes do.\n\n"
            "**Why this is its own atom (separate from `bn-affine-"
            "params`).** Two different conditional behaviors get fused "
            "into BatchNorm: the *normalize* stage (which axes, biased "
            "or not, running or batch stats) and the *affine* stage "
            "(gamma * x_hat + beta). Drilling them in isolation lets you "
            "compose any norm variant — RMSNorm differs in normalize "
            "stage; LayerNorm differs in normalize stage; the affine "
            "stage is shared."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # residual-skip-add
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "residual-skip-add",
        "subtopic": "CNN: Residual skip-connection add",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_RESIDUAL_SKIP,
        "exercise_index": 1,
        "exercise_title": "build a toy ResidualBlock with conditional shortcut",
        "slug": "build-a-toy-residualblock-with-conditional-shortcut",
        "bloom_level": "Apply",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["residual", "skip", "identity", "1x1-shortcut", "resnet"],
        "kcs": ["residual-skip-add-pattern", "conditional-1x1-shortcut"],
        "lo": (
            "Apply the residual-block construction pattern: conv branch + "
            "skip branch summed; skip is `nn.Identity` when shapes match, "
            "else a `1×1 Conv2d` projection."
        ),
        "prompt_body": (
            "Build a toy `ResidualBlock` module. The block has TWO parallel "
            "branches that get ADDED to form the output:\n\n"
            "- **conv branch**: `nn.Conv2d(in_channels, out_channels, "
            "kernel_size=3, stride=first_stride, padding=1)` — the "
            "shape-changer.\n"
            "- **skip branch**: depends on whether shapes match:\n"
            "  - If `in_channels == out_channels` AND `first_stride == 1` "
            "→ `nn.Identity()`.\n"
            "  - Otherwise → `nn.Conv2d(in_channels, out_channels, "
            "kernel_size=1, stride=first_stride, padding=0)`.\n\n"
            "Forward: `out = self.conv(x) + self.skip(x)`. No ReLU, no BN "
            "in this drill — we're isolating the skip-add pattern.\n\n"
            "Skeleton:\n\n"
            "```\n"
            "class ResidualBlock(nn.Module):\n"
            "    def __init__(self, in_channels, out_channels, first_stride=1):\n"
            "        super().__init__()\n"
            "        # 1. self.conv = nn.Conv2d(...)\n"
            "        # 2. self.skip = nn.Identity() or nn.Conv2d(1x1, stride=first_stride)\n"
            "        ...\n"
            "    def forward(self, x):\n"
            "        return self.conv(x) + self.skip(x)\n"
            "```\n\n"
            "**What the test checks.**\n"
            "- Identity-shaped block (in=out, stride=1) has `self.skip` of "
            "type `nn.Identity`.\n"
            "- Shape-changing block (in≠out OR stride>1) has `self.skip` "
            "of type `nn.Conv2d` with `kernel_size=(1,1)`.\n"
            "- Forward pass produces the expected `(B, out_channels, "
            "H_out, W_out)` shape.\n"
            "- Forward output equals `conv(x) + skip(x)` element-wise.\n"
            "- Gradient flows back through BOTH branches (the gradient "
            "highway property)."
        ),
        "stub": (
            "import torch.nn as nn\n"
            "\n"
            "class ResidualBlock(nn.Module):\n"
            "    def __init__(self, in_channels: int, out_channels: int, first_stride: int = 1):\n"
            "        super().__init__()\n"
            "        raise NotImplementedError()\n"
            "    def forward(self, x: Tensor) -> Tensor:\n"
            "        raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "# Identity-shaped: in==out, stride=1 → skip must be nn.Identity.\n"
            "block_id = ResidualBlock(64, 64, first_stride=1)\n"
            "assert isinstance(block_id.skip, nn.Identity), (\n"
            "    f'identity-shaped skip should be nn.Identity, got {type(block_id.skip).__name__}'\n"
            ")\n"
            "# Forward: shape preserved.\n"
            "x = t.randn(2, 64, 8, 8)\n"
            "y = block_id(x)\n"
            "assert y.shape == (2, 64, 8, 8), f'identity block shape wrong: {tuple(y.shape)}'\n"
            "# Output must equal conv(x) + x.\n"
            "expected_id = block_id.conv(x) + x\n"
            "assert t.allclose(y, expected_id, atol=1e-5), 'identity block output != conv(x) + x'\n"
            "\n"
            "# Channel change only: in=32, out=64, stride=1 → skip must be 1x1 Conv2d.\n"
            "block_ch = ResidualBlock(32, 64, first_stride=1)\n"
            "assert isinstance(block_ch.skip, nn.Conv2d), (\n"
            "    f'channel-change skip should be nn.Conv2d, got {type(block_ch.skip).__name__}'\n"
            ")\n"
            "assert block_ch.skip.kernel_size == (1, 1), (\n"
            "    f'shortcut must be 1x1, got kernel_size={block_ch.skip.kernel_size}'\n"
            ")\n"
            "assert block_ch.skip.stride == (1, 1), 'stride=1 case should have skip stride (1,1)'\n"
            "x2 = t.randn(1, 32, 4, 4)\n"
            "y2 = block_ch(x2)\n"
            "assert y2.shape == (1, 64, 4, 4)\n"
            "\n"
            "# Stride change: in=64, out=128, stride=2 → skip is 1x1 Conv2d stride=2.\n"
            "block_str = ResidualBlock(64, 128, first_stride=2)\n"
            "assert isinstance(block_str.skip, nn.Conv2d)\n"
            "assert block_str.skip.kernel_size == (1, 1)\n"
            "assert block_str.skip.stride == (2, 2), (\n"
            "    f'first_stride=2 case should have skip stride (2,2), got {block_str.skip.stride}'\n"
            ")\n"
            "x3 = t.randn(1, 64, 16, 16)\n"
            "y3 = block_str(x3)\n"
            "assert y3.shape == (1, 128, 8, 8), f'stride-2 block shape wrong: {tuple(y3.shape)}'\n"
            "# Cross-check: y == conv(x) + skip(x) element-wise.\n"
            "expected_str = block_str.conv(x3) + block_str.skip(x3)\n"
            "assert t.allclose(y3, expected_str, atol=1e-5), 'stride-change output != conv + skip'\n"
            "\n"
            "# Gradient highway: gradient must flow through the skip even if conv weights are zeroed.\n"
            "block_grad = ResidualBlock(8, 8, first_stride=1)\n"
            "with t.no_grad():\n"
            "    block_grad.conv.weight.zero_()\n"
            "    block_grad.conv.bias.zero_()\n"
            "x4 = t.randn(1, 8, 4, 4, requires_grad=True)\n"
            "out = block_grad(x4)\n"
            "# With conv zeroed, output should equal x exactly (identity skip + zero conv).\n"
            "assert t.allclose(out, x4, atol=1e-6), 'conv=0 + identity skip should produce x exactly'\n"
            "out.sum().backward()\n"
            "# x4.grad must be non-zero — gradient took the skip route.\n"
            "assert x4.grad is not None and t.all(x4.grad != 0), (\n"
            "    'gradient highway: skip path must propagate grad even when conv is zeroed'\n"
            ")"
        ),
        "solution_body": (
            "class ResidualBlock(nn.Module):\n"
            "    def __init__(self, in_channels: int, out_channels: int, first_stride: int = 1):\n"
            "        super().__init__()\n"
            "        self.conv = nn.Conv2d(\n"
            "            in_channels, out_channels,\n"
            "            kernel_size=3, stride=first_stride, padding=1,\n"
            "        )\n"
            "        if in_channels == out_channels and first_stride == 1:\n"
            "            self.skip = nn.Identity()\n"
            "        else:\n"
            "            self.skip = nn.Conv2d(\n"
            "                in_channels, out_channels,\n"
            "                kernel_size=1, stride=first_stride, padding=0,\n"
            "            )\n"
            "\n"
            "    def forward(self, x: Tensor) -> Tensor:\n"
            "        return self.conv(x) + self.skip(x)"
        ),
        "solution_notes": (
            "**Why `nn.Identity` and not just write `x + self.conv(x)`.** "
            "Using `nn.Identity` makes the skip branch a NAMED submodule "
            "that shows up in `repr(block)`, `state_dict`, and `named_"
            "modules()`. That uniform structure is what lets ResNet's "
            "constructor wire BlockGroups without branching on the "
            "in==out case — every block has a `.skip` attribute, just "
            "different types.\n\n"
            "**Why the 1×1 conv on the skip when shapes differ.** Two "
            "tensors of different shape can't be added — you need a "
            "projection. The 1×1 conv is the cheapest possible "
            "projection: O(IC*OC) params per pixel, no spatial mixing. "
            "See the `1x1-conv-channel-reshape` atom for the per-pixel-"
            "Linear interpretation.\n\n"
            "**Why the gradient highway works.** "
            "`∂(conv(x) + skip(x))/∂x = ∂conv/∂x + ∂skip/∂x`. For "
            "`skip = Identity`, that second term is just `1`. So even "
            "if `∂conv/∂x` is zero or tiny (dead channels, saturated "
            "ReLUs deeper in the conv branch), the gradient w.r.t. x "
            "has a guaranteed +1 floor — vanishing gradients become "
            "impossible. This is the single architectural reason 50+ "
            "layer CNNs trained at all in 2015.\n\n"
            "**In real ResNet** the conv branch is `BN(Conv) → ReLU → "
            "BN(Conv)` and there's a ReLU after the add. Adding those "
            "layers is `module-composition` work — not the SKIP-ADD "
            "skill this drill exercises."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # 1x1-conv-channel-reshape
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "1x1-conv-channel-reshape",
        "subtopic": "CNN: 1x1 conv channel-reshape",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_1x1_CONV,
        "exercise_index": 1,
        "exercise_title": "prove 1x1 Conv2d equals per-pixel Linear",
        "slug": "prove-1x1-conv2d-equals-per-pixel-linear",
        "bloom_level": "Analyze",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["1x1-conv", "per-pixel-linear", "channel-projection", "resnet-bottleneck"],
        "kcs": ["1x1-conv-equals-per-pixel-linear", "1x1-conv-shape-preservation"],
        "lo": (
            "Analyze the equivalence between `nn.Conv2d(IC, OC, "
            "kernel_size=1)` and `nn.Linear(IC, OC)` applied per-pixel by "
            "constructing matching weights and comparing outputs."
        ),
        "prompt_body": (
            "Implement `ex1_one_by_one_via_linear(x, conv)`. Given:\n\n"
            "- `x`: input tensor of shape `(B, IC, H, W)`.\n"
            "- `conv`: an `nn.Conv2d(IC, OC, kernel_size=1)` module "
            "(already constructed by the test harness).\n\n"
            "Return the result of applying a per-pixel `nn.Linear(IC, OC)` "
            "with the SAME weights as `conv` and producing a tensor of "
            "shape `(B, OC, H, W)`. Algorithm:\n\n"
            "1. Build `linear = nn.Linear(IC, OC)`.\n"
            "2. **Copy the conv weights into the linear's weight.** The "
            "conv's `weight` has shape `(OC, IC, 1, 1)`; `nn.Linear.weight` "
            "has shape `(OC, IC)`. The map is:\n"
            "   ```\n"
            "   linear.weight.data = conv.weight.data.view(OC, IC)\n"
            "   linear.bias.data   = conv.bias.data\n"
            "   ```\n"
            "   Use `.data` so the assignment doesn't track gradients "
            "(we're just copying initial weights for comparison).\n\n"
            "3. Rearrange `x` so each pixel is a row of features:\n"
            "   ```\n"
            "   x_flat = einops.rearrange(x, 'b c h w -> (b h w) c')   # (B*H*W, IC)\n"
            "   ```\n\n"
            "4. Apply the linear: `y_flat = linear(x_flat)`  → `(B*H*W, OC)`.\n\n"
            "5. Rearrange back to image shape:\n"
            "   ```\n"
            "   y = einops.rearrange(y_flat, '(b h w) c -> b c h w', b=B, h=H, w=W)\n"
            "   ```\n\n"
            "Return `y`. The test compares your output to `conv(x)` to fp "
            "tolerance — they must be identical (it's literally the same "
            "computation, just written differently).\n\n"
            "**Why this matters.** The two interpretations of 1×1 conv are "
            "equivalent — there's no special spatial trick. That's the "
            "atomic insight the drill is locking in."
        ),
        "stub": (
            "def ex1_one_by_one_via_linear(x: Tensor, conv) -> Tensor:\n"
            '    """Apply a 1x1 Conv2d via per-pixel nn.Linear with matched weights."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "rng = t.Generator().manual_seed(0)\n"
            "\n"
            "# Basic case: small channels.\n"
            "IC, OC, B, H, W = 3, 5, 2, 4, 6\n"
            "conv = nn.Conv2d(IC, OC, kernel_size=1)\n"
            "x = t.randn(B, IC, H, W, generator=rng)\n"
            "y_ours = ex1_one_by_one_via_linear(x, conv)\n"
            "y_ref  = conv(x)\n"
            "assert y_ours.shape == (B, OC, H, W), f'shape wrong: {tuple(y_ours.shape)}'\n"
            "assert y_ours.shape == y_ref.shape\n"
            "assert t.allclose(y_ours, y_ref, atol=1e-5), (\n"
            "    f'1x1-conv vs per-pixel-linear mismatch (max diff = {(y_ours - y_ref).abs().max().item()})'\n"
            ")\n"
            "\n"
            "# Bottleneck-style: 256 -> 64 squeeze.\n"
            "conv_b = nn.Conv2d(256, 64, kernel_size=1)\n"
            "x_b = t.randn(1, 256, 7, 7, generator=rng)\n"
            "y_b = ex1_one_by_one_via_linear(x_b, conv_b)\n"
            "assert y_b.shape == (1, 64, 7, 7), f'bottleneck shape wrong: {tuple(y_b.shape)}'\n"
            "assert t.allclose(y_b, conv_b(x_b), atol=1e-4)\n"
            "\n"
            "# Channel-expand case (decoder pattern): 32 -> 128.\n"
            "conv_e = nn.Conv2d(32, 128, kernel_size=1)\n"
            "x_e = t.randn(2, 32, 14, 14, generator=rng)\n"
            "y_e = ex1_one_by_one_via_linear(x_e, conv_e)\n"
            "assert y_e.shape == (2, 128, 14, 14)\n"
            "assert t.allclose(y_e, conv_e(x_e), atol=1e-4)\n"
            "\n"
            "# 1x1 case (single pixel): degenerate, must still work.\n"
            "conv_s = nn.Conv2d(4, 2, kernel_size=1)\n"
            "x_s = t.randn(3, 4, 1, 1, generator=rng)\n"
            "y_s = ex1_one_by_one_via_linear(x_s, conv_s)\n"
            "assert y_s.shape == (3, 2, 1, 1)\n"
            "assert t.allclose(y_s, conv_s(x_s), atol=1e-5)\n"
            "\n"
            "# IC == OC case (identity-shape channel projection — used in ResNet skip when only stride differs).\n"
            "conv_eq = nn.Conv2d(8, 8, kernel_size=1)\n"
            "x_eq = t.randn(1, 8, 5, 5, generator=rng)\n"
            "y_eq = ex1_one_by_one_via_linear(x_eq, conv_eq)\n"
            "assert y_eq.shape == (1, 8, 5, 5)\n"
            "assert t.allclose(y_eq, conv_eq(x_eq), atol=1e-5)"
        ),
        "solution_body": (
            "def ex1_one_by_one_via_linear(x: Tensor, conv) -> Tensor:\n"
            "    import torch.nn as nn\n"
            "    OC, IC, _, _ = conv.weight.shape\n"
            "    B, _, H, W = x.shape\n"
            "    linear = nn.Linear(IC, OC)\n"
            "    linear.weight.data = conv.weight.data.view(OC, IC).clone()\n"
            "    linear.bias.data   = conv.bias.data.clone()\n"
            "    x_flat = einops.rearrange(x, 'b c h w -> (b h w) c')\n"
            "    y_flat = linear(x_flat)\n"
            "    return einops.rearrange(y_flat, '(b h w) c -> b c h w', b=B, h=H, w=W)"
        ),
        "solution_notes": (
            "**Why the shapes line up.** Conv2d weight is `(OC, IC, K, "
            "K)`. For `K=1`, that's `(OC, IC, 1, 1)` — the two trailing "
            "size-1 axes hold zero information. `view(OC, IC)` collapses "
            "them. `nn.Linear.weight` is `(out_features, in_features)` = "
            "`(OC, IC)` — exact match. The conv's bias is already shape "
            "`(OC,)` matching Linear's.\n\n"
            "**Why `.clone()`.** Using `.data = ...` shares storage by "
            "default (when shapes match). Cloning makes the test's "
            "assertion 'modifying linear doesn't affect conv' true if "
            "you ever extend the drill — it's a habit-forming defensive "
            "copy. Not strictly required for the test as written.\n\n"
            "**Per-element formula identity.** For both ops:\n"
            "```\n"
            "y[b, oc, h, w] = sum_ic W[oc, ic] * x[b, ic, h, w] + bias[oc]\n"
            "```\n"
            "1×1 Conv2d and per-pixel Linear are LITERALLY the same "
            "computation. PyTorch's CUDA backends just happen to "
            "dispatch them through different kernels for memory-layout "
            "reasons.\n\n"
            "**Why this matters for ResNet bottlenecks.** The bottleneck "
            "block `Conv(1x1, IC→IC/4) → Conv(3x3, IC/4→IC/4) → Conv(1x1, "
            "IC/4→IC)` is 'squeeze, mix spatially, expand' — but you can "
            "also read it as 'per-pixel Linear projection, conv, per-"
            "pixel Linear projection'. That mental model is what makes "
            "transformer FFN blocks (`Linear → activation → Linear`) and "
            "CNN bottlenecks feel like the same primitive."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # resnet-stem
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "resnet-stem",
        "subtopic": "CNN: ResNet stem block",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_RESNET_STEM,
        "exercise_index": 1,
        "exercise_title": "build the ResNet stem and verify the 224 → 56 reduction",
        "slug": "build-the-resnet-stem-and-verify-the-224-to-56-reduction",
        "bloom_level": "Apply",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["resnet", "stem", "downsample", "sequential", "224-to-56"],
        "kcs": ["resnet-stem-recipe", "stem-shape-reduction-math"],
        "lo": (
            "Apply the ResNet stem recipe — Conv(7×7, s=2, p=3) + BN + "
            "ReLU + MaxPool(3×3, s=2, p=1) — wired into an `nn.Sequential` "
            "that turns `(B, 3, 224, 224)` into `(B, 64, 56, 56)`."
        ),
        "prompt_body": (
            "Implement `ex1_build_resnet_stem()` that returns an "
            "`nn.Sequential` containing the four-op ResNet stem block, in "
            "this exact order:\n\n"
            "1. `nn.Conv2d(in_channels=3, out_channels=64, kernel_size=7, "
            "stride=2, padding=3, bias=False)`\n"
            "2. `nn.BatchNorm2d(64)`\n"
            "3. `nn.ReLU(inplace=True)`\n"
            "4. `nn.MaxPool2d(kernel_size=3, stride=2, padding=1)`\n\n"
            "**Why each setting.**\n"
            "- `kernel_size=7, stride=2, padding=3` on the conv → big "
            "receptive field early, halves spatial size from 224 to 112. "
            "Shape: `(224 + 2*3 - 7) // 2 + 1 = 112`.\n"
            "- `bias=False` on the conv → bias is redundant before a "
            "BatchNorm that already has a learnable `beta` shift.\n"
            "- `inplace=True` on the ReLU → micro-optimization; the conv "
            "output isn't used elsewhere so overwriting it is safe.\n"
            "- `kernel_size=3, stride=2, padding=1` on the MaxPool → "
            "second 2× spatial reduction. Shape: "
            "`(112 + 2*1 - 3) // 2 + 1 = 56`.\n\n"
            "Putting it all together: `(B, 3, 224, 224) → (B, 64, 112, "
            "112) → ... → (B, 64, 56, 56)`. That's a 4× total spatial "
            "downsample plus a 3 → 64 channel lift in one block.\n\n"
            "**What the test checks.**\n"
            "- The returned object is `nn.Sequential` with 4 children.\n"
            "- Child types are correct, in the right order.\n"
            "- The conv has `kernel_size=7, stride=2, padding=3, "
            "bias=None`.\n"
            "- The maxpool has `kernel_size=3, stride=2, padding=1`.\n"
            "- Forward on `(B, 3, 224, 224)` yields exactly "
            "`(B, 64, 56, 56)`.\n"
            "- Smaller input (`(B, 3, 64, 64)`) yields `(B, 64, 16, 16)` "
            "— the 4× downsample is general, not 224-specific."
        ),
        "stub": (
            "import torch.nn as nn\n"
            "\n"
            "def ex1_build_resnet_stem():\n"
            '    """Return the ResNet stem: Conv(7,s=2,p=3) + BN + ReLU + MaxPool(3,s=2,p=1)."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "stem = ex1_build_resnet_stem()\n"
            "\n"
            "# Container type.\n"
            "assert isinstance(stem, nn.Sequential), f'expected nn.Sequential, got {type(stem).__name__}'\n"
            "assert len(stem) == 4, f'expected 4 children, got {len(stem)}'\n"
            "\n"
            "# Child types & order.\n"
            "assert isinstance(stem[0], nn.Conv2d),      f'child 0 should be Conv2d, got {type(stem[0]).__name__}'\n"
            "assert isinstance(stem[1], nn.BatchNorm2d), f'child 1 should be BatchNorm2d, got {type(stem[1]).__name__}'\n"
            "assert isinstance(stem[2], nn.ReLU),        f'child 2 should be ReLU, got {type(stem[2]).__name__}'\n"
            "assert isinstance(stem[3], nn.MaxPool2d),   f'child 3 should be MaxPool2d, got {type(stem[3]).__name__}'\n"
            "\n"
            "# Conv config.\n"
            "conv = stem[0]\n"
            "assert conv.in_channels == 3 and conv.out_channels == 64\n"
            "assert conv.kernel_size == (7, 7), f'kernel_size wrong: {conv.kernel_size}'\n"
            "assert conv.stride == (2, 2),      f'stride wrong: {conv.stride}'\n"
            "assert conv.padding == (3, 3),     f'padding wrong: {conv.padding}'\n"
            "assert conv.bias is None,          'conv should be bias=False (BN absorbs the shift)'\n"
            "\n"
            "# BN config.\n"
            "bn = stem[1]\n"
            "assert bn.num_features == 64, f'BN num_features should be 64, got {bn.num_features}'\n"
            "\n"
            "# MaxPool config.\n"
            "mp = stem[3]\n"
            "assert mp.kernel_size == 3, f'maxpool kernel_size should be 3, got {mp.kernel_size}'\n"
            "assert mp.stride == 2,      f'maxpool stride should be 2, got {mp.stride}'\n"
            "assert mp.padding == 1,     f'maxpool padding should be 1, got {mp.padding}'\n"
            "\n"
            "# Canonical 224 -> 56 reduction.\n"
            "x224 = t.randn(2, 3, 224, 224)\n"
            "stem.eval()    # so BN uses identity running stats\n"
            "y = stem(x224)\n"
            "assert y.shape == (2, 64, 56, 56), (\n"
            "    f'canonical ImageNet stem must produce (B,64,56,56), got {tuple(y.shape)}'\n"
            ")\n"
            "\n"
            "# Generalizes: 64x64 input → 64/4 = 16.\n"
            "x64 = t.randn(1, 3, 64, 64)\n"
            "y64 = stem(x64)\n"
            "assert y64.shape == (1, 64, 16, 16), (\n"
            "    f'64-input must produce 16 spatial (4x downsample), got {tuple(y64.shape)}'\n"
            ")\n"
            "\n"
            "# Intermediate-stage shape check: after the conv alone we should be at 112.\n"
            "y_after_conv = conv(x224)\n"
            "assert y_after_conv.shape == (2, 64, 112, 112), (\n"
            "    f'after stem conv expected (B,64,112,112), got {tuple(y_after_conv.shape)}'\n"
            ")"
        ),
        "solution_body": (
            "def ex1_build_resnet_stem():\n"
            "    import torch.nn as nn\n"
            "    return nn.Sequential(\n"
            "        nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False),\n"
            "        nn.BatchNorm2d(64),\n"
            "        nn.ReLU(inplace=True),\n"
            "        nn.MaxPool2d(kernel_size=3, stride=2, padding=1),\n"
            "    )"
        ),
        "solution_notes": (
            "**Why this exact spatial math.** The two stride-2 layers "
            "together produce a 4× downsample. Pairing the conv's "
            "`stride=2` with `padding=(K-1)/2 = 3` gives a CLEAN halving "
            "(not (224+5)//2+1=114, but (224+6-7)//2+1=112). The same "
            "trick applies to the MaxPool: `K=3, P=1` halves cleanly.\n\n"
            "**Why `bias=False` AND BatchNorm.** Both BN and bias add a "
            "per-channel constant. Stacking them is wasteful — BN's "
            "`beta` is exactly the same expressive power. ResNet sets "
            "every conv with a following BN to `bias=False` for this "
            "reason. The 64 saved scalars don't matter — but the "
            "PRINCIPLE matters every time you compose conv + norm.\n\n"
            "**Why MaxPool here, AvgPool at the head.** Stem MaxPool "
            "selects salient activations (after the first conv has "
            "produced edge/blob features). Head AvgPool (between last "
            "BlockGroup and `fc`) averages — that's what a classifier "
            "wants. Both share the einops `'b c (h p1) (w p2) -> b c h "
            "w'` axis-factor pattern; only the reducer differs.\n\n"
            "**Real torchvision stem.** "
            "`torchvision.models.resnet18().conv1` + `.bn1` + `.relu` + "
            "`.maxpool` matches this exactly. You can `assert "
            "str(stem) == str(resnet18_stem)` against the official model "
            "if you want to confirm the recipe."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # register-buffer
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "register-buffer",
        "subtopic": "PyTorch: register_buffer",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_REGISTER_BUFFER,
        "exercise_index": 1,
        "exercise_title": "register non-trainable state and verify state_dict membership",
        "slug": "register-non-trainable-state-and-verify-state-dict-membership",
        "bloom_level": "Apply",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["register_buffer", "state_dict", "non-trainable", "buffers"],
        "kcs": ["register-buffer-syntax", "buffer-vs-parameter-discrimination"],
        "lo": (
            "Apply `self.register_buffer(name, tensor)` to attach "
            "non-trainable state to a Module, and discriminate it from "
            "`nn.Parameter` via `.parameters()`, `.buffers()`, and "
            "`state_dict` membership."
        ),
        "prompt_body": (
            "Implement a `MyBN` Module that mimics the **state shape** of "
            "`nn.BatchNorm2d` — without doing any actual normalization. "
            "The module has FOUR pieces of channel-wise state:\n\n"
            "- `weight`: `nn.Parameter` of shape `(num_features,)`, "
            "initialized to **ones**. **Trainable.**\n"
            "- `bias`:   `nn.Parameter` of shape `(num_features,)`, "
            "initialized to **zeros**. **Trainable.**\n"
            "- `running_mean`: buffer of shape `(num_features,)`, "
            "initialized to **zeros**. **NOT trainable** — registered via "
            "`self.register_buffer('running_mean', t.zeros(...))`.\n"
            "- `running_var`:  buffer of shape `(num_features,)`, "
            "initialized to **ones**. **NOT trainable** — registered via "
            "`self.register_buffer('running_var', t.ones(...))`.\n\n"
            "No forward method needed — this drill is about getting the "
            "STATE registration right, not the math (the math is in the "
            "`batchnorm-running-stats` and `batchnorm-affine-params` "
            "drills).\n\n"
            "Skeleton:\n\n"
            "```\n"
            "class MyBN(nn.Module):\n"
            "    def __init__(self, num_features: int):\n"
            "        super().__init__()\n"
            "        # self.weight = nn.Parameter(...)\n"
            "        # self.bias   = nn.Parameter(...)\n"
            "        # self.register_buffer('running_mean', ...)\n"
            "        # self.register_buffer('running_var',  ...)\n"
            "```\n\n"
            "**What the test verifies (exercising the discrimination "
            "skill).**\n"
            "- `weight` and `bias` show up in `.parameters()`, NOT in "
            "`.buffers()`.\n"
            "- `running_mean` and `running_var` show up in `.buffers()`, "
            "NOT in `.parameters()`.\n"
            "- ALL FOUR show up in `state_dict()`.\n"
            "- Buffers have `requires_grad == False`.\n"
            "- Calling `.to('cpu')` (no-op on CPU but exercises the path) "
            "preserves all four.\n"
            "- A round-trip `state_dict()` → `load_state_dict()` "
            "preserves the running stats verbatim."
        ),
        "stub": (
            "import torch.nn as nn\n"
            "\n"
            "class MyBN(nn.Module):\n"
            "    def __init__(self, num_features: int):\n"
            "        super().__init__()\n"
            "        raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "C = 8\n"
            "bn = MyBN(C)\n"
            "\n"
            "# All four attributes exist and have correct shape & init.\n"
            "assert hasattr(bn, 'weight') and bn.weight.shape == (C,)\n"
            "assert hasattr(bn, 'bias')   and bn.bias.shape == (C,)\n"
            "assert hasattr(bn, 'running_mean') and bn.running_mean.shape == (C,)\n"
            "assert hasattr(bn, 'running_var')  and bn.running_var.shape == (C,)\n"
            "assert t.allclose(bn.weight,       t.ones(C)),  'weight should init to ones'\n"
            "assert t.allclose(bn.bias,         t.zeros(C)), 'bias should init to zeros'\n"
            "assert t.allclose(bn.running_mean, t.zeros(C)), 'running_mean should init to zeros'\n"
            "assert t.allclose(bn.running_var,  t.ones(C)),  'running_var should init to ones'\n"
            "\n"
            "# weight/bias are Parameters; running_* are NOT.\n"
            "assert isinstance(bn.weight, nn.Parameter), 'weight must be nn.Parameter'\n"
            "assert isinstance(bn.bias,   nn.Parameter), 'bias must be nn.Parameter'\n"
            "assert not isinstance(bn.running_mean, nn.Parameter), 'running_mean must NOT be nn.Parameter'\n"
            "assert not isinstance(bn.running_var,  nn.Parameter), 'running_var must NOT be nn.Parameter'\n"
            "\n"
            "# Parameter / buffer membership discrimination.\n"
            "param_names = {n for n, _ in bn.named_parameters()}\n"
            "buf_names   = {n for n, _ in bn.named_buffers()}\n"
            "assert param_names == {'weight', 'bias'}, (\n"
            "    f'expected params={{weight, bias}}, got {param_names}'\n"
            ")\n"
            "assert buf_names == {'running_mean', 'running_var'}, (\n"
            "    f'expected buffers={{running_mean, running_var}}, got {buf_names}'\n"
            ")\n"
            "\n"
            "# state_dict has ALL FOUR (this is the whole reason buffers exist).\n"
            "sd = bn.state_dict()\n"
            "assert set(sd.keys()) == {'weight', 'bias', 'running_mean', 'running_var'}, (\n"
            "    f'state_dict keys wrong: {set(sd.keys())}'\n"
            ")\n"
            "\n"
            "# requires_grad: True for params, False for buffers.\n"
            "assert bn.weight.requires_grad is True\n"
            "assert bn.bias.requires_grad   is True\n"
            "assert bn.running_mean.requires_grad is False, 'buffers should not require grad'\n"
            "assert bn.running_var.requires_grad  is False, 'buffers should not require grad'\n"
            "\n"
            "# .to('cpu') is a no-op on CPU but must not lose buffers (often a bug source).\n"
            "bn2 = bn.to('cpu')\n"
            "assert bn2.running_mean is not None and bn2.running_var is not None\n"
            "assert t.allclose(bn2.running_mean, t.zeros(C))\n"
            "\n"
            "# Round-trip: save, mutate, load, confirm restored.\n"
            "bn.running_mean.data.fill_(42.0)\n"
            "bn.running_var.data.fill_(3.14)\n"
            "sd2 = bn.state_dict()\n"
            "bn_fresh = MyBN(C)\n"
            "bn_fresh.load_state_dict(sd2)\n"
            "assert t.allclose(bn_fresh.running_mean, t.full((C,), 42.0)), 'running_mean lost in save/load round-trip'\n"
            "assert t.allclose(bn_fresh.running_var,  t.full((C,), 3.14)), 'running_var lost in save/load round-trip'"
        ),
        "solution_body": (
            "class MyBN(nn.Module):\n"
            "    def __init__(self, num_features: int):\n"
            "        super().__init__()\n"
            "        self.weight = nn.Parameter(t.ones(num_features))\n"
            "        self.bias   = nn.Parameter(t.zeros(num_features))\n"
            "        self.register_buffer('running_mean', t.zeros(num_features))\n"
            "        self.register_buffer('running_var',  t.ones(num_features))"
        ),
        "solution_notes": (
            "**Why `register_buffer` (not `self.running_mean = "
            "t.zeros(...)`).** A plain tensor attribute is invisible to "
            "PyTorch's machinery — it doesn't appear in `state_dict`, "
            "doesn't follow `.to(device)`, and gets lost when the model "
            "is pickled / re-instantiated. Without registration the "
            "running stats would be silently broken across save/load "
            "cycles. THIS is the single most-common 'why does my model "
            "give different outputs after I save and reload it?' bug.\n\n"
            "**Why buffers don't need a `nn.Buffer` wrapper.** Unlike "
            "parameters (which use `nn.Parameter` to mark them), buffers "
            "are tracked by NAME via the registration call. PyTorch "
            "stores them in a separate `_buffers` ordered dict on the "
            "module; that's the source of truth for `.buffers()` and "
            "the state_dict layout.\n\n"
            "**`persistent=True` is the default.** "
            "`register_buffer(name, tensor, persistent=False)` exists "
            "for buffers you want at runtime but NOT in `state_dict` — "
            "e.g., a cached positional-encoding table that can be "
            "regenerated. Rarely needed; default `persistent=True` is "
            "the right call for running stats.\n\n"
            "**Real BatchNorm has a third buffer.** `nn.BatchNorm2d` "
            "also registers `num_batches_tracked` (a long-tensor "
            "counter for stale-stat warnings). Out of scope for this "
            "drill, but illustrates the pattern: ANY non-trainable "
            "state that needs to survive save/load goes through "
            "`register_buffer`."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # replace-final-head
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "replace-final-head",
        "subtopic": "Transfer: Replace final head",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_REPLACE_HEAD,
        "exercise_index": 1,
        "exercise_title": "swap the final classifier of a toy backbone",
        "slug": "swap-the-final-classifier-of-a-toy-backbone",
        "bloom_level": "Apply",
        "difficulty_num": 2,
        "difficulty_dots": "🔴🔴⚪⚪⚪",
        "keywords": ["transfer-learning", "head-replace", "in_features", "model-fc"],
        "kcs": ["read-in-features-from-old-head", "assign-new-linear-to-fc"],
        "lo": (
            "Apply the transfer-learning head-swap pattern: read "
            "`model.fc.in_features` to learn the backbone width, then "
            "assign `model.fc = nn.Linear(in_features, new_num_classes)`."
        ),
        "prompt_body": (
            "A toy pretrained model is provided:\n\n"
            "```\n"
            "class ToyPretrained(nn.Module):\n"
            "    def __init__(self):\n"
            "        super().__init__()\n"
            "        self.backbone = nn.Sequential(\n"
            "            nn.Linear(10, 32),\n"
            "            nn.ReLU(),\n"
            "            nn.Linear(32, 16),     # backbone output width = 16\n"
            "        )\n"
            "        self.fc = nn.Linear(16, 1000)   # ImageNet-style 1000-class head\n"
            "    def forward(self, x):\n"
            "        return self.fc(self.backbone(x))\n"
            "```\n\n"
            "Implement `ex1_replace_head(model, new_num_classes)` that "
            "performs the head swap, then returns the modified `model`:\n\n"
            "1. **Read the backbone width** from the OLD head:\n"
            "   ```\n"
            "   in_features = model.fc.in_features\n"
            "   ```\n"
            "2. **Replace `model.fc`** with a new `nn.Linear`:\n"
            "   ```\n"
            "   model.fc = nn.Linear(in_features, new_num_classes)\n"
            "   ```\n"
            "3. Return `model`.\n\n"
            "Do NOT touch the backbone — this drill is specifically about "
            "the head-swap (the freeze step is a separate atom).\n\n"
            "**What the test checks.**\n"
            "- After the call, `model.fc.out_features == "
            "new_num_classes`.\n"
            "- `model.fc.in_features` STILL equals 16 (the backbone "
            "width).\n"
            "- The new head's params have `requires_grad == True` "
            "(brand-new Linear is trainable by default).\n"
            "- The new head is REGISTERED as a child module (it appears "
            "in `model.named_modules()`, `state_dict()`, and "
            "`model.parameters()`).\n"
            "- Forward pass works on a `(B, 10)` input and produces "
            "`(B, new_num_classes)`.\n"
            "- The OLD head's parameters are NO LONGER in "
            "`model.parameters()` (replacement is total, not "
            "additive)."
        ),
        "stub": (
            "import torch.nn as nn\n"
            "\n"
            "class ToyPretrained(nn.Module):\n"
            "    def __init__(self):\n"
            "        super().__init__()\n"
            "        self.backbone = nn.Sequential(\n"
            "            nn.Linear(10, 32),\n"
            "            nn.ReLU(),\n"
            "            nn.Linear(32, 16),\n"
            "        )\n"
            "        self.fc = nn.Linear(16, 1000)\n"
            "    def forward(self, x):\n"
            "        return self.fc(self.backbone(x))\n"
            "\n"
            "\n"
            "def ex1_replace_head(model, new_num_classes: int):\n"
            '    """Swap model.fc to an nn.Linear(in_features, new_num_classes). Returns model."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "model = ToyPretrained()\n"
            "# Snapshot the old head's parameter ids — they must NOT appear in model.parameters() after swap.\n"
            "old_head_ids = {id(p) for p in model.fc.parameters()}\n"
            "assert model.fc.out_features == 1000, 'fresh ToyPretrained should start with 1000-class head'\n"
            "\n"
            "n_classes = 7\n"
            "out_model = ex1_replace_head(model, n_classes)\n"
            "assert out_model is not None, 'must return the model'\n"
            "\n"
            "# Head shape after swap.\n"
            "assert out_model.fc.in_features  == 16, f'in_features changed unexpectedly: {out_model.fc.in_features}'\n"
            "assert out_model.fc.out_features == n_classes, (\n"
            "    f'out_features wrong: {out_model.fc.out_features} expected {n_classes}'\n"
            ")\n"
            "\n"
            "# New head is trainable.\n"
            "assert out_model.fc.weight.requires_grad is True\n"
            "assert out_model.fc.bias.requires_grad   is True\n"
            "\n"
            "# New head registered as a child — appears in state_dict and parameters().\n"
            "sd_keys = set(out_model.state_dict().keys())\n"
            "assert 'fc.weight' in sd_keys, f'fc.weight missing from state_dict: {sd_keys}'\n"
            "assert 'fc.bias'   in sd_keys, f'fc.bias missing from state_dict: {sd_keys}'\n"
            "param_ids = {id(p) for p in out_model.parameters()}\n"
            "assert id(out_model.fc.weight) in param_ids\n"
            "assert id(out_model.fc.bias)   in param_ids\n"
            "\n"
            "# Old head's params are GONE — replacement is total, not additive.\n"
            "assert old_head_ids.isdisjoint(param_ids), 'old head params still appear in model.parameters() after swap'\n"
            "\n"
            "# Forward pass works.\n"
            "x = t.randn(4, 10)\n"
            "y = out_model(x)\n"
            "assert y.shape == (4, n_classes), f'forward output shape wrong: {tuple(y.shape)}'\n"
            "\n"
            "# Different sizes round-trip cleanly.\n"
            "for n in [1, 2, 5, 100, 10000]:\n"
            "    m = ToyPretrained()\n"
            "    m = ex1_replace_head(m, n)\n"
            "    assert m.fc.out_features == n\n"
            "    assert m(t.randn(1, 10)).shape == (1, n)\n"
            "\n"
            "# The backbone is UNTOUCHED (this drill is only about the head).\n"
            "model_fresh = ToyPretrained()\n"
            "bb_before = [p.detach().clone() for p in model_fresh.backbone.parameters()]\n"
            "model_fresh = ex1_replace_head(model_fresh, 3)\n"
            "for p_now, p_then in zip(model_fresh.backbone.parameters(), bb_before):\n"
            "    assert t.equal(p_now, p_then), 'backbone was modified during head swap'"
        ),
        "solution_body": (
            "def ex1_replace_head(model, new_num_classes: int):\n"
            "    import torch.nn as nn\n"
            "    in_features = model.fc.in_features\n"
            "    model.fc = nn.Linear(in_features, new_num_classes)\n"
            "    return model"
        ),
        "solution_notes": (
            "**Why `model.fc.in_features` (not hard-coding 16).** "
            "Different backbones have different feature widths: "
            "ResNet-18/34 = 512, ResNet-50+ = 2048, ViT-B/16 = 768, "
            "MobileNet-v2 = 1280. Reading the dim off the OLD head makes "
            "the swap function backbone-agnostic — same code works on "
            "any standard architecture.\n\n"
            "**Why `model.fc = ...` works as a registration.** PyTorch's "
            "`nn.Module.__setattr__` intercepts assignment of "
            "`nn.Module` (or `nn.Parameter`) instances and registers "
            "them as children. So a plain Python attribute assignment "
            "is enough — no explicit `register_module` call needed. "
            "(The same machinery deregisters the old `fc` from "
            "`_modules` first.)\n\n"
            "**Common pitfall — different head names.** Not every "
            "torchvision model calls its head `fc`. Check the model's "
            "repr or `list(model.named_children())[-1]` to find the "
            "right attribute. Examples:\n"
            "- ResNet, GoogLeNet → `model.fc`\n"
            "- VGG, AlexNet, MobileNet → `model.classifier[-1]` "
            "(a Sequential)\n"
            "- ViT → `model.heads.head`\n"
            "- EfficientNet → `model.classifier[1]`\n\n"
            "**Why this composes with `freeze-requires-grad`.** The "
            "swap creates a brand-new Linear with `requires_grad=True`. "
            "If the backbone is frozen FIRST and the swap happens "
            "SECOND, the new head naturally becomes the only trainable "
            "submodule. That's the transfer-learning recipe."
        ),
    },
    # ═══════════════════════════════════════════════════════════════════════
    # state-dict-load
    # ═══════════════════════════════════════════════════════════════════════
    {
        "atom_id": "state-dict-load",
        "subtopic": "Transfer: state_dict load",
        "topic_folder": TOPIC,
        "atom_recap_md": RECAP_STATE_DICT_LOAD,
        "exercise_index": 1,
        "exercise_title": "load a checkpoint into a head-swapped model with strict=False",
        "slug": "load-a-checkpoint-into-a-head-swapped-model-with-strict-false",
        "bloom_level": "Analyze",
        "difficulty_num": 3,
        "difficulty_dots": "🔴🔴🔴⚪⚪",
        "keywords": ["load_state_dict", "strict-false", "incompatible-keys", "missing", "unexpected"],
        "kcs": ["load-state-dict-strict-false", "interpret-incompatible-keys-tuple"],
        "lo": (
            "Analyze the `_IncompatibleKeys(missing, unexpected)` return "
            "value of `load_state_dict(strict=False)` after swapping a "
            "model's head, distinguishing missing keys (model has, ckpt "
            "didn't provide) from unexpected (ckpt has, model doesn't "
            "want)."
        ),
        "prompt_body": (
            "A toy model + simulated checkpoint are provided:\n\n"
            "```\n"
            "class ToyModel(nn.Module):\n"
            "    def __init__(self, n_classes):\n"
            "        super().__init__()\n"
            "        self.backbone = nn.Linear(10, 16)\n"
            "        self.fc = nn.Linear(16, n_classes)\n"
            "    def forward(self, x):\n"
            "        return self.fc(self.backbone(x))\n"
            "```\n\n"
            "Implement `ex1_load_with_head_swap(model, checkpoint)` that:\n\n"
            "1. Calls `model.load_state_dict(checkpoint, strict=False)`.\n"
            "2. Returns a 3-tuple `(model, missing, unexpected)`:\n"
            "   - `model`: the loaded model (which the test then runs "
            "forward on).\n"
            "   - `missing`: a Python **list** of strings — the "
            "`missing_keys` from the returned `_IncompatibleKeys` "
            "named-tuple. These are state-dict keys the model has but "
            "the checkpoint didn't provide.\n"
            "   - `unexpected`: a Python **list** of strings — the "
            "`unexpected_keys` from the returned tuple. These are "
            "checkpoint keys the model didn't want.\n\n"
            "**Typical scenario for the test.** The checkpoint was saved "
            "from a 1000-class model (`fc.weight: (1000, 16), fc.bias: "
            "(1000,)`), but the user is loading it into a 7-class model "
            "(`fc.weight: (7, 16), fc.bias: (7,)`). The shape mismatch "
            "on `fc.*` keys is what makes `strict=True` raise — so "
            "`strict=False` is the right escape hatch, and the "
            "checkpoint is pre-cleaned by dropping the mismatching "
            "`fc.*` keys.\n\n"
            "**Reading the result.**\n"
            "- `backbone.weight, backbone.bias` → present in both → loaded "
            "successfully.\n"
            "- `fc.weight, fc.bias` → present in model only (checkpoint "
            "dropped them) → appear in `missing`.\n"
            "- A leftover `extra_buffer` key → present in checkpoint "
            "only → appears in `unexpected`.\n\n"
            "**Don't pre-process the checkpoint** — just pass it to "
            "`load_state_dict` with `strict=False`. The test constructs "
            "the checkpoint to produce the expected missing/unexpected "
            "lists."
        ),
        "stub": (
            "import torch.nn as nn\n"
            "\n"
            "class ToyModel(nn.Module):\n"
            "    def __init__(self, n_classes):\n"
            "        super().__init__()\n"
            "        self.backbone = nn.Linear(10, 16)\n"
            "        self.fc = nn.Linear(16, n_classes)\n"
            "    def forward(self, x):\n"
            "        return self.fc(self.backbone(x))\n"
            "\n"
            "\n"
            "def ex1_load_with_head_swap(model, checkpoint):\n"
            '    """Load checkpoint with strict=False; return (model, missing_list, unexpected_list)."""\n'
            "    raise NotImplementedError()"
        ),
        "test_body": (
            "import torch.nn as nn\n"
            "\n"
            "# Build a 7-class model.\n"
            "model = ToyModel(n_classes=7)\n"
            "\n"
            "# Simulate a 'pretrained' checkpoint:\n"
            "#  - has backbone.weight, backbone.bias (shape matches → load).\n"
            "#  - missing fc.weight, fc.bias entirely (head was stripped before save).\n"
            "#  - has an extra 'extra_buffer' key the model doesn't want.\n"
            "rng = t.Generator().manual_seed(0)\n"
            "checkpoint = {\n"
            "    'backbone.weight': t.randn(16, 10, generator=rng),\n"
            "    'backbone.bias':   t.randn(16,     generator=rng),\n"
            "    'extra_buffer':    t.zeros(5),\n"
            "}\n"
            "\n"
            "# Snapshot backbone weights before load to confirm they got overwritten.\n"
            "backbone_w_target = checkpoint['backbone.weight'].clone()\n"
            "fc_w_before       = model.fc.weight.detach().clone()\n"
            "\n"
            "loaded_model, missing, unexpected = ex1_load_with_head_swap(model, checkpoint)\n"
            "\n"
            "# Backbone got the checkpoint values (load succeeded for matching keys).\n"
            "assert t.allclose(loaded_model.backbone.weight, backbone_w_target), (\n"
            "    'backbone.weight should have been loaded from checkpoint'\n"
            ")\n"
            "\n"
            "# fc was NOT overwritten — checkpoint didn't provide it.\n"
            "assert t.equal(loaded_model.fc.weight, fc_w_before), (\n"
            "    'fc.weight should be unchanged (checkpoint had no fc.* keys)'\n"
            ")\n"
            "\n"
            "# Missing keys: fc.weight and fc.bias.\n"
            "assert isinstance(missing, list), f'missing must be a list, got {type(missing).__name__}'\n"
            "assert set(missing) == {'fc.weight', 'fc.bias'}, (\n"
            "    f'expected missing={{fc.weight, fc.bias}}, got {set(missing)}'\n"
            ")\n"
            "\n"
            "# Unexpected keys: extra_buffer.\n"
            "assert isinstance(unexpected, list), f'unexpected must be a list, got {type(unexpected).__name__}'\n"
            "assert set(unexpected) == {'extra_buffer'}, (\n"
            "    f'expected unexpected={{extra_buffer}}, got {set(unexpected)}'\n"
            ")\n"
            "\n"
            "# Forward pass works — backbone was loaded, fc is at fresh-init.\n"
            "x = t.randn(2, 10)\n"
            "y = loaded_model(x)\n"
            "assert y.shape == (2, 7), f'forward output shape wrong: {tuple(y.shape)}'\n"
            "\n"
            "# Second scenario: NO missing, NO unexpected (clean reload of the same model).\n"
            "m_clean = ToyModel(n_classes=7)\n"
            "sd_full = m_clean.state_dict()  # has fc.* matching shapes\n"
            "m_target = ToyModel(n_classes=7)\n"
            "m_target, miss2, unexp2 = ex1_load_with_head_swap(m_target, sd_full)\n"
            "assert miss2 == [],  f'clean reload should have no missing, got {miss2}'\n"
            "assert unexp2 == [], f'clean reload should have no unexpected, got {unexp2}'\n"
            "\n"
            "# Third scenario: ONLY unexpected (checkpoint has extra keys, model has everything else).\n"
            "ckpt_extra = dict(sd_full)\n"
            "ckpt_extra['orphan_buffer'] = t.zeros(3)\n"
            "m3, miss3, unexp3 = ex1_load_with_head_swap(ToyModel(n_classes=7), ckpt_extra)\n"
            "assert miss3 == []\n"
            "assert set(unexp3) == {'orphan_buffer'}"
        ),
        "solution_body": (
            "def ex1_load_with_head_swap(model, checkpoint):\n"
            "    result = model.load_state_dict(checkpoint, strict=False)\n"
            "    return model, list(result.missing_keys), list(result.unexpected_keys)"
        ),
        "solution_notes": (
            "**Reading `_IncompatibleKeys`.** It's a `typing.NamedTuple` "
            "with two fields, BOTH lists of strings:\n"
            "- `missing_keys`: keys the model expects but the checkpoint "
            "didn't provide. The corresponding params/buffers stay at "
            "their fresh-init values.\n"
            "- `unexpected_keys`: keys the checkpoint provided but the "
            "model doesn't want. They're silently dropped.\n\n"
            "**Why `strict=True` is the default.** Loose loading is "
            "DANGEROUS — a typo in a key name silently leaves a param "
            "at random init and you get a model that 'loaded' but "
            "behaves like a random net. `strict=True` forces every "
            "discrepancy to surface immediately. Use `strict=False` "
            "only when you EXPECT mismatches (transfer learning, "
            "architectural surgery, partial loads).\n\n"
            "**Mismatch in shape ≠ missing/unexpected.** If a key exists "
            "in both with INCOMPATIBLE shapes, modern PyTorch surfaces "
            "this with a `RuntimeError` even under `strict=False`. The "
            "safe pre-clean step before transfer learning:\n"
            "```\n"
            "for k in list(checkpoint.keys()):\n"
            "    if k.startswith('fc.'):\n"
            "        del checkpoint[k]      # drop head — will reappear in missing\n"
            "```\n"
            "Now `strict=False` happily loads the rest.\n\n"
            "**Composes with the other transfer-learning atoms.** "
            "Typical full recipe:\n"
            "1. Build model with new `n_classes` (or swap head — "
            "`replace-final-head` atom).\n"
            "2. Strip head keys from checkpoint.\n"
            "3. `load_state_dict(checkpoint, strict=False)` — this "
            "atom.\n"
            "4. Freeze backbone — `freeze-requires-grad` atom.\n"
            "5. Train head only.\n\n"
            "All four atoms in this batch (`replace-final-head`, "
            "`state-dict-load`, plus `register-buffer` for "
            "understanding what's saved, plus `freeze-requires-grad` "
            "from batch-4) compose into the canonical transfer-learning "
            "workflow."
        ),
    },
]


def main() -> None:
    for spec in SPECS:
        path = emit_standalone(spec)
        rel = path.relative_to(path.parents[3])
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
