"""watch.py — health checks for content_review

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../..'))


def check_imports():
    import glob
    here = os.path.dirname(os.path.abspath(__file__))
    assert glob.glob(os.path.join(here, '*.md')), 'no review reports present'


def check_public_api():
    here = os.path.dirname(os.path.abspath(__file__))
    rubric = os.path.join(here, '..', 'CONTENT_RUBRIC.md')
    assert os.path.exists(rubric), 'CONTENT_RUBRIC.md missing'


def check_invariants():
    # Every report is named YYYYMMDD-<scope>-<reviewer|NN>.(md|json)
    import re
    here = os.path.dirname(os.path.abspath(__file__))
    for name in os.listdir(here):
        if name in ('README.md', 'watch.py') or name.startswith('.'):
            continue
        assert re.match(r'^\d{8}(-\d{4})?-[a-z0-9-]+\.(md|json)$', name), f'bad report name: {name}'


if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
