#!/usr/bin/env python3
"""Merge authored drill hints into a frontend manifest.

Reads scripts/solution_build/drill_hints/*.jsonl ({path, hint}) and writes
Local_Deployed_Shared/practice/drill-hints-manifest.js defining
window.__drillHints = { "<notebookPath>": "<hint>", ... }, consumed by the drill
card's Show-hint button.
"""
from __future__ import annotations
import json, glob
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
HINTS_DIR = Path(__file__).resolve().parent / "drill_hints"
OUT = REPO / "Local_Deployed_Shared" / "practice" / "drill-hints-manifest.js"


def main() -> None:
    hints: dict[str, str] = {}
    for f in sorted(HINTS_DIR.glob("*.jsonl")):
        for line in f.read_text().splitlines():
            if line.strip():
                o = json.loads(line)
                p, h = o.get("path"), (o.get("hint") or "").strip()
                if p and h:
                    hints[p] = h
    OUT.write_text(
        "// AUTO-GENERATED by scripts/solution_build/build_drill_hints_manifest.py — do not edit.\n"
        "// Per-drill hint shown by the drill card's Show-hint button, keyed by notebookPath.\n"
        "window.__drillHints = " + json.dumps(hints, indent=1, ensure_ascii=False) + ";\n"
    )
    print(f"drill hints: {len(hints)} → {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
