"""watch.py — health checks for practice

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import json
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.dirname(HERE)

REQUIRED_JS = [
    "init.js", "dom.js", "events.js", "engine.js", "api.js",
    "runner.js", "visuals.js", "ui.js", "ai.js", "mode.js",
    "adaptive.js", "questions.js", "storage.js", "timer.js",
    "bars.js", "config.js",
]
REQUIRED_DOCS = ["README.md", "RUNTIME_CONTRACT.md"]
REQUIRED_ASSETS = [
    os.path.join(SHARED, "delta_numbers.npy"),
    os.path.join(SHARED, "numbers_stacked.png"),
    os.path.join(SHARED, "arena_prereqs_structured.json"),
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Folder is JS; verify required source files exist and parse-adjacent invariants
# (no Python modules to import directly).
def check_imports():
    missing = [f for f in REQUIRED_JS if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing, f"missing required JS files: {missing}"
    missing_docs = [f for f in REQUIRED_DOCS if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing_docs, f"missing required docs: {missing_docs}"
    missing_assets = [p for p in REQUIRED_ASSETS if not os.path.isfile(p)]
    assert not missing_assets, f"missing sibling assets: {missing_assets}"


# ── Public API checks ─────────────────────────
# Verify the runtime-contract surface stays intact: preamble builder is exported,
# fallback rendering helpers are present, and the question JSON is parseable.
def check_public_api():
    runner = _read(os.path.join(HERE, "runner.js"))
    assert "buildPyodidePreamble" in runner, "runner.js missing buildPyodidePreamble"
    assert "ensureArenaNumbersInPyodide" in runner, "runner.js missing ensureArenaNumbersInPyodide"

    visuals = _read(os.path.join(HERE, "visuals.js"))
    assert "renderQuestionVisual" in visuals, "visuals.js missing renderQuestionVisual"
    assert "renderFallbackImage" in visuals, "visuals.js missing PNG fallback (renderFallbackImage)"
    assert "getArenaNumbersPngCandidates" in visuals, "visuals.js missing PNG candidate resolver"

    questions_path = os.path.join(SHARED, "arena_prereqs_structured.json")
    data = json.loads(_read(questions_path))
    assert isinstance(data, list) and data, "arena_prereqs_structured.json is empty or not a list"


# ── Invariant checks ──────────────────────────
# Structural rules that must remain true:
#  1. No leftover modulario template markers.
#  2. Every question carries the runtime_dependencies contract.
#  3. The id-27 einsum entry has a non-null canonical_solution (was a known bug).
#  4. The Pyodide preamble's injected names match the doc's "Always injected" set.
def check_invariants():
    for fname in ("README.md", "watch.py"):
        first = _read(os.path.join(HERE, fname)).splitlines()[:1]
        assert first and "modulario:template" not in first[0], (
            f"{fname} still has modulario template marker on line 1"
        )

    data = json.loads(_read(os.path.join(SHARED, "arena_prereqs_structured.json")))
    bad = [q["id"] for q in data if "runtime_dependencies" not in q.get("exercise", {})]
    assert not bad, f"questions missing runtime_dependencies: {bad}"

    id27 = next((q for q in data if q.get("id") == 27), None)
    assert id27 is not None, "missing question id 27"
    assert id27["exercise"].get("canonical_solution"), "id-27 canonical_solution still null"

    runner = _read(os.path.join(HERE, "runner.js"))
    contract = _read(os.path.join(HERE, "RUNTIME_CONTRACT.md"))
    # Names that the doc claims are always/conditionally injected.
    for name in ("import numpy as np", "display_array_as_img", "delta_numbers.npy"):
        assert name in runner, f"runner.js no longer injects expected name: {name!r}"
        assert name.split()[-1].split("/")[-1] in contract or name in contract, (
            f"RUNTIME_CONTRACT.md does not mention {name!r}"
        )

    # The dispatch line that forces einops-questions to Pyodide is the documented gotcha.
    assert re.search(r"questionNeedsEinops\(", runner), (
        "runner.js no longer uses questionNeedsEinops gating — update RUNTIME_CONTRACT.md"
    )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
