"""watch.py — health checks for practice

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import json
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.dirname(HERE)

REQUIRED_JS = [
    "init.js", "dom.js", "events.js", "engine.js", "api.js",
    "runner.js", "visuals.js", "ui.js", "ai.js", "mode.js",
    "adaptive.js", "questions.js", "storage.js", "timer.js",
    "bars.js", "config.js",
    "arena-unlock-dom.js",  # injects #arena-unlock-page into #page-practice at script-eval time
    "arena-unlock.js",  # interstitial controller (consumes the stats/predicted-prereqs-temp.js scaffold)
]
REQUIRED_DOCS = ["README.md", "RUNTIME_CONTRACT.md"]
REQUIRED_ASSETS = [
    os.path.join(SHARED, "delta_numbers.npy"),
    os.path.join(SHARED, "numbers_stacked.png"),
    os.path.join(SHARED, "questions_structured.json"),
    os.path.join(SHARED, "arena_prereqs_structured.json"),
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Folder is JS; verify required source files exist and parse-adjacent invariants
# (no Python modules to import directly).
def check_imports():
    missing = [f for f in REQUIRED_JS if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing, f"missing required JS files: {missing}"
    missing_docs = [f for f in REQUIRED_DOCS if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing_docs, f"missing required docs: {missing_docs}"
    missing_assets = [p for p in REQUIRED_ASSETS if not os.path.isfile(p)]
    assert not missing_assets, f"missing sibling assets: {missing_assets}"


# ── Public API checks ─────────────────────────
# Verify the runtime-contract surface stays intact: preamble builder is exported,
# fallback rendering helpers are present, and the question JSON is parseable.
def check_public_api():
    runner = _read(os.path.join(HERE, "runner.js"))
    assert "buildPyodidePreamble" in runner, "runner.js missing buildPyodidePreamble"
    assert "ensureArenaNumbersInPyodide" in runner, "runner.js missing ensureArenaNumbersInPyodide"

    ui_js = _read(os.path.join(HERE, "ui.js"))
    assert "renderQuestionImports" in ui_js, "ui.js missing imports renderer"

    visuals = _read(os.path.join(HERE, "visuals.js"))
    assert "renderQuestionVisual" in visuals, "visuals.js missing renderQuestionVisual"
    assert "renderFallbackImage" in visuals, "visuals.js missing PNG fallback (renderFallbackImage)"
    assert "getArenaNumbersPngCandidates" in visuals, "visuals.js missing PNG candidate resolver"

    unlock = _read(os.path.join(HERE, "arena-unlock.js"))
    for needle in (
        "window.ArenaUnlock", "tryShow",
        # showFor is the manual-launch API consumed by the Targeted Practice
        # "Practice this problem" button. If this drops, the TP review-mode
        # action button silently no-ops with a console.warn.
        "showFor",
        "arena-unlock-page", "arena-unlock-card", "arena-unlock-continue-btn",
        ".practice-container",  # the view that gets swapped out on show
    ):
        assert needle in unlock, f"arena-unlock.js missing required symbol: {needle!r}"
    # The Colab href must fall back to currentEx.notebookPath so manual
    # launches from Targeted Practice point at the right notebook, not the
    # hardcoded 0.0 prereqs notebook used by the auto-unlock flow.
    assert re.search(r"currentEx[^\n]*notebookPath", unlock), (
        "arena-unlock.js colabHrefForUnlock lost the currentEx.notebookPath fallback "
        "— Targeted Practice will land on the wrong Colab notebook"
    )
    # The _targetedPractice flag must gate markArenaExerciseShown so manually
    # launched exercises remain re-practicable from the TP review page.
    assert "_targetedPractice" in unlock, (
        "arena-unlock.js no longer honors the _targetedPractice flag "
        "— Targeted-Practice exercises will get marked one-shot-shown"
    )
    # The unlock-page CSS lives in practice/arena-unlock.css (modular — kept
    # separate from practice.css so the unlock view can be ripped out when
    # the real concept-graph backend ships without touching the question UI).
    unlock_css = _read(os.path.join(HERE, "arena-unlock.css"))
    for needle in (".arena-unlock-page", ".arena-unlock-card", ".arena-unlock-continue-btn"):
        assert needle in unlock_css, f"arena-unlock.css missing required selector: {needle!r}"
    # The unlock view used to be authored inline in index.html. It was
    # extracted into practice/arena-unlock-dom.js (script-eval-time DOM
    # injection) to keep index.html under the per-file LOC ceiling.
    # Verify the DOM module still ships the mount + the load order puts
    # it BEFORE arena-unlock-timer.js and arena-unlock.js (both query the
    # injected ids at IIFE-eval time).
    dom_mount = _read(os.path.join(HERE, "arena-unlock-dom.js"))
    assert 'id="arena-unlock-page"' in dom_mount, (
        "arena-unlock-dom.js no longer injects #arena-unlock-page — the "
        "interstitial mount is the controller's hard dependency"
    )
    assert "page-practice" in dom_mount, (
        "arena-unlock-dom.js must mount into #page-practice "
        "(so the in-tab view swap with .practice-container works)"
    )
    index_html = _read(os.path.join(os.path.dirname(HERE), "index.html"))
    dom_pos = index_html.find('src="practice/arena-unlock-dom.js')
    timer_pos = index_html.find('src="practice/arena-unlock-timer.js')
    ctrl_pos = index_html.find('src="practice/arena-unlock.js')
    assert dom_pos != -1, 'index.html missing <script src="practice/arena-unlock-dom.js">'
    assert timer_pos != -1, 'index.html missing <script src="practice/arena-unlock-timer.js">'
    assert ctrl_pos != -1, 'index.html missing <script src="practice/arena-unlock.js">'
    assert dom_pos < timer_pos and dom_pos < ctrl_pos, (
        "arena-unlock-dom.js must load BEFORE arena-unlock-timer.js and "
        "arena-unlock.js — those controllers query the injected ids at "
        "IIFE-eval time and would silently no-op otherwise"
    )
    events_js = _read(os.path.join(HERE, "events.js"))
    assert "ArenaUnlock" in events_js, "events.js no longer routes through ArenaUnlock.tryShow"
    assert "_loadNextPracticeQuestion" in events_js, "events.js missing _loadNextPracticeQuestion helper"

    questions_path = os.path.join(SHARED, "questions_structured.json")
    data = json.loads(_read(questions_path))
    assert isinstance(data, list) and data, "questions_structured.json is empty or not a list"
    sample = next((q for q in data if q.get("exercise", {}).get("function_name")), None)
    assert sample is not None, "questions_structured.json has no function-backed practice questions"


# ── Invariant checks ──────────────────────────
# Structural rules that must remain true:
#  1. No leftover modulario template markers.
#  2. Every function-implementation question has a canonical_solution
#     (runtime_dependencies was dropped from the generator schema 2026-07-06).
#  3. The id-27 einsum entry has a non-null canonical_solution (was a known bug;
#     regressed once when the notebook's last cell had no trailing solution
#     markdown — now covered by the solutions-notebook fallback in
#     extract_arena_prereqs.py).
#  4. The Pyodide preamble's injected names match the doc's "Always injected" set.
def check_invariants():
    for fname in ("README.md", "watch.py"):
        first = _read(os.path.join(HERE, fname)).splitlines()[:1]
        assert first and "modulario:template" not in first[0], (
            f"{fname} still has modulario template marker on line 1"
        )

    data = json.loads(_read(os.path.join(SHARED, "arena_prereqs_structured.json")))
    bad = [
        q["id"] for q in data
        if q.get("exercise", {}).get("task_type") == "function_implementation"
        and not q.get("exercise", {}).get("canonical_solution")
    ]
    assert not bad, f"function questions missing canonical_solution: {bad}"

    id27 = next((q for q in data if q.get("id") == 27), None)
    assert id27 is not None, "missing question id 27"
    assert id27["exercise"].get("canonical_solution"), "id-27 canonical_solution still null"

    runner = _read(os.path.join(HERE, "runner.js"))
    contract = _read(os.path.join(HERE, "RUNTIME_CONTRACT.md"))
    # Names that the doc claims are always/conditionally injected.
    for name in ("import numpy as np", "display_array_as_img", "delta_numbers.npy"):
        assert name in runner, f"runner.js no longer injects expected name: {name!r}"
        assert name.split()[-1].split("/")[-1] in contract or name in contract, (
            f"RUNTIME_CONTRACT.md does not mention {name!r}"
        )

    # The dispatch line that forces einops-questions to Pyodide is the documented gotcha.
    assert re.search(r"questionNeedsEinops\(", runner), (
        "runner.js no longer uses questionNeedsEinops gating — update RUNTIME_CONTRACT.md"
    )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
