"""watch.py — health checks for concept_graphs

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import importlib.util
import json
import os
import sys

_HERE = os.path.dirname(__file__)
# backend/ is 3 levels up: concept_graphs -> data -> app -> backend
_BACKEND = os.path.abspath(os.path.join(_HERE, '../../..'))
_CG_PY = os.path.join(_BACKEND, 'app', 'concept_graph.py')
_V2 = os.path.join(_HERE, 'arena_iter5_v2.json')
_V3 = os.path.join(_HERE, 'arena_iter5_v3_encompassing.json')


def _pydantic_available():
    return importlib.util.find_spec('pydantic') is not None


def _load_cg_module():
    """Import concept_graph.py standalone (bypasses app/__init__ heavy deps)."""
    spec = importlib.util.spec_from_file_location('_dd_concept_graph', _CG_PY)
    mod = importlib.util.module_from_spec(spec)
    # Register before exec: concept_graph.py uses `from __future__ import
    # annotations`, so pydantic resolves forward refs via sys.modules[name].
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


# ── Import checks ──────────────────────────────
# Verify key modules in this folder can be imported without error.
def check_imports():
    if not _pydantic_available():
        return  # mod watch minimal env without pydantic — skip gracefully
    cg = _load_cg_module()
    cg.load_curriculum_graph(_V2)  # baseline graph still loads
    if os.path.exists(_V3):
        cg.load_curriculum_graph(_V3)  # encompassing graph loads + validates


# ── Public API checks ─────────────────────────
# Verify expected functions/classes exist and are callable.
def check_public_api():
    if not _pydantic_available():
        return
    cg = _load_cg_module()
    fields = cg.PrerequisiteEdge.model_fields
    assert 'is_encompassing' in fields, "PrerequisiteEdge missing is_encompassing"
    assert 'propagation_weight' in fields, "PrerequisiteEdge missing propagation_weight"
    assert callable(cg.encompassing_edges_from), "encompassing_edges_from not callable"


# ── Invariant checks ──────────────────────────
# Verify structural rules that must remain true for this folder.
def check_invariants():
    # encompassing ⊆ prerequisite: non-encompassing edges carry zero
    # propagation_weight; encompassing edges carry weight in (0, 0.6]; no
    # edge is a self-loop. Run on every graph JSON in this folder (pure JSON,
    # no pydantic needed).
    for name in os.listdir(_HERE):
        if not name.endswith('.json'):
            continue
        g = json.loads(open(os.path.join(_HERE, name), encoding='utf-8').read())
        for e in g.get('prerequisite_edges', []):
            assert e['prerequisite_id'] != e['dependent_id'], f"{name}: self-loop {e}"
            is_enc = e.get('is_encompassing', False)
            w = e.get('propagation_weight', 0.0)
            if not is_enc:
                assert w == 0.0, f"{name}: non-encompassing edge has weight {w}"
            else:
                assert 0.0 < w <= 1.0, f"{name}: encompassing weight {w} out of (0, 1.0]"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
