"""watch.py — health checks for lessons/leetcode (the LeetCode Patterns course)

Both files here are GENERATED by This-Directory-Only/scripts/leetcode_course/
export_app.py, which grades every row before writing it. This watch checks the
contract the app relies on without re-running the grader: ids stay in the
LeetCode range and never move, every drill targets a registered `leetcode.*`
concept, and every drill carries what the function grader needs.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import json
import os
import sys

_DIR = os.path.dirname(os.path.abspath(__file__))
ID_FLOOR, ID_CEIL = 60000, 70000  # math owns 50000+, pipeline/export_questions_json.py checks the floor


def _load(name):
    with open(os.path.join(_DIR, name), encoding="utf-8") as fh:
        return json.load(fh)


def check_imports():
    rows, ids = _load("problems.json"), _load("ids.json")
    assert isinstance(rows, list) and rows, "problems.json is empty or not a list"
    assert isinstance(ids, dict) and ids, "ids.json is empty or not an object"


def check_public_api():
    """Every row is a function drill the backend loader and grader accept."""
    for r in _load("problems.json"):
        for key in ("id", "question_text", "answer_code", "starter_code", "function_name", "leetcode_kc"):
            assert r.get(key), f"q{r.get('id')} has no {key}"
        assert r.get("submission_mode") == "function", f"q{r['id']} is not submission_mode=function"
        cases = r.get("test_cases") or []
        assert len(cases) >= 3, f"q{r['id']} has {len(cases)} test cases (< 3)"
        assert all(c.get("call") and "expected_expr" in c for c in cases), f"q{r['id']} has a malformed case"
        # The audit reads the FIRST case: a None answer there is a placeholder the bare starter passes.
        assert cases[0]["expected_expr"] != "None", f"q{r['id']} leads with a None-expected case"


def check_invariants():
    """Ids: in range, unique, and each row's id is the one ids.json assigned
    (append-only, so a learner's history never points at another problem).
    Concepts: every drill's KC is a registered leetcode.* row."""
    rows, ids = _load("problems.json"), _load("ids.json")
    qids = [r["id"] for r in rows]
    assert len(qids) == len(set(qids)), "duplicate question ids in problems.json"
    assert all(ID_FLOOR <= q < ID_CEIL for q in qids), "a question id is outside 60000-69999"
    assert len(set(ids.values())) == len(ids), "ids.json maps two problems to one question id"
    assigned = set(ids.values())
    assert set(qids) <= assigned, f"ids not assigned by ids.json: {sorted(set(qids) - assigned)[:5]}"
    with open(os.path.join(_DIR, "..", "kc_registry.json"), encoding="utf-8") as fh:
        kcs = {k["id"] for k in json.load(fh)["kcs"] if k["id"].startswith("leetcode.")}
    stray = sorted({r["leetcode_kc"] for r in rows} - kcs)
    assert not stray, f"drills target unregistered concepts: {stray}"


if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
