"""watch.py — health checks for practice

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import os
import re
import sys

THIS = os.path.dirname(__file__)
# practice/ lives at backend/app/practice/, so backend/ is two levels up.
sys.path.insert(0, os.path.join(THIS, '..', '..'))

SUB_ROUTERS = [
    'ai_router.py',
    'diagnostic_router.py',
    'feedback_router.py',
    'problem_feedback_router.py',
    'questions_router.py',
    'subtopic_router.py',
]
EXPECTED_PATHS = {
    '/api/practice/next-question',
    '/api/practice/submit',
    '/api/practice/submit-local-eval',
    '/api/practice/override',
    '/api/practice/feedback',
    '/api/practice/problem-feedback',
    '/api/practice/visual-debug',
    '/api/practice/subtopics',
    '/api/practice/weights',
    '/api/practice/run-code',
    '/api/practice/ai-explanation',
    '/api/practice/ai-judge',
    '/api/practice/diagnostic/status',
    '/api/practice/diagnostic/start',
    '/api/practice/diagnostic/answer',
    '/api/practice/diagnostic/finish',
    '/api/practice/diagnostic/decline',
}


def _fastapi_available():
    try:
        import fastapi  # noqa: F401
        return True
    except Exception:
        return False


# ── Import checks ──────────────────────────────
def check_imports():
    if not _fastapi_available():
        return  # `mod watch` runs in a minimal env; skip when fastapi missing
    from app.practice import (  # noqa: F401
        ai_router,
        chatgpt_helpers,
        diagnostic_router,
        feedback_router,
        grading,
        prompts,
        questions_router,
        subtopic_router,
    )
    from app.practice import router  # noqa: F401


# ── Public API checks ─────────────────────────
def check_public_api():
    # Always do the cheap text check so this works even without fastapi installed.
    for fname in SUB_ROUTERS + ['__init__.py']:
        path = os.path.join(THIS, fname)
        with open(path) as f:
            src = f.read()
        assert 'router' in src, f"{fname}: missing 'router' symbol"

    if not _fastapi_available():
        return
    from app.practice import router
    paths = {r.path for r in router.routes}
    missing = EXPECTED_PATHS - paths
    assert not missing, f"router missing endpoints: {sorted(missing)}"


# ── Invariant checks ──────────────────────────
def check_invariants():
    # Each sub-router declares a top-level `router = APIRouter(...)`.
    for fname in SUB_ROUTERS:
        path = os.path.join(THIS, fname)
        with open(path) as f:
            src = f.read()
        assert re.search(r'^router\s*=\s*APIRouter\(', src, re.MULTILINE), \
            f"{fname}: missing top-level `router = APIRouter(...)`"

    # __init__.py mounts every sub-router.
    with open(os.path.join(THIS, '__init__.py')) as f:
        init_src = f.read()
    for fname in SUB_ROUTERS:
        mod = fname[:-3]
        assert mod in init_src, f"__init__.py does not include {mod}"
    # And exposes a single aggregated `router` with the /api/practice prefix.
    assert "prefix=\"/api/practice\"" in init_src or "prefix='/api/practice'" in init_src, \
        "__init__.py must declare prefix='/api/practice' on the aggregated router"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
