"""watch.py — health checks for app

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import os
import sys

THIS = os.path.dirname(__file__)
# app/ lives at backend/app/, so backend/ is one level up.
sys.path.insert(0, os.path.join(THIS, '..'))


def _fastapi_available():
    try:
        import fastapi  # noqa: F401
        return True
    except Exception:
        return False


# ── Import checks ──────────────────────────────
def check_imports():
    if not _fastapi_available():
        return  # `mod watch` runs in a minimal env; skip when fastapi missing
    from app import main  # noqa: F401
    from app.practice import router  # noqa: F401
    from app.auth_router import router as _auth  # noqa: F401
    from app.jobs_router import router as _jobs  # noqa: F401
    from app.chapters_router import router as _chapters  # noqa: F401


# ── Public API checks ─────────────────────────
def check_public_api():
    # Cheap text checks that work without fastapi/sqlalchemy installed.
    main_path = os.path.join(THIS, 'main.py')
    with open(main_path) as f:
        main_src = f.read()
    assert 'app = FastAPI(' in main_src, "main.py: missing `app = FastAPI(...)`"
    assert 'app.include_router(practice_router)' in main_src, \
        "main.py: practice router is not mounted"
    # Top-level routers must each be mounted.
    for mod in ('auth_router', 'jobs_router', 'chapters_router'):
        assert f'app.include_router({mod})' in main_src, \
            f"main.py: {mod} is not mounted"

    if not _fastapi_available():
        return
    from app.main import app
    paths = {getattr(r, 'path', '') for r in app.routes}
    expected = {
        '/health',
        '/auth/signup',
        '/auth/login',
        '/jobs',
        '/jobs/{job_id}',
        '/jobs/{job_id}/artifacts',
        '/jobs/{job_id}/chapters',
        '/jobs/{job_id}/chapters/{chapter_id}/download',
        '/api/practice/next-question',
    }
    missing = expected - paths
    assert not missing, f"FastAPI app is missing endpoints: {sorted(missing)}"


# ── Invariant checks ──────────────────────────
def check_invariants():
    # The split-up practice package must replace the old monolith.
    assert not os.path.exists(os.path.join(THIS, 'practice_router.py')), \
        "Old monolithic practice_router.py is back — keep the split under app/practice/"
    assert os.path.isdir(os.path.join(THIS, 'practice')), \
        "app/practice/ package is missing"
    assert os.path.exists(os.path.join(THIS, 'practice', '__init__.py')), \
        "app/practice/__init__.py is missing"

    # main.py must import practice from the package, not the old module path.
    with open(os.path.join(THIS, 'main.py')) as f:
        main_src = f.read()
    assert 'from app.practice import router' in main_src, \
        "main.py must import the practice router from `app.practice`"
    assert 'from app.practice_router' not in main_src, \
        "main.py still references the old `app.practice_router` module"

    # main.py is the thin assembly layer — endpoint logic must live in
    # the *_router.py modules, not inline. Keep main.py LOC bounded so
    # nobody re-grows it back into ORANGE.
    main_loc = sum(1 for _ in open(os.path.join(THIS, 'main.py')))
    assert main_loc <= 60, \
        f"main.py grew to {main_loc} LOC — endpoint logic must move into a *_router.py module"

    # Each top-level router file declares a top-level `router = APIRouter(...)`.
    import re
    for fname in ('auth_router.py', 'jobs_router.py', 'chapters_router.py'):
        path = os.path.join(THIS, fname)
        assert os.path.exists(path), f"{fname} is missing"
        with open(path) as f:
            src = f.read()
        assert re.search(r'^router\s*=\s*APIRouter\(', src, re.MULTILINE), \
            f"{fname}: missing top-level `router = APIRouter(...)`"

    # practice_schemas.py stays at app/ level (not moved into practice/).
    assert os.path.exists(os.path.join(THIS, 'practice_schemas.py')), \
        "practice_schemas.py must stay at app/ level so non-practice modules can import it cheaply"

    # The staleness-review scaffolding is gone for good — do not resurrect it
    # as an override module; build any future revival inside prioritization.py.
    assert not os.path.exists(os.path.join(THIS, 'TEMP_staleness_review_REMOVE_LATER')), \
        "TEMP_staleness_review_REMOVE_LATER/ is back — fold the feature into prioritization.py instead"
    with open(os.path.join(THIS, 'prioritization.py')) as f:
        prio_src = f.read()
    assert 'TEMP_staleness_review_REMOVE_LATER' not in prio_src, \
        "prioritization.py references the deleted TEMP_staleness_review_REMOVE_LATER module"
    assert 'ENABLE_STALENESS_REVIEW' not in prio_src, \
        "ENABLE_STALENESS_REVIEW flag was deleted; remove the leftover reference"


def check_a_kp_is_taught_one_concept_at_a_time():
    """The gate must owe the learner ONE concept, and must not claim the KP.

    `<kc>` in the exposure map means the whole KP is done — every later gate
    reads it that way and stops firing. So while a segmented KP still has
    unread concepts, the key the gate hands back has to be the concept's, and
    the drill it points at has to be that concept's own. Getting this wrong is
    silent and permanent: the learner is credited with concepts 2 and 3, never
    sees them, and nothing ever asks again.
    """
    from app import lessons
    lessons._load()
    segmented = {kc: segs for kc, segs in lessons._kc_segments.items() if len(segs) > 1}
    assert segmented, "no KP has multiple concepts — the segment loop is dead code"

    kc, segs = sorted(segmented.items())[0]
    exposure = {}
    for expected, seg in enumerate(segs):
        step = lessons._segment_step(kc, exposure)
        assert step["segment_index"] == expected, \
            f"{kc}: gate is on concept {step['segment_index']}, expected {expected}"
        assert step["exposure_key"] == f"{kc}#{seg['concept_id']}", \
            f"{kc}: gate would write {step['exposure_key']!r}, not the concept's own key"
        assert step["exposure_key"] != kc, \
            f"{kc}: the KP's own key retires every remaining concept unread"
        assert step["drills"] == seg["drills"], \
            f"{kc}: concept {expected} would drill {step['drills']}, not its own {seg['drills']}"
        assert lessons.exposure_key_exists(step["exposure_key"]), \
            f"{kc}: /exposure would drop {step['exposure_key']!r} as unknown and re-teach forever"
        # Nothing may be integrated until every concept has been read.
        for qid in seg["drills"]:
            assert not lessons.is_integrated(qid, exposure), \
                f"{kc}: q{qid} reported integrated with concepts still untaught"
        exposure[step["exposure_key"]] = "now"

    assert lessons.exposure_key_exists(kc), "the KP's own key must stay storable"
    assert not lessons.exposure_key_exists(f"{kc}#not-a-concept"), \
        "/exposure would store a concept id nothing teaches"

    # Every concept read. Now the KP's whole-KP problems — and ONLY those —
    # may report the fifth rung. Exposure says what the learner has read; it
    # says nothing about what is on the screen, and `narrow_to_next_kc` falls
    # back to the unfiltered pool when a rung is spent, so without the second
    # half of the test a fill-in-the-blank drill for one of the three ideas
    # gets labelled as the problem that needs all of them.
    whole_kp = [
        qid for qid, src in lessons._question_source.items()
        if src == "kp-independent" and kc in lessons._question_target_kcs.get(qid, [])
    ]
    assert whole_kp, f"{kc}: no independent problems — nothing can be integrated"
    for qid in whole_kp:
        assert lessons.is_integrated(qid, exposure), \
            f"{kc}: q{qid} needs the whole KP but is not reported integrated"
    for seg in segs:
        for qid in seg["drills"]:
            assert not lessons.is_integrated(qid, exposure), \
                f"{kc}: q{qid} is one concept's drill and must never read as integrated"


def check_a_rung_reports_the_support_it_promises():
    """`faded` promises blanks; `partial` promises an example. Not each other.

    One boolean covering both rungs let each cover for the other: a faded drill
    with only an example still read as "most of the solution is written", and a
    partial one with only blanks still read as "read the example above". Both
    are reachable — the queue falls back to the unfiltered pool when a rung's
    own drills are spent — and both describe a page the learner is not looking
    at.
    """
    from app import lessons
    lessons._load()
    with_example = next(iter(lessons._applied_with_example), None)
    assert with_example, "no drill has a worked example — the third rung is empty"

    assert not lessons.rung_support(with_example, "faded", None), \
        "a worked example is being counted as blanks on the faded rung"
    assert lessons.rung_support(with_example, "faded", "def solve():\n    return _____"), \
        "blanks in the starter are not being counted on the faded rung"
    assert lessons.rung_support(with_example, "partial", None), \
        "a worked example is not being counted on the rung that promises one"
    assert not lessons.rung_support(0, "partial", "def solve():\n    return _____"), \
        "blanks are standing in for the example the partial rung promises"
    for stage in ("worked", "solo", ""):
        assert lessons.rung_support(0, stage, None), \
            f"stage {stage!r} promises no scaffold and must not report one missing"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [
        check_imports,
        check_public_api,
        check_invariants,
        check_a_kp_is_taught_one_concept_at_a_time,
        check_a_rung_reports_the_support_it_promises,
    ]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
