"""watch.py — health checks for app

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import os
import sys

THIS = os.path.dirname(__file__)
# app/ lives at backend/app/, so backend/ is one level up.
sys.path.insert(0, os.path.join(THIS, '..'))


def _fastapi_available():
    try:
        import fastapi  # noqa: F401
        return True
    except Exception:
        return False


# ── Import checks ──────────────────────────────
def check_imports():
    if not _fastapi_available():
        return  # `mod watch` runs in a minimal env; skip when fastapi missing
    from app import main  # noqa: F401
    from app.practice import router  # noqa: F401
    from app.auth_router import router as _auth  # noqa: F401
    from app.jobs_router import router as _jobs  # noqa: F401
    from app.chapters_router import router as _chapters  # noqa: F401


# ── Public API checks ─────────────────────────
def check_public_api():
    # Cheap text checks that work without fastapi/sqlalchemy installed.
    main_path = os.path.join(THIS, 'main.py')
    with open(main_path) as f:
        main_src = f.read()
    assert 'app = FastAPI(' in main_src, "main.py: missing `app = FastAPI(...)`"
    assert 'app.include_router(practice_router)' in main_src, \
        "main.py: practice router is not mounted"
    # Top-level routers must each be mounted.
    for mod in ('auth_router', 'jobs_router', 'chapters_router'):
        assert f'app.include_router({mod})' in main_src, \
            f"main.py: {mod} is not mounted"

    if not _fastapi_available():
        return
    from app.main import app
    paths = {getattr(r, 'path', '') for r in app.routes}
    expected = {
        '/health',
        '/auth/signup',
        '/auth/login',
        '/jobs',
        '/jobs/{job_id}',
        '/jobs/{job_id}/artifacts',
        '/jobs/{job_id}/chapters',
        '/jobs/{job_id}/chapters/{chapter_id}/download',
        '/api/practice/next-question',
    }
    missing = expected - paths
    assert not missing, f"FastAPI app is missing endpoints: {sorted(missing)}"


# ── Invariant checks ──────────────────────────
def check_invariants():
    # The split-up practice package must replace the old monolith.
    assert not os.path.exists(os.path.join(THIS, 'practice_router.py')), \
        "Old monolithic practice_router.py is back — keep the split under app/practice/"
    assert os.path.isdir(os.path.join(THIS, 'practice')), \
        "app/practice/ package is missing"
    assert os.path.exists(os.path.join(THIS, 'practice', '__init__.py')), \
        "app/practice/__init__.py is missing"

    # main.py must import practice from the package, not the old module path.
    with open(os.path.join(THIS, 'main.py')) as f:
        main_src = f.read()
    assert 'from app.practice import router' in main_src, \
        "main.py must import the practice router from `app.practice`"
    assert 'from app.practice_router' not in main_src, \
        "main.py still references the old `app.practice_router` module"

    # main.py is the thin assembly layer — endpoint logic must live in
    # the *_router.py modules, not inline. Keep main.py LOC bounded so
    # nobody re-grows it back into ORANGE.
    main_loc = sum(1 for _ in open(os.path.join(THIS, 'main.py')))
    assert main_loc <= 60, \
        f"main.py grew to {main_loc} LOC — endpoint logic must move into a *_router.py module"

    # Each top-level router file declares a top-level `router = APIRouter(...)`.
    import re
    for fname in ('auth_router.py', 'jobs_router.py', 'chapters_router.py'):
        path = os.path.join(THIS, fname)
        assert os.path.exists(path), f"{fname} is missing"
        with open(path) as f:
            src = f.read()
        assert re.search(r'^router\s*=\s*APIRouter\(', src, re.MULTILINE), \
            f"{fname}: missing top-level `router = APIRouter(...)`"

    # practice_schemas.py stays at app/ level (not moved into practice/).
    assert os.path.exists(os.path.join(THIS, 'practice_schemas.py')), \
        "practice_schemas.py must stay at app/ level so non-practice modules can import it cheaply"

    # The staleness-review scaffolding is gone for good — do not resurrect it
    # as an override module; build any future revival inside prioritization.py.
    assert not os.path.exists(os.path.join(THIS, 'TEMP_staleness_review_REMOVE_LATER')), \
        "TEMP_staleness_review_REMOVE_LATER/ is back — fold the feature into prioritization.py instead"
    with open(os.path.join(THIS, 'prioritization.py')) as f:
        prio_src = f.read()
    assert 'TEMP_staleness_review_REMOVE_LATER' not in prio_src, \
        "prioritization.py references the deleted TEMP_staleness_review_REMOVE_LATER module"
    assert 'ENABLE_STALENESS_REVIEW' not in prio_src, \
        "ENABLE_STALENESS_REVIEW flag was deleted; remove the leftover reference"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
