"""watch.py — health checks for app

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import os
import sys

THIS = os.path.dirname(__file__)
# app/ lives at backend/app/, so backend/ is one level up.
sys.path.insert(0, os.path.join(THIS, '..'))


def _fastapi_available():
    try:
        import fastapi  # noqa: F401
        return True
    except Exception:
        return False


# ── Import checks ──────────────────────────────
def check_imports():
    if not _fastapi_available():
        return  # `mod watch` runs in a minimal env; skip when fastapi missing
    from app import main  # noqa: F401
    from app.practice import router  # noqa: F401
    from app.auth_router import router as _auth  # noqa: F401
    from app.jobs_router import router as _jobs  # noqa: F401
    from app.chapters_router import router as _chapters  # noqa: F401


# ── Public API checks ─────────────────────────
def check_public_api():
    # Cheap text checks that work without fastapi/sqlalchemy installed.
    main_path = os.path.join(THIS, 'main.py')
    with open(main_path) as f:
        main_src = f.read()
    assert 'app = FastAPI(' in main_src, "main.py: missing `app = FastAPI(...)`"
    assert 'app.include_router(practice_router)' in main_src, \
        "main.py: practice router is not mounted"
    # Top-level routers must each be mounted.
    for mod in ('auth_router', 'jobs_router', 'chapters_router'):
        assert f'app.include_router({mod})' in main_src, \
            f"main.py: {mod} is not mounted"

    if not _fastapi_available():
        return
    from app.main import app
    paths = {getattr(r, 'path', '') for r in app.routes}
    expected = {
        '/health',
        '/auth/signup',
        '/auth/login',
        '/jobs',
        '/jobs/{job_id}',
        '/jobs/{job_id}/artifacts',
        '/jobs/{job_id}/chapters',
        '/jobs/{job_id}/chapters/{chapter_id}/download',
        '/api/practice/next-question',
        '/api/practice/kernel/exec',
    }
    missing = expected - paths
    assert not missing, f"FastAPI app is missing endpoints: {sorted(missing)}"


# ── Invariant checks ──────────────────────────
def check_invariants():
    # The split-up practice package must replace the old monolith.
    assert not os.path.exists(os.path.join(THIS, 'practice_router.py')), \
        "Old monolithic practice_router.py is back — keep the split under app/practice/"
    assert os.path.isdir(os.path.join(THIS, 'practice')), \
        "app/practice/ package is missing"
    assert os.path.exists(os.path.join(THIS, 'practice', '__init__.py')), \
        "app/practice/__init__.py is missing"

    # main.py must import practice from the package, not the old module path.
    with open(os.path.join(THIS, 'main.py')) as f:
        main_src = f.read()
    assert 'from app.practice import router' in main_src, \
        "main.py must import the practice router from `app.practice`"
    assert 'from app.practice_router' not in main_src, \
        "main.py still references the old `app.practice_router` module"

    # main.py is the thin assembly layer — endpoint logic must live in
    # the *_router.py modules, not inline. Keep main.py LOC bounded so
    # nobody re-grows it back into ORANGE.
    main_loc = sum(1 for _ in open(os.path.join(THIS, 'main.py')))
    assert main_loc <= 60, \
        f"main.py grew to {main_loc} LOC — endpoint logic must move into a *_router.py module"

    # Each top-level router file declares a top-level `router = APIRouter(...)`.
    import re
    for fname in ('auth_router.py', 'jobs_router.py', 'chapters_router.py'):
        path = os.path.join(THIS, fname)
        assert os.path.exists(path), f"{fname} is missing"
        with open(path) as f:
            src = f.read()
        assert re.search(r'^router\s*=\s*APIRouter\(', src, re.MULTILINE), \
            f"{fname}: missing top-level `router = APIRouter(...)`"

    # practice_schemas.py stays at app/ level (not moved into practice/).
    assert os.path.exists(os.path.join(THIS, 'practice_schemas.py')), \
        "practice_schemas.py must stay at app/ level so non-practice modules can import it cheaply"

    # The staleness-review scaffolding is gone for good — do not resurrect it
    # as an override module; build any future revival inside prioritization.py.
    assert not os.path.exists(os.path.join(THIS, 'TEMP_staleness_review_REMOVE_LATER')), \
        "TEMP_staleness_review_REMOVE_LATER/ is back — fold the feature into prioritization.py instead"
    with open(os.path.join(THIS, 'prioritization.py')) as f:
        prio_src = f.read()
    assert 'TEMP_staleness_review_REMOVE_LATER' not in prio_src, \
        "prioritization.py references the deleted TEMP_staleness_review_REMOVE_LATER module"
    assert 'ENABLE_STALENESS_REVIEW' not in prio_src, \
        "ENABLE_STALENESS_REVIEW flag was deleted; remove the leftover reference"


def check_a_kp_is_taught_one_concept_at_a_time():
    """The gate must owe the learner ONE concept, and must not claim the KP.

    `<kc>` in the exposure map means the whole KP is done — every later gate
    reads it that way and stops firing. So while a segmented KP still has
    unread concepts, the key the gate hands back has to be the concept's, and
    the drill it points at has to be that concept's own. Getting this wrong is
    silent and permanent: the learner is credited with concepts 2 and 3, never
    sees them, and nothing ever asks again.
    """
    from app import lessons
    lessons._load()
    segmented = {kc: segs for kc, segs in lessons._kc_segments.items() if len(segs) > 1}
    assert segmented, "no KP has multiple concepts — the segment loop is dead code"

    kc, segs = sorted(segmented.items())[0]
    exposure = {}
    for expected, seg in enumerate(segs):
        step = lessons._segment_step(kc, exposure)
        assert step["segment_index"] == expected, \
            f"{kc}: gate is on concept {step['segment_index']}, expected {expected}"
        assert step["exposure_key"] == f"{kc}#{seg['concept_id']}", \
            f"{kc}: gate would write {step['exposure_key']!r}, not the concept's own key"
        assert step["exposure_key"] != kc, \
            f"{kc}: the KP's own key retires every remaining concept unread"
        assert step["drills"] == seg["drills"], \
            f"{kc}: concept {expected} would drill {step['drills']}, not its own {seg['drills']}"
        assert lessons.exposure_key_exists(step["exposure_key"]), \
            f"{kc}: /exposure would drop {step['exposure_key']!r} as unknown and re-teach forever"
        # Nothing may be integrated until every concept has been read.
        for qid in seg["drills"]:
            assert not lessons.is_integrated(qid, exposure), \
                f"{kc}: q{qid} reported integrated with concepts still untaught"
        exposure[step["exposure_key"]] = "now"

    assert lessons.exposure_key_exists(kc), "the KP's own key must stay storable"
    assert not lessons.exposure_key_exists(f"{kc}#not-a-concept"), \
        "/exposure would store a concept id nothing teaches"

    # Every concept read. Now the KP's whole-KP problems — and ONLY those —
    # may report the fifth rung. Exposure says what the learner has read; it
    # says nothing about what is on the screen, and `narrow_to_next_kc` falls
    # back to the unfiltered pool when a rung is spent, so without the second
    # half of the test a fill-in-the-blank drill for one of the three ideas
    # gets labelled as the problem that needs all of them.
    whole_kp = [
        qid for qid, src in lessons._question_source.items()
        if src in ("kp-integrated", "kp-independent")
        and kc in lessons._question_target_kcs.get(qid, [])
    ]
    assert whole_kp, f"{kc}: no top-rung problems — nothing can be integrated"
    for qid in whole_kp:
        assert lessons.is_integrated(qid, exposure), \
            f"{kc}: q{qid} needs the whole KP but is not reported integrated"
    for seg in segs:
        for qid in seg["drills"]:
            assert not lessons.is_integrated(qid, exposure), \
                f"{kc}: q{qid} is one concept's drill and must never read as integrated"


def check_a_rung_reports_the_support_it_promises():
    """`faded` promises blanks. It is the only rung that promises anything.

    A faded drill served without blanks — reachable whenever a KC's own faded
    drills are spent — reads as "most of the solution is written for you" over
    a blank page, which describes a screen the learner is not looking at.

    `partial` is deliberately NOT here any more (2026-08-28). It used to promise
    an example above the problem, but examples are authored per ITEM: thirteen
    of the nineteen solo drills on `numpy.ndarray-model` have none, and the rung
    reported itself unsupported on every one of them. Examples now ORDER that
    rung (`kc_graph.with_example_first`) instead of defining it.
    """
    from app import lessons
    lessons._load()
    with_example = next(iter(lessons._applied_with_example), None)
    assert with_example, "no solo drill has a worked example — the fade has nothing to fade"

    assert not lessons.rung_support(with_example, "faded", None), \
        "a worked example is being counted as blanks on the faded rung"
    assert lessons.rung_support(with_example, "faded", "def solve():\n    return _____"), \
        "blanks in the starter are not being counted on the faded rung"
    for stage in ("worked", "partial", "solo", ""):
        assert lessons.rung_support(0, stage, None), \
            f"stage {stage!r} promises no scaffold and must not report one missing"


def check_a_new_rung_starts_empty():
    """The run of correct answers a rung is judged on is that RUNG's run.

    `kc_estimate` reports the trailing run so the strip can fill the active
    section along the route the learner is actually on. The raw run survives
    the promotion it buys: three correct answers at `faded` promote to
    `partial`, and the same three are still trailing, so the rung the learner
    reached one question ago would draw itself already full — a promise of a
    promotion `_streak_stage` will not make, because it aims one rung above the
    LOWEST answer in the run and that is the rung they now stand on.

    A rung the learner has answered nothing on reads empty. That is the whole
    claim, and it is behavioural: the string checks over in the frontend's
    watch cannot see a number that leaks across a rung boundary.
    """
    from types import SimpleNamespace
    from app import kc_graph

    def est(attempts, worked_seen=1):
        state = SimpleNamespace(kc_ladder={
            "kc": {"worked_seen": worked_seen, "attempts": list(attempts)}})
        return (kc_graph.kc_estimate(state, "kc"),
                kc_graph.kc_stage(state, "kc"))

    ok = lambda stage: {"correct": True, "stage": stage}
    miss = lambda stage: {"correct": False, "stage": stage}

    promoted, stage = est([ok("faded")] * 3)
    assert stage == "partial", \
        f"three correct at faded no longer promotes (stage={stage!r})"
    assert promoted["streak"] == 0, (
        "the rung the learner just reached is drawn "
        f"{promoted['streak']}/{promoted['streak_needed']} of the way through "
        "it, on answers made at the rung below"
    )

    # The control: a run made AT the rung being served still counts, or the
    # scoping has simply deleted the route instead of scoping it.
    on_rung, stage = est([miss("faded")] * 8 + [ok("faded")] * 2)
    assert stage == "faded", f"expected a stalled learner on faded, got {stage!r}"
    assert on_rung["streak"] == 2, (
        f"a run made at the rung being served reports {on_rung['streak']} — the "
        "streak route is no longer visible to the learner on it"
    )


def check_a_notebook_kernel_cannot_read_the_server():
    """A kernel outlives the cell that started it — so its fence must hold.

    `code_runner`'s grading child re-hardens itself on every run and then
    exits. A kernel hardens ONCE and then serves cells for twenty minutes, so
    every measure below is load-bearing for that whole window: a learner who
    can `import app.config` from a lesson cell reads the box's secrets.
    """
    path = os.path.join(THIS, 'kernel_runner.py')
    assert os.path.exists(path), "app/kernel_runner.py is missing"
    with open(path) as f:
        src = f.read()

    for measure, why in (
        ('os.setsid()', "the kernel has no process group of its own — a runaway "
                        "cell's children would survive the kill"),
        ('os.environ.clear()', "the kernel inherits the API process's environment, "
                               "including DATABASE_URL and the OpenAI key"),
        ('sys.modules["app"] = None', "a cell can `import app.config` and read the "
                                      "box's secrets"),
    ):
        assert measure in src, f"kernel_runner.py dropped {measure} — {why}"

    # The kernel is authenticated and its session key is derived from the
    # signed-in user. A client-supplied id would let one learner attach to
    # another learner's live namespace.
    router_path = os.path.join(THIS, 'practice', 'kernel_router.py')
    with open(router_path) as f:
        router_src = f.read()
    assert 'Depends(get_current_user)' in router_src, \
        "kernel_router.py no longer authenticates — anonymous callers could reserve kernels"
    assert 'f"u{user.id}"' in router_src, \
        "kernel_router.py session id is no longer derived from the signed-in user"

    # Caps exist because the box is 2gb and torch already lives in it.
    for cap in ('MAX_KERNELS', 'IDLE_SECONDS', 'MAX_RSS_MB'):
        assert cap in src, f"kernel_runner.py lost its {cap} cap"

    # The registry's RSS check runs between requests and skips a kernel that is
    # mid-cell, so the only thing standing between one `t.ones(10**10)` and the
    # box's OOM killer is the kernel watching its OWN memory.
    assert '_memory_watchdog' in src, \
        "kernel_runner.py dropped the in-kernel memory watchdog — a running cell " \
        "can now allocate past MAX_RSS_MB and take the API down with it"
    assert 'interrupt_main()' in src, \
        "the memory watchdog kills without asking first — a Python allocation loop " \
        "should unwind and leave the learner's session alive"

    # Status is the caller's own kernel. Signed in is not privileged: the
    # unscoped listing hands any learner every other learner's session id and
    # the lesson they are on.
    assert 'kernel_status(_session_id(user))' in router_src, \
        "kernel_router.py serves the whole registry to any signed-in learner"


def check_a_fresh_kernel_does_not_run_the_clicked_cell_twice():
    """`fresh` means the client is about to replay cells 1..N — which ENDS with
    the cell that was clicked. If the server ran that cell on the way to
    reporting `fresh`, it runs twice, and a cell that appends to a list, writes
    a file or bumps a counter is not the same run twice. `skip_on_fresh` is the
    client saying "if you had to build it, run nothing and just tell me"."""
    with open(os.path.join(THIS, 'kernel_runner.py')) as f:
        src = f.read()
    with open(os.path.join(THIS, 'practice', 'kernel_router.py')) as f:
        router_src = f.read()
    assert 'skip_on_fresh' in src, \
        "kernel_runner.run_cell lost skip_on_fresh — a replayed prefix now double-runs its last cell"
    assert 'if fresh and skip_on_fresh:' in src, \
        "skip_on_fresh is accepted but never honoured"
    assert 'skip_on_fresh=payload.skip_on_fresh' in router_src, \
        "kernel_router.py accepts skip_on_fresh but does not pass it through"

    # The bootstrap must still be installed on that skipped call, or the kernel
    # the client replays into has no `_delta_cell` and every cell NameErrors.
    boot = src.index('if fresh and bootstrap.strip():')
    skip = src.index('if fresh and skip_on_fresh:')
    assert boot < skip, \
        "the fresh-kernel shortcut returns before the harness is installed"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [
        check_imports,
        check_public_api,
        check_invariants,
        check_a_kp_is_taught_one_concept_at_a_time,
        check_a_rung_reports_the_support_it_promises,
        check_a_new_rung_starts_empty,
        check_a_notebook_kernel_cannot_read_the_server,
        check_a_fresh_kernel_does_not_run_the_clicked_cell_twice,
    ]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
