"""watch.py — health checks for backend

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Verify the FastAPI app's required structural pieces are present. We don't
# actually import the app module here — `mod watch` runs in a minimal env that
# typically lacks fastapi/supabase/uvicorn. Just confirm the files exist.
def check_imports():
    required = [
        "app/__init__.py",
        "app/main.py",
        "app/questions.py",
        "app/code_runner.py",
        "app/practice/__init__.py",
        "app/practice/questions_router.py",
        "app/practice/grading.py",
        "schema.sql",
        "requirements.txt",
    ]
    missing = [p for p in required if not os.path.isfile(os.path.join(HERE, p))]
    assert not missing, f"missing required backend files: {missing}"


# ── Public API checks ─────────────────────────
# Verify the public surfaces other code in this repo depends on are intact:
# the override-loading helpers, the wrapping helper for the solution-display
# path, and the question-router's response builder. These are the contract
# the practice frontend rides on.
def check_public_api():
    questions_py = _read(os.path.join(HERE, "app/questions.py"))
    for symbol in (
        "def load_questions(",
        "def _load_function_overrides(",
        "def _load_id_set(",
        "def _load_csv_into(",
        "def wrap_answer_as_function(",
        "def compose_full_solution(",
    ):
        assert symbol in questions_py, f"app/questions.py missing {symbol}"

    router_py = _read(os.path.join(HERE, "app/practice/questions_router.py"))
    for symbol in ("def next_question(", "def submit_answer(", "compose_full_solution"):
        assert symbol in router_py, f"app/practice/questions_router.py missing {symbol!r}"

    schema = _read(os.path.join(HERE, "schema.sql"))
    assert schema.strip(), "schema.sql is empty"
    assert "CREATE TABLE" in schema.upper(), "schema.sql appears to define no tables"


# ── Invariant checks ──────────────────────────
# Structural rules:
#  1. Override-loading reads BOTH function_mode and einops_prompt_rewrite
#     files. Removing one without routing it elsewhere drops repairs on the
#     floor — caught here.
#  2. The two questions_router response-building paths (next_question +
#     submit_answer) both use compose_full_solution so the user sees a
#     paste-ready solution; using bare answer_code regresses the UX.
#  3. requirements.txt pins fastapi (the app must boot under fastapi).
def check_invariants():
    questions_py = _read(os.path.join(HERE, "app/questions.py"))
    for layer in (
        "function_mode_overrides.jsonl",
        "function_mode_overrides_round2.jsonl",
        "function_mode_overrides_round3.jsonl",
        "einops_prompt_rewrite_overrides.jsonl",
        "numpy_einsum_prompt_rewrite_overrides.jsonl",
    ):
        assert layer in questions_py, (
            f"_load_function_overrides() must still merge {layer}"
        )

    router_py = _read(os.path.join(HERE, "app/practice/questions_router.py"))
    # Both response paths must use compose_full_solution, not raw answer_code.
    bad = re.findall(r"solution_code\s*=\s*question\.answer_code\b", router_py)
    assert not bad, (
        f"questions_router.py has {len(bad)} occurrences of "
        "`solution_code=question.answer_code` — should be wrapped with "
        "compose_full_solution(question.starter_code, question.answer_code)"
    )
    compose_uses = router_py.count("compose_full_solution(")
    assert compose_uses >= 2, (
        f"questions_router.py uses compose_full_solution() {compose_uses} times; "
        "expected at least 2 (next_question + submit_answer)"
    )

    reqs = _read(os.path.join(HERE, "requirements.txt"))
    assert re.search(r"^fastapi\b", reqs, flags=re.MULTILINE), (
        "requirements.txt must pin fastapi (app boots from app.main:app)"
    )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
