#!/usr/bin/env python3
"""Generate per-exercise anchor registry for ARENA notebooks.

Walks every notebookPath referenced by Local_Deployed_Shared/arena/manifest.js,
extracts every `## Exercise...` / `### Exercise...` / `#### Exercise...` heading
from the corresponding `.ipynb`, slugifies each heading to match the id Jupyter
Book / myst-nb generates in the built HTML, and writes
`Local_Deployed_Shared/arena/exercises.js` setting
`window.ARENA_EXERCISES_BY_NOTEBOOK`.

Slug rule (verified against arena-book/_build/html for chapter 0): lowercase,
strip backticks, collapse runs of non-alphanumeric chars into single hyphens,
strip leading/trailing hyphens.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parents[2]
SHARED_DIR = REPO_DIR / "Local_Deployed_Shared"
MANIFEST_PATH = SHARED_DIR / "arena" / "manifest.js"
OUT_PATH = SHARED_DIR / "arena" / "exercises.js"

EXERCISE_HEADING_RE = re.compile(r"^(#{2,4})\s+(Exercise\b.*)$")
NOTEBOOK_PATH_RE = re.compile(r'notebookPath:\s*"([^"]+)"')


def slugify(text: str) -> str:
    text = text.lower().replace("`", "")
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")


def extract_exercises(nb_path: Path) -> list[dict]:
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    out = []
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        source = cell.get("source", [])
        lines = source if isinstance(source, list) else source.splitlines(keepends=True)
        for line in lines:
            stripped = line.lstrip()
            m = EXERCISE_HEADING_RE.match(stripped.rstrip())
            if not m:
                continue
            heading = m.group(2).strip()
            out.append({"title": heading, "anchor": slugify(heading)})
    return out


def manifest_notebook_paths() -> list[str]:
    text = MANIFEST_PATH.read_text(encoding="utf-8")
    seen = set()
    paths = []
    for m in NOTEBOOK_PATH_RE.finditer(text):
        p = m.group(1)
        if p in seen:
            continue
        seen.add(p)
        paths.append(p)
    return paths


def main() -> None:
    registry: dict[str, list[dict]] = {}
    skipped: list[str] = []
    for rel in manifest_notebook_paths():
        nb_path = SHARED_DIR / rel
        if not nb_path.exists():
            skipped.append(rel)
            continue
        registry[rel] = extract_exercises(nb_path)

    body = json.dumps(registry, indent=2, ensure_ascii=False)
    OUT_PATH.write_text(
        "// AUTO-GENERATED by This-Directory-Only/scripts/extract_arena_exercises.py\n"
        "// Do not edit by hand. Re-run the script (or deploy) to refresh.\n"
        f"window.ARENA_EXERCISES_BY_NOTEBOOK = {body};\n",
        encoding="utf-8",
    )

    total = sum(len(v) for v in registry.values())
    print(f"Wrote {len(registry)} notebooks ({total} exercises) to {OUT_PATH}")
    if skipped:
        print(f"WARNING: skipped {len(skipped)} missing notebooks:")
        for p in skipped:
            print(f"  - {p}")


if __name__ == "__main__":
    main()
