/* GENERATED by scripts/generate_colab_notebooks.py — do not edit.
   Regenerate after changing lessons; the panel navigates by this map. */
window.DD_NOTEBOOKS = {
  "dir": "arena-book-colab/ARENA_5.0/ch-1-foundations",
  "lessons": [
    {
      "id": "ma-00",
      "title": "Linear algebra for ARENA 0.1",
      "topic": "Mathematics",
      "subtopic_key": "Mathematics: Linear algebra",
      "file": "ma-00-linear-algebra-for-arena-0-1.ipynb",
      "problems": 0
    },
    {
      "id": "ma-01",
      "title": "Math for ARENA 0.1",
      "topic": "Mathematics",
      "subtopic_key": "Mathematics: ARENA 0.1",
      "file": "ma-01-math-for-arena-0-1.ipynb",
      "problems": 0
    },
    {
      "id": "py-0",
      "title": "Python you need first",
      "topic": "Python",
      "subtopic_key": "Python: Getting started",
      "file": "py-0-python-you-need-first.ipynb",
      "problems": 110
    },
    {
      "id": "np-1",
      "title": "Tensors from the ground up",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Core array literacy",
      "file": "np-1-tensors-from-the-ground-up.ipynb",
      "problems": 279
    },
    {
      "id": "np-2",
      "title": "Indexing and selection",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Indexing and selection",
      "file": "np-2-indexing-and-selection.ipynb",
      "problems": 24
    },
    {
      "id": "np-3",
      "title": "Vectorization and broadcasting",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Vectorization and broadcasting",
      "file": "np-3-vectorization-and-broadcasting.ipynb",
      "problems": 68
    },
    {
      "id": "eo-1",
      "title": "Rearrange",
      "topic": "Einops",
      "subtopic_key": "Einops: Rearrange",
      "file": "eo-1-rearrange.ipynb",
      "problems": 70
    },
    {
      "id": "eo-2",
      "title": "Reduce",
      "topic": "Einops",
      "subtopic_key": "Einops: Reduce",
      "file": "eo-2-reduce.ipynb",
      "problems": 21
    },
    {
      "id": "eo-3",
      "title": "Repeat and deep-learning patterns",
      "topic": "Einops",
      "subtopic_key": "Einops: Deep Learning",
      "file": "eo-3-repeat-and-deep-learning-patterns.ipynb",
      "problems": 35
    },
    {
      "id": "tr-1",
      "title": "Rays as tensors (ARENA 0.1)",
      "topic": "PyTorch",
      "subtopic_key": "PyTorch: Rays as tensors",
      "file": "tr-1-rays-as-tensors--arena-0-1.ipynb",
      "problems": 40
    },
    {
      "id": "es-1",
      "title": "Einsum",
      "topic": "Einops",
      "subtopic_key": "Einops: Einsum",
      "file": "es-1-einsum.ipynb",
      "problems": 26
    },
    {
      "id": "ar-00",
      "title": "ARENA 0.0 — Tensor reasoning",
      "topic": "PyTorch",
      "subtopic_key": "PyTorch: ar-00",
      "file": "ar-00-arena-0-0---tensor-reasoning.ipynb",
      "problems": 93
    },
    {
      "id": "ar-01",
      "title": "ARENA 0.1 — Geometry and rendering",
      "topic": "PyTorch",
      "subtopic_key": "PyTorch: ar-01",
      "file": "ar-01-arena-0-1---geometry-and-rendering.ipynb",
      "problems": 67
    },
    {
      "id": "ar-02",
      "title": "ARENA 0.2 — Neural networks and ResNets",
      "topic": "PyTorch",
      "subtopic_key": "PyTorch: ar-02",
      "file": "ar-02-arena-0-2---neural-networks-and-resnets.ipynb",
      "problems": 190
    },
    {
      "id": "dd-1",
      "title": "What this app is, and the math behind it",
      "topic": "Delta Drills",
      "subtopic_key": "Delta Drills: How this app works",
      "file": "dd-1-what-this-app-is--and-the-math-behind-it.ipynb",
      "problems": 0
    }
  ],
  "subtopics": {
    "Mathematics: Linear algebra": "ma-00",
    "Mathematics: ARENA 0.1": "ma-01",
    "Python: Getting started": "py-0",
    "Numpy: Core array literacy": "np-1",
    "Numpy: Indexing and selection": "np-2",
    "Numpy: Vectorization and broadcasting": "np-3",
    "Einops: Rearrange": "eo-1",
    "Einops: Reduce": "eo-2",
    "Einops: Deep Learning": "eo-3",
    "PyTorch: Rays as tensors": "tr-1",
    "Einops: Einsum": "es-1",
    "PyTorch: ar-00": "ar-00",
    "PyTorch: ar-01": "ar-01",
    "PyTorch: ar-02": "ar-02",
    "Delta Drills: How this app works": "dd-1"
  }
};
