/* GENERATED by scripts/generate_colab_notebooks.py — do not edit.
   Regenerate after changing lessons; the panel navigates by this map. */
window.DD_NOTEBOOKS = {
  "dir": "arena-book-colab/ARENA_5.0/ch-1-foundations",
  "lessons": [
    {
      "id": "np-1",
      "title": "Arrays from the ground up",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Core array literacy",
      "file": "np-1-arrays-from-the-ground-up.ipynb",
      "problems": 112
    },
    {
      "id": "np-2",
      "title": "Indexing and selection",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Indexing and selection",
      "file": "np-2-indexing-and-selection.ipynb",
      "problems": 66
    },
    {
      "id": "np-3",
      "title": "Vectorization and broadcasting",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Vectorization and broadcasting",
      "file": "np-3-vectorization-and-broadcasting.ipynb",
      "problems": 67
    },
    {
      "id": "np-4",
      "title": "Applied patterns",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Applied patterns and advanced",
      "file": "np-4-applied-patterns.ipynb",
      "problems": 48
    },
    {
      "id": "es-1",
      "title": "Einsum notation",
      "topic": "Einsum",
      "subtopic_key": "Einsum: Core array literacy",
      "file": "es-1-einsum-notation.ipynb",
      "problems": 38
    },
    {
      "id": "es-2",
      "title": "Batch dimensions and applied einsum",
      "topic": "Einsum",
      "subtopic_key": "Einsum: Applied patterns and advanced",
      "file": "es-2-batch-dimensions-and-applied-einsum.ipynb",
      "problems": 30
    },
    {
      "id": "eo-1",
      "title": "Rearrange",
      "topic": "Einops",
      "subtopic_key": "Einops: Rearrange",
      "file": "eo-1-rearrange.ipynb",
      "problems": 52
    },
    {
      "id": "eo-2",
      "title": "Reduce",
      "topic": "Einops",
      "subtopic_key": "Einops: Reduce",
      "file": "eo-2-reduce.ipynb",
      "problems": 16
    },
    {
      "id": "eo-3",
      "title": "Repeat and deep-learning patterns",
      "topic": "Einops",
      "subtopic_key": "Einops: Deep Learning",
      "file": "eo-3-repeat-and-deep-learning-patterns.ipynb",
      "problems": 23
    }
  ],
  "subtopics": {
    "Numpy: Core array literacy": "np-1",
    "Numpy: Indexing and selection": "np-2",
    "Numpy: Vectorization and broadcasting": "np-3",
    "Numpy: Applied patterns and advanced": "np-4",
    "Einsum: Core array literacy": "es-1",
    "Einsum: Applied patterns and advanced": "es-2",
    "Einops: Rearrange": "eo-1",
    "Einops: Reduce": "eo-2",
    "Einops: Deep Learning": "eo-3"
  }
};
