/* GENERATED by scripts/generate_colab_notebooks.py — do not edit.
   Regenerate after changing lessons; the panel navigates by this map. */
window.DD_NOTEBOOKS = {
  "dir": "arena-book-colab/ARENA_5.0/ch-1-foundations",
  "lessons": [
    {
      "id": "py-0",
      "title": "Python you need first",
      "topic": "Python",
      "subtopic_key": "Python: Getting started",
      "file": "py-0-python-you-need-first.ipynb",
      "problems": 108
    },
    {
      "id": "np-1",
      "title": "Arrays from the ground up",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Core array literacy",
      "file": "np-1-arrays-from-the-ground-up.ipynb",
      "problems": 176
    },
    {
      "id": "np-2",
      "title": "Indexing and selection",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Indexing and selection",
      "file": "np-2-indexing-and-selection.ipynb",
      "problems": 14
    },
    {
      "id": "np-3",
      "title": "Vectorization and broadcasting",
      "topic": "Numpy",
      "subtopic_key": "Numpy: Vectorization and broadcasting",
      "file": "np-3-vectorization-and-broadcasting.ipynb",
      "problems": 25
    },
    {
      "id": "eo-1",
      "title": "Rearrange",
      "topic": "Einops",
      "subtopic_key": "Einops: Rearrange",
      "file": "eo-1-rearrange.ipynb",
      "problems": 51
    },
    {
      "id": "eo-2",
      "title": "Reduce",
      "topic": "Einops",
      "subtopic_key": "Einops: Reduce",
      "file": "eo-2-reduce.ipynb",
      "problems": 15
    },
    {
      "id": "eo-3",
      "title": "Repeat and deep-learning patterns",
      "topic": "Einops",
      "subtopic_key": "Einops: Deep Learning",
      "file": "eo-3-repeat-and-deep-learning-patterns.ipynb",
      "problems": 23
    },
    {
      "id": "tr-1",
      "title": "Rays as tensors (ARENA 0.1)",
      "topic": "PyTorch",
      "subtopic_key": "PyTorch: Rays as tensors",
      "file": "tr-1-rays-as-tensors--arena-0-1.ipynb",
      "problems": 32
    },
    {
      "id": "es-1",
      "title": "Einsum",
      "topic": "Einops",
      "subtopic_key": "Einops: Einsum",
      "file": "es-1-einsum.ipynb",
      "problems": 14
    }
  ],
  "subtopics": {
    "Python: Getting started": "py-0",
    "Numpy: Core array literacy": "np-1",
    "Numpy: Indexing and selection": "np-2",
    "Numpy: Vectorization and broadcasting": "np-3",
    "Einops: Rearrange": "eo-1",
    "Einops: Reduce": "eo-2",
    "Einops: Deep Learning": "eo-3",
    "PyTorch: Rays as tensors": "tr-1",
    "Einops: Einsum": "es-1"
  }
};
