#!/usr/bin/env python3
"""Build Local_Deployed_Shared/lessons/question_symbol_kcs.json.

The runtime half of the syntax rule (2026-09-17). `audit_solution_prereqs.py`
asks, at build time, whether every symbol a drill uses is taught by the
drill's own concept or one of its lattice ancestors. It reports; it cannot
stop a learner meeting `torch.arange` on a `numpy.boolean-masking` drill when
the page that teaches `arange` is on a branch they have not walked. This file
gives the backend what it needs to stop that at serve time:

    question_id -> {KC: [symbols]}   every KC that teaches a symbol the
                                     drill's solution, starter or prompt
                                     uses, EXCLUDING the drill's own targets

`backend/app/symbol_gate.py` then serves the drill only when each listed KC
is learned (mastered) or exposed (its lesson read). Symbols no page declares
are not here — nothing can be gated on them; the audit reports them as
`unowned` and that is content debt, not a gate.

Committed output, like qmatrix_tags.json; `scripts/watch.py`
(check_symbol_index_is_current) fails when it is stale.

Run: python3 scripts/build_symbol_prereqs.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from audit_lesson_syntax import lesson_order  # noqa: E402
from audit_solution_prereqs import (  # noqa: E402
    QMATRIX, QUESTIONS, SELF_DEFINED, SURFACES, declaring_kcs, owner_of,
    question_symbols,
)

OUT = QMATRIX.parent / "question_symbol_kcs.json"


def build() -> dict:
    bank = json.loads(QUESTIONS.read_text(encoding="utf-8"))
    questions = bank if isinstance(bank, list) else bank.get("questions", bank)
    qmatrix = json.loads(QMATRIX.read_text(encoding="utf-8"))
    declared, kc_of_page = declaring_kcs()
    rank = lesson_order(kc_of_page)
    index: dict[str, dict] = {}
    for q in questions:
        qid = q.get("id")
        targets = set((qmatrix.get(str(qid)) or {}).get("target_kcs") or [])
        owners: dict[str, list[str]] = {}
        for surface in SURFACES:
            for sym in sorted(question_symbols(q, surface)):
                if sym in SELF_DEFINED:
                    continue
                owner = owner_of(sym, declared, rank)
                if owner is None or owner in targets:
                    continue
                owners.setdefault(owner, [])
                if sym not in owners[owner]:
                    owners[owner].append(sym)
        if owners:
            index[str(qid)] = {kc: owners[kc] for kc in sorted(owners)}
    return {
        "_": "question_id -> {KC teaching a symbol the drill uses: [symbols]}, "
             "target KCs excluded. Generated by scripts/build_symbol_prereqs.py; "
             "do not hand-edit. Read by backend/app/symbol_gate.py.",
        "questions": index,
    }


def main() -> int:
    payload = build()
    text = json.dumps(payload, indent=1, sort_keys=True) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"STALE: {OUT.name} — run scripts/build_symbol_prereqs.py")
            return 1
        print(f"OK: {OUT.name} current ({len(payload['questions'])} drills)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(payload['questions'])} drills with off-concept symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
