#!/usr/bin/env bash
# publish_colab_notebooks.sh — put the generated notebooks somewhere Colab can open.
#
# WHY
#   Colab opens a notebook from GitHub, from Drive, or from an upload. The side
#   panel switches notebooks by URL, and the only URL it can COMPUTE rather than
#   be told is the GitHub one:
#
#     https://colab.research.google.com/github/<owner>/<repo>/blob/<branch>/<path>
#
#   So the 9 generated notebooks need to live in a repo. They go in their own
#   repo rather than in Delta-Drills because `arena-book-colab/` is gitignored
#   there on purpose — it also holds the 458 upstream ARENA notebooks, and the
#   deploy scripts run `git add -A`, so un-ignoring it would sweep all of that
#   into the next deploy commit.
#
# WHAT IT DOES
#   Regenerates the notebooks, then creates (or updates) <owner>/<repo> with
#   ARENA_5.0/ch-1-foundations/*.ipynb. Re-runs clone the existing repo and
#   commit on top — no force-push, no history rewrite.
#
# AFTERWARDS
#   Set the panel's "Notebook repo" (⚙) to:
#       <owner>/<repo>/ARENA_5.0/ch-1-foundations
#
# Usage: scripts/publish_colab_notebooks.sh [repo-name] [--private]
set -euo pipefail

REPO_NAME="arena-book-colab"
VISIBILITY="--public"
for arg in "$@"; do
  case "$arg" in
    --private) VISIBILITY="--private" ;;
    --public) VISIBILITY="--public" ;;
    -*) echo "unknown flag: $arg" >&2; exit 2 ;;
    *) REPO_NAME="$arg" ;;
  esac
done

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$HERE/arena-book-colab/ARENA_5.0/ch-1-foundations"
RELDIR="ARENA_5.0/ch-1-foundations"

command -v gh >/dev/null || { echo "gh CLI not found" >&2; exit 1; }
OWNER="$(gh api user -q .login)"

echo "▸ regenerating notebooks + index"
python3 "$HERE/scripts/generate_colab_notebooks.py" | tail -3

count=$(find "$SRC" -maxdepth 1 -name '*.ipynb' | wc -l)
[ "$count" -gt 0 ] || { echo "no notebooks in $SRC" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if gh repo view "$OWNER/$REPO_NAME" >/dev/null 2>&1; then
  echo "▸ $OWNER/$REPO_NAME exists — updating it"
  gh repo clone "$OWNER/$REPO_NAME" "$WORK/repo" -- --quiet
else
  echo "▸ creating $OWNER/$REPO_NAME ($VISIBILITY)"
  # `--clone` is a boolean flag and clones into ./<name>, so create and clone
  # are two steps here — the clone has to land inside the temp dir.
  gh repo create "$OWNER/$REPO_NAME" $VISIBILITY \
    -d "Delta Drills — ARENA foundations, compiled to Colab notebooks (generated)" >/dev/null
  git init -q -b main "$WORK/repo"
  git -C "$WORK/repo" remote add origin "https://github.com/$OWNER/$REPO_NAME.git"
fi

mkdir -p "$WORK/repo/$RELDIR"
rm -f "$WORK/repo/$RELDIR"/*.ipynb
cp "$SRC"/*.ipynb "$WORK/repo/$RELDIR/"

cat > "$WORK/repo/README.md" <<EOF
# arena-book-colab

Generated by \`scripts/generate_colab_notebooks.py\` in
[Delta-Drills](https://github.com/$OWNER/Delta-Drills). **Do not edit by hand** —
the next publish overwrites everything here.

$count notebooks in \`$RELDIR/\`. They are the practice surface for the Delta
Drills tutor: the Chrome side panel decides what you work on next and scrolls
you to the cell. Reading them front to back is not the intended use.

Point the panel's **Notebook repo** setting at:

    $OWNER/$REPO_NAME/$RELDIR
EOF

cd "$WORK/repo"
git add -- README.md "$RELDIR"
if git diff --cached --quiet; then
  echo "▸ nothing changed — already published"
else
  git commit -q -m "Regenerate Colab notebooks ($count lessons)"
  git push -q origin HEAD:main
  echo "▸ pushed"
fi

echo
echo "Repo:     https://github.com/$OWNER/$REPO_NAME"
echo "Panel ⚙:  $OWNER/$REPO_NAME/$RELDIR"
echo "Example:  https://colab.research.google.com/github/$OWNER/$REPO_NAME/blob/main/$RELDIR/$(basename "$(find "$SRC" -maxdepth 1 -name 'np-1*' | head -1)")"
