"""watch.py — health checks for backend/scripts

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Required script files must exist. We don't import them — they pull in the
# whole FastAPI app + sqlalchemy engine, which `mod watch` doesn't have.
def check_imports():
    required = ["init_db.py", "recompute_p_ewma.py"]
    missing = [f for f in required if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing, f"missing required scripts: {missing}"


# ── Public API checks ─────────────────────────
# init_db.py must define a callable main(); recompute_p_ewma.py is a top-level
# script that runs on import-as-main, so check for the EWMA constant instead.
def check_public_api():
    init_db = _read(os.path.join(HERE, "init_db.py"))
    assert "def main(" in init_db, "init_db.py must define def main()"
    assert 'if __name__ == "__main__":' in init_db or "if __name__ == '__main__':" in init_db, (
        "init_db.py must have an if __name__ == '__main__': guard"
    )

    recompute = _read(os.path.join(HERE, "recompute_p_ewma.py"))
    assert re.search(r"\bP_ALPHA\s*=", recompute), "recompute_p_ewma.py missing P_ALPHA constant"
    assert "user_data" in recompute, "recompute_p_ewma.py must reference user_data dir"


# ── Invariant checks ──────────────────────────
# Structural rules:
#  1. recompute_p_ewma.py's path to user_data must stay one level up
#     (parents[1]); moving the file without updating the path silently
#     breaks the migration.
#  2. init_db.py must keep idempotent guards (CREATE EXTENSION IF NOT EXISTS,
#     create_all). A non-idempotent migration here would corrupt prod on a
#     re-run.
def check_invariants():
    recompute = _read(os.path.join(HERE, "recompute_p_ewma.py"))
    assert "parents[1]" in recompute, (
        "recompute_p_ewma.py expects to be one level under backend/; "
        "the parents[1] path resolution must stay correct"
    )

    init_db = _read(os.path.join(HERE, "init_db.py"))
    assert "IF NOT EXISTS" in init_db.upper(), (
        "init_db.py must keep its IF NOT EXISTS guards to stay idempotent"
    )
    assert "create_all" in init_db, (
        "init_db.py must use Base.metadata.create_all (not raw DDL) to stay idempotent"
    )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
