"""watch.py — health checks for This-Directory-Only

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import csv
import json

HERE = os.path.dirname(os.path.abspath(__file__))

REQUIRED_DIRS = [
    "backend",
    "chatgpt",
    "csv files of problems",
    "scripts",
]
REQUIRED_FILES = [
    "serve.py",
    "Dockerfile",
    "fly.toml",
    "questions_full.json",
]
REQUIRED_CSVS = [
    "csv files of problems/Export of numpy problems with outputs.csv",
    "csv files of problems/einsum_problems.csv",
    "csv files of problems/einops_problems.csv",
]
REQUIRED_SCRIPTS = [
    "scripts/build_function_bank.py",
    "scripts/validate_function_bank.py",
    "scripts/export_questions_json.py",
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Folder is mixed Python + data + config; verify required structural pieces
# exist. No Python module import is meaningful here because backend/app pulls
# heavy deps (FastAPI, supabase) that aren't on the mod-watch sys.path.
def check_imports():
    missing_dirs = [d for d in REQUIRED_DIRS if not os.path.isdir(os.path.join(HERE, d))]
    assert not missing_dirs, f"missing required subdirs: {missing_dirs}"
    missing_files = [f for f in REQUIRED_FILES if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing_files, f"missing required files: {missing_files}"
    missing_csvs = [p for p in REQUIRED_CSVS if not os.path.isfile(os.path.join(HERE, p))]
    assert not missing_csvs, f"missing required CSVs: {missing_csvs}"
    missing_scripts = [p for p in REQUIRED_SCRIPTS if not os.path.isfile(os.path.join(HERE, p))]
    assert not missing_scripts, f"missing required scripts: {missing_scripts}"


# ── Public API checks ─────────────────────────
# Verify the data + script artifacts have the surfaces other tools depend on:
# CSVs parse with the expected header columns, questions_full.json parses,
# scripts have main() entry points.
def check_public_api():
    expected_csv_headers = {"Topic", "Subtopic", "Question", "Answer"}
    for rel_path in REQUIRED_CSVS:
        path = os.path.join(HERE, rel_path)
        with open(path, encoding="utf-8") as f:
            # Numpy CSV has 2 leading non-header rows; einsum/einops have headers on row 1.
            if rel_path.endswith("Export of numpy problems with outputs.csv"):
                next(f, None); next(f, None)
            reader = csv.DictReader(f)
            headers = set(reader.fieldnames or [])
            missing = expected_csv_headers - headers
            assert not missing, f"{rel_path} missing CSV headers: {missing} (got {headers})"

    qfull = os.path.join(HERE, "questions_full.json")
    try:
        data = json.loads(_read(qfull))
    except json.JSONDecodeError as e:
        raise AssertionError(f"questions_full.json is not valid JSON: {e}")
    assert isinstance(data, list) and data, "questions_full.json must be a non-empty list"

    # Each script must be standalone-runnable. The shims under scripts/
    # delegate to Local_Deployed_Shared/ via runpy.run_path; the originals
    # define def main(). Either pattern is acceptable.
    for rel_path in REQUIRED_SCRIPTS:
        text = _read(os.path.join(HERE, rel_path))
        assert "def main(" in text or "runpy.run_path(" in text, (
            f"{rel_path} missing entry point (def main() or runpy.run_path())"
        )


# ── Invariant checks ──────────────────────────
# Structural rules that must remain true:
#  1. AI runtime artifacts in chatgpt/ are JSONL-parseable when present.
#  2. The override format keys by integer id with required fields.
#  3. api_key.txt and .env files never accidentally end up in the public bundle.
def check_invariants():
    chatgpt_dir = os.path.join(HERE, "chatgpt")
    for fname in ("function_mode_overrides.jsonl", "einops_prompt_rewrite_overrides.jsonl"):
        path = os.path.join(chatgpt_dir, fname)
        if not os.path.isfile(path):
            continue  # optional file
        for lineno, line in enumerate(_read(path).splitlines(), 1):
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError as e:
                raise AssertionError(f"{fname}:{lineno} not valid JSON: {e}")
            assert isinstance(rec, dict), f"{fname}:{lineno} expected object, got {type(rec).__name__}"
            assert isinstance(rec.get("id"), int), f"{fname}:{lineno} missing/non-int id"

    # Secrets must not have leaked into Local_Deployed_Shared (the deploy bundle).
    public_dir = os.path.join(HERE, "..", "Local_Deployed_Shared")
    if os.path.isdir(public_dir):
        for forbidden in ("api_key.txt", ".openai_key"):
            assert not os.path.isfile(os.path.join(public_dir, forbidden)), (
                f"secret {forbidden!r} must not live in Local_Deployed_Shared (the deploy bundle)"
            )
        # A `.env` is OK at the public-dir root only if it has no OPENAI_ keys.
        public_env = os.path.join(public_dir, ".env")
        if os.path.isfile(public_env):
            assert "OPENAI" not in _read(public_env), "Local_Deployed_Shared/.env must not contain OPENAI keys"


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
