"""Validate the derived prereq graph in vocab/prereqs.json.

This file is GENERATED by scripts/derive_prereqs.py. To change its contents,
edit vocab/concept_edges.json or vocab/prereq_manual.json and re-run derive.

Checks (hard errors → exit 1):
  - Endpoint resolution: every `from`/`to` must be a known atom id.
  - Self-loops: `from == to` is invalid.
  - Duplicate edges: same (from, to) pair appears twice.
  - Acyclicity: the directed graph (from → to) must be a DAG. Cycles are reported
    using Kahn's algorithm.

Soft warnings (printed, exit 0):
  - Orphan atoms: vocab entries with no incoming and no outgoing edges.
  - Transitive-reduction candidates: edge (A,C) is redundant if there exists a
    path A → ... → C using other edges.

Run from repo root:
    python concept-graph/scripts/validate_graph.py
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict, deque
from pathlib import Path


def load_data(repo_root: Path) -> tuple[dict, dict]:
    with (repo_root / "vocab" / "atoms.json").open() as f:
        vocab = json.load(f)
    with (repo_root / "vocab" / "prereqs.json").open() as f:
        prereqs = json.load(f)
    return vocab, prereqs


def check_endpoints(edges: list[dict], known: set[str]) -> list[str]:
    errs = []
    for i, e in enumerate(edges):
        if e["from"] not in known:
            errs.append(f"edge[{i}] from='{e['from']}' not in vocab")
        if e["to"] not in known:
            errs.append(f"edge[{i}] to='{e['to']}' not in vocab")
    return errs


def check_self_loops(edges: list[dict]) -> list[str]:
    return [f"edge[{i}] self-loop on '{e['from']}'" for i, e in enumerate(edges) if e["from"] == e["to"]]


def check_duplicates(edges: list[dict]) -> list[str]:
    seen: dict[tuple, int] = {}
    errs = []
    for i, e in enumerate(edges):
        key = (e["from"], e["to"])
        if key in seen:
            errs.append(f"edge[{i}] duplicate of edge[{seen[key]}]: {key}")
        else:
            seen[key] = i
    return errs


def find_cycles(nodes: set[str], adj: dict[str, list[str]]) -> list[list[str]]:
    indeg = {n: 0 for n in nodes}
    for u in nodes:
        for v in adj.get(u, []):
            indeg[v] = indeg.get(v, 0) + 1
    q = deque(n for n in nodes if indeg[n] == 0)
    visited = 0
    while q:
        u = q.popleft()
        visited += 1
        for v in adj.get(u, []):
            indeg[v] -= 1
            if indeg[v] == 0:
                q.append(v)
    if visited == len(nodes):
        return []
    residue = [n for n in nodes if indeg[n] > 0]
    return [residue]


def find_orphans(known: set[str], edges: list[dict]) -> list[str]:
    touched: set[str] = set()
    for e in edges:
        touched.add(e["from"])
        touched.add(e["to"])
    return sorted(known - touched)


def find_transitive_redundancies(edges: list[dict]) -> list[tuple[str, str]]:
    adj: dict[str, set[str]] = {}
    for e in edges:
        adj.setdefault(e["from"], set()).add(e["to"])

    redundant = []
    for u in list(adj.keys()):
        for v in list(adj[u]):
            stack = [w for w in adj[u] if w != v]
            seen = set(stack)
            while stack:
                w = stack.pop()
                neigh = adj.get(w, set())
                if v in neigh:
                    redundant.append((u, v))
                    break
                for x in neigh:
                    if x not in seen:
                        seen.add(x)
                        stack.append(x)
    return redundant


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    vocab, prereqs = load_data(repo_root)
    known = {a["id"] for a in vocab["atoms"]}
    edges = prereqs.get("edges", [])

    print(f"vocab: {len(known)} atoms")
    print(f"edges: {len(edges)}")
    print()

    hard_errors: list[str] = []
    hard_errors += check_endpoints(edges, known)
    hard_errors += check_self_loops(edges)
    hard_errors += check_duplicates(edges)

    if hard_errors:
        print("HARD ERRORS:")
        for e in hard_errors:
            print(f"  {e}")
        print()
        return 1

    adj: dict[str, list[str]] = defaultdict(list)
    nodes: set[str] = set()
    for e in edges:
        adj[e["from"]].append(e["to"])
        nodes.add(e["from"])
        nodes.add(e["to"])

    cycles = find_cycles(nodes, adj)
    if cycles:
        print("HARD ERROR: cycle detected. Nodes in cyclic component(s):")
        for c in cycles:
            for n in c:
                print(f"  {n}")
        return 1

    orphans = find_orphans(known, edges)
    redundant = find_transitive_redundancies(edges)

    print(f"DAG: OK ({len(nodes)}/{len(known)} atoms reached by ≥1 edge)")
    if orphans:
        print(f"\nORPHAN atoms ({len(orphans)} with no edges):")
        for o in orphans:
            print(f"  {o}")
    if redundant:
        print(f"\nTRANSITIVE-REDUCTION candidates ({len(redundant)} edges implied by longer paths):")
        for u, v in redundant:
            print(f"  {u} -> {v}")
    print("\nOK: graph is valid.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
