"""watch.py — health checks for Local_Deployed_Shared

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import re
import json

HERE = os.path.dirname(os.path.abspath(__file__))

REQUIRED_FILES = [
    "questions.json",
    "questions_structured.json",
    "arena_prereqs_structured.json",
    "delta_numbers.npy",
    "numbers_stacked.png",
    "practice.js",
    "practice_engine.py",
    # practice.css was split into styles/practice/*.css (2026-07-12)
    "styles/practice/layout.css",
    "styles/practice/timer.css",
    "styles/practice/question.css",
    "styles/practice/feedback.css",
    "styles/practice/editor.css",
    "styles/practice/misc.css",
    "index.html",
    "app.js",
    "nav-drawer.js",
    "solo-route.js",
    "styles/solo-route.css",
    "courses.js",
    # Test users (@P, 2026-08-23): a demo identity swap. Listed here because
    # index.html loads all three unconditionally — a missing one is a 404 on
    # every page load, not a feature that quietly stays off.
    "test-users.js",
    "test-users-ui.js",
    "styles/test-users.css",
]
REQUIRED_DIRS = [
    "practice",
    "arena",
    "content/ARENA_3.0-main",
    "content/ARENA_4.0-main",
    "chatgpt",
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Folder is mixed Python/JS/data; verify the structural pieces are present and
# the JSON data files parse cleanly. No Python module import is meaningful here
# because most siblings pull heavy deps (numpy, requests, etc.) at import time.
def check_imports():
    missing = [f for f in REQUIRED_FILES if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing, f"missing required files: {missing}"
    missing_dirs = [d for d in REQUIRED_DIRS if not os.path.isdir(os.path.join(HERE, d))]
    assert not missing_dirs, f"missing required subdirs: {missing_dirs}"

    for fname in ("questions.json", "questions_structured.json", "arena_prereqs_structured.json"):
        try:
            json.loads(_read(os.path.join(HERE, fname)))
        except json.JSONDecodeError as e:
            raise AssertionError(f"{fname} is not valid JSON: {e}")


# ── Public API checks ─────────────────────────
# The frontend depends on a few static asset paths and on the prereq question
# schema. Verify the question records expose the fields the practice runtime
# reads (starter_code, canonical_solution where expected, runtime contract).
def check_public_api():
    prereqs = json.loads(_read(os.path.join(HERE, "arena_prereqs_structured.json")))
    assert isinstance(prereqs, list) and prereqs, "arena_prereqs_structured.json must be a non-empty list"

    # Current extract_arena_prereqs.py schema — runtime_dependencies was
    # dropped from the generator (stale invariant removed 2026-07-06).
    required_keys = {"starter_code", "expected_artifact_type", "supports_visual_output", "task_type", "canonical_solution"}
    for q in prereqs:
        ex = q.get("exercise") or {}
        missing = required_keys - ex.keys()
        assert not missing, f"question id={q.get('id')} missing exercise keys: {missing}"


# ── Invariant checks ──────────────────────────
# Structural rules that must remain true for this folder.
def check_invariants():
    # The PNG fallback and source array must remain at canonical served paths.
    for asset in ("delta_numbers.npy", "numbers_stacked.png"):
        path = os.path.join(HERE, asset)
        assert os.path.getsize(path) > 0, f"{asset} is empty"

    # Each declared tab in index.html must have a matching <main id="page-${name}">,
    # and every auth-gated tab must be listed in app.js authRequiredTabs. Drift here
    # silently breaks navigation (clicking the tab hides every page).
    index_html = _read(os.path.join(HERE, "index.html"))
    app_js = _read(os.path.join(HERE, "app.js"))
    # learn / arena / course / papers tabs were removed from the SPA before
    # this session; statistics was removed 2026-07-31. Keep this list aligned
    # with the actual tab buttons in index.html (and authRequiredTabs in app.js).
    expected_tabs = ("split-tool", "account", "courses", "practice", "targeted-practice")
    # Tabs app.js must still name explicitly, i.e. the ones on an auth/mode
    # list. Routing itself is generic (`tabs.forEach(... switchTab)`), so a tab
    # absent from every list is correctly reachable without a literal.
    # "account" left this set on 2026-08-22: it stopped being guest-blocked so
    # signed-out visitors can reach the basic/advanced mode toggle it hosts.
    auth_listed_tabs = ("split-tool", "courses", "targeted-practice")
    # page-targeted-practice lives in a -dom.js module (extracted from
    # index.html to keep it under the per-file LOC ceiling); check that
    # source file for the mount instead of index.html.
    runtime_mounts = {
        "targeted-practice": os.path.join(HERE, "targeted-practice", "targeted-practice-dom.js"),
    }
    for tab in expected_tabs:
        assert f'data-tab="{tab}"' in index_html, f'index.html missing tab button data-tab="{tab}"'
        mount_src = runtime_mounts.get(tab, index_html)
        if isinstance(mount_src, str) and mount_src != index_html:
            mount_src = _read(mount_src)
        assert f'id="page-{tab}"' in mount_src, (
            f'<main id="page-{tab}"> missing — checked '
            f'{"runtime DOM module" if tab in runtime_mounts else "index.html"}'
        )
        if tab in auth_listed_tabs:
            assert f'"{tab}"' in app_js, f'app.js auth/mode list missing "{tab}"'

    # Targeted Practice must sit immediately after Practice and is now the
    # last tab in the nav (Statistics, which used to follow it, was removed
    # 2026-07-31). Order matters because the keyboard tab-cycle and the
    # user's mental model both follow left-to-right ordering.
    practice_pos = index_html.find('data-tab="practice"')
    targeted_pos = index_html.find('data-tab="targeted-practice"')
    assert -1 not in (practice_pos, targeted_pos), "missing one of practice/targeted-practice tabs"
    assert practice_pos < targeted_pos, (
        "tab order changed — Targeted Practice must come after Practice"
    )
    # ---- the topbar, stripped and centred 2026-08-23 (Seth) -------------
    # The brand line, the signed-in email and every tab ⓘ are gone; the level
    # pill owns the far left, a cog owns the far right, and the tab strip is
    # centred BETWEEN them. The centring is the part that breaks silently:
    # `.tabs` was held against one edge with `margin-*: auto` through two
    # earlier rounds, and either of those rules coming back moves the strip
    # off centre without failing anything else here.
    layout_css = _read(os.path.join(HERE, "styles", "layout.css"))
    assert "--dd-topbar-h" in layout_css, (
        "styles/layout.css lost --dd-topbar-h. The bar's height is read by "
        "#page-practice and .nav-drawer-head; as a literal it has to be found "
        "and changed by hand in every one of them"
    )
    topbar_block = layout_css.split(".topbar {")[1].split("}")[0]
    assert "grid-template-columns: 1fr auto 1fr" in topbar_block, (
        "`.topbar` is not a 1fr/auto/1fr grid any more. Only two EQUAL side "
        "columns centre the strip on the viewport — flex `space-between` "
        "centres it on whatever happens to sit beside it"
    )
    tabs_block = layout_css.split("\n.tabs {")[1].split("}")[0]
    # A ban, not a positive check, and the comment in layout.css is worded to
    # say `margin-*: auto` rather than either literal so this cannot fail on
    # its own rationale (it did once, the other way round).
    for dead in ("margin-left: auto", "margin-right: auto"):
        assert dead not in tabs_block, (
            f"`.tabs` is holding itself against an edge again ({dead}) — that "
            f"un-centres the strip the grid just centred"
        )
    assert 'id="topbar-auth"' not in index_html, (
        "the signed-in email is back in the topbar. It belongs on the Account "
        "tab (#account-identity-email)"
    )
    assert 'class="logo"' not in index_html, (
        "`.logo` is back. It was the brand line, then an empty flex spacer "
        "that outlived it; in a three-column grid an extra child DISPLACES "
        "the centred tab strip into a side column"
    )
    assert 'id="topbar-cog"' in index_html and 'data-goto-tab="account"' in index_html, (
        "the topbar cog is gone or no longer routes to Account. It is the "
        "only control on the right edge and it needs no handler of its own — "
        "app.js wires every [data-goto-tab]"
    )
    level_pos = index_html.find('id="dd-level"')
    tabs_pos = index_html.find('<nav class="tabs">')
    cog_pos = index_html.find('id="topbar-cog"')
    assert -1 not in (level_pos, tabs_pos, cog_pos), "topbar lost the pill, the strip or the cog"
    assert level_pos < tabs_pos < cog_pos, (
        "topbar source order changed. Grid auto-placement fills the columns "
        "in DOM order, so pill → strip → cog IS the left/centre/right layout"
    )

    # ---- the question header ---------------------------------------------
    # The heading names the CONCEPT, and the two AUDIT controls live in the
    # notch's three-dot menu. They kept their ids so practice/ui.js and
    # practice/graph-jump.js still find them — which is exactly why a move
    # back into .question-number-row would go unnoticed by every other check.
    notch_menu_pos = index_html.find('id="practice-notch-menu"')
    assert notch_menu_pos != -1, "index.html missing the notch menu"
    for needle in ('id="question-id-chip"', 'id="practice-graph-jump"'):
        pos = index_html.find(needle)
        assert pos != -1, f"index.html missing {needle}"
        assert pos > notch_menu_pos, (
            f"{needle} is back above the question. Both audit controls belong "
            "in .practice-notch-menu — they exist so a problem can be quoted "
            "in a bug report, not so the learner reads them every question"
        )
    assert '<h2 class="question-number"' in index_html, (
        "the question heading is not an <h2> any more. It names the concept "
        "under test now, not 'Question 21' — a title, and marked up as one"
    )

    # The Statistics tab must not creep back in: its renderers, DOM module
    # and stylesheet were deleted, so a stray button would open a blank page.
    assert 'data-tab="statistics"' not in index_html, (
        'index.html has a data-tab="statistics" button again — the Statistics '
        "tab was removed 2026-07-31 and has no page to mount"
    )

    # The global Targeted Practice mode banner (#tp-banner) must live OUTSIDE
    # any <main> (it's a global indicator that persists across tab switches).
    # Cheap proxy: the banner element appears before the first real <main ...>
    # tag (skip HTML comments by matching `<main ` with trailing space).
    import re as _re
    banner_pos = index_html.find('id="tp-banner"')
    m = _re.search(r'<main\s', index_html)
    main_pos = m.start() if m else -1
    assert banner_pos != -1, "index.html missing #tp-banner global indicator"
    assert main_pos != -1 and banner_pos < main_pos, (
        "#tp-banner moved inside/after <main> — banner must stay above all pages"
    )

    # The banner's child elements + script/stylesheet links must stay in
    # index.html. Page-mount ids (#page-targeted-practice, #arena-unlock-page,
    # #arena-unlock-continue-btn) live in the -dom.js extraction modules —
    # those are checked above + in the per-folder watch.py scripts.
    for needle in (
        'id="tp-banner-meta"',
        'id="tp-banner-end"',
        'href="targeted-practice/targeted-practice.css',
        'src="targeted-practice/targeted-practice-dom.js',
        'src="targeted-practice/targeted-practice.js',
        'src="practice/arena-unlock-dom.js',
    ):
        assert needle in index_html, f"index.html missing required marker: {needle}"

    # Script load order — targeted-practice.js needs these to be already
    # evaluated. Most have const/let top-level bindings that ARE visible
    # cross-script but only after their <script> tag has executed.
    def _script_offset(needle):
        m = _re.search(rf'<script\s+src="{_re.escape(needle)}', index_html)
        return m.start() if m else -1

    tp_pos = _script_offset('targeted-practice/targeted-practice.js')
    assert tp_pos != -1, 'index.html missing <script src="targeted-practice/targeted-practice.js">'
    for dep in (
        'app.js',
        'arena/manifest.js',
        'arena/exercises.js',
        'stats/predicted-links.js',
        'stats/predicted-prereqs-temp.js',
        'practice/arena-unlock.js',
    ):
        dep_pos = _script_offset(dep)
        assert dep_pos != -1, f"index.html missing dep script: {dep}"
        assert dep_pos < tp_pos, (
            f"load-order broken: {dep} must come before targeted-practice.js "
            "(targeted-practice's catalog + ArenaUnlock.showFor handoff reads "
            "globals defined by these files)"
        )

    # Courses page contract: the tab renders the single ARENA course directly,
    # so only the detail-view shell that courses.js queries by id must remain
    # in index.html — there is no list view, no search input, and no results
    # container. courses.js and its fork gate must both load (script tags
    # present) so the tab is interactive, and courses.js must still embed the
    # ARENA detail content (chapter images + source links) the user expects.
    for marker in (
        'id="courses-detail-view"',
        'src="courses.js',
        'src="courses-fork-gate.js',
    ):
        assert marker in index_html, f"index.html missing {marker}"

    # The removed list view must not creep back in — these ids are what the
    # search/card UI hung off of.
    for gone in ('id="courses-search"', 'id="courses-results"', 'id="courses-list-view"'):
        assert gone not in index_html, (
            f"index.html still has {gone}: the Courses tab is ARENA-only and has no list view"
        )

    # courses.js resolves Colab hrefs through colabUpstreamHref(), which
    # stats/predicted-links.js defines, so that file must load first.
    courses_pos = _script_offset("courses.js")
    for dep in ("stats/predicted-links.js", "courses-fork-gate.js"):
        dep_pos = _script_offset(dep)
        assert dep_pos != -1, f"index.html missing dep script: {dep}"
        assert dep_pos < courses_pos, (
            f"load-order broken: {dep} must come before courses.js (courses.js "
            "resolves Colab hrefs via colabUpstreamHref and hands first clicks "
            "to window.CoursesForkGate)"
        )

    courses_js = _read(os.path.join(HERE, "courses.js"))
    for needle in (
        "ARENA_DETAIL",
        "learn.arena.education/static/images/arena-logo.png",
        "funda.png",
        "mechinterp.png",
        "/rl.png",
        "evals.jpeg",
        "science+of+misalignment.png",
        # Source links in the hero — the ARENA site and Callum's upstream repo.
        "https://www.arena.education/",
        "https://github.com/callummcdougall/ARENA_3.0",
        # Section rows link out to upstream Colab notebooks rather than the
        # local book mirror; the first click routes through the fork gate.
        "notebookPathForBookUrl",
        "colabUpstreamHref",
        "CoursesForkGate",
        "courses:github-owner-changed",
        # Chapter-sections modal: open/close logic, modal classnames, and
        # one representative section title per chapter so the modal data
        # cannot silently regress on any chapter.
        "openChapterModal",
        "closeChapterModal",
        "chapter-modal-backdrop",
        # Chapter 0 — Fundamentals (color #DC2626).
        "Prerequisites",
        "Ray Tracing",
        "VAEs & GANs",
        "#DC2626",
        # Chapter 1 — Transformer Interpretability (color #D97706).
        "Transformers from Scratch",
        "Intro to Mech Interp",
        "OthelloGPT",
        "Monthly Algorithmic Problems",
        "#D97706",
        # Chapter 2 — Reinforcement Learning (color #059669).
        "Intro to RL",
        "DQN & VPG",
        "RLHF",
        "#059669",
        # Chapter 3 — LLM Evaluations (color #2563EB).
        "Intro to Evals",
        "Dataset Generation",
        "LLM Agents",
        "#2563EB",
        # Chapter 4 — Alignment Science (color #4F46E5).
        "Emergent Misalignment",
        "Science of Misalignment",
        "Investigator Agents",
        "#4F46E5",
    ):
        assert needle in courses_js, f"courses.js missing required content: {needle}"

    prereqs = json.loads(_read(os.path.join(HERE, "arena_prereqs_structured.json")))

    # ID 27 (einsum bundle) must have a non-null canonical solution — was a known bug.
    id27 = next((q for q in prereqs if q.get("id") == 27), None)
    assert id27 and id27["exercise"].get("canonical_solution"), "id-27 canonical_solution must not be null"

    # Visual-output questions must have a canonical_solution to drive the preview.
    visual_missing = [
        q["id"] for q in prereqs
        if q["exercise"].get("supports_visual_output") and not q["exercise"].get("canonical_solution")
    ]
    assert not visual_missing, f"visual questions missing canonical_solution: {visual_missing}"

    # (runtime_unmet_dependencies check removed 2026-07-06 — the field was
    # dropped from the extract_arena_prereqs.py schema.)

    # Every function-implementation exercise must carry a canonical solution
    # (the solutions-notebook fallback in extract_arena_prereqs.py guarantees
    # this even for exercises with no trailing solution markdown).
    fn_missing = [
        q["id"] for q in prereqs
        if q["exercise"].get("task_type") == "function_implementation"
        and not q["exercise"].get("canonical_solution")
    ]
    assert not fn_missing, f"function questions missing canonical_solution: {fn_missing}"

    # export_questions_json.py must merge the same override layers as the
    # backend's _load_function_overrides(). If they ever drift, the validator
    # works against a different bank than the backend serves.
    exporter = _read(os.path.join(HERE, "pipeline", "export_questions_json.py"))
    for layer in (
        "function_mode_overrides.jsonl",
        "function_mode_overrides_round2.jsonl",
        "function_mode_overrides_round3.jsonl",
        "einops_prompt_rewrite_overrides.jsonl",
        "numpy_einsum_prompt_rewrite_overrides.jsonl",
    ):
        assert layer in exporter, (
            f"export_questions_json.py must merge {layer} (mirror of backend "
            f"_load_function_overrides override stack)"
        )


def check_infotips():
    """The ⓘ system: every anchor has copy, and every tab has a dot.

    Two lists have to stay in step — `data-dd-info="<key>"` in the markup
    and the keys in infotips-registry.js. Neither half fails loudly on its
    own: a key with no anchor is dead copy nobody sees, and an anchor with
    no key renders a dot that opens an empty panel. Both are silent, so
    they are asserted here instead.
    """
    import re as _re

    index_html = _read(os.path.join(HERE, "index.html"))
    registry = _read(os.path.join(HERE, "infotips-registry.js"))
    # Anchors also live in the two runtime DOM modules, which is the whole
    # reason infotips.js re-derives dots from a MutationObserver.
    anchor_sources = [
        index_html,
        _read(os.path.join(HERE, "targeted-practice", "targeted-practice-dom.js")),
        _read(os.path.join(HERE, "practice", "arena-unlock-dom.js")),
        # The stage ladder writes its own ⓘ per rung rather than letting the
        # scanner inject one: the rung names are drawn TWICE (a base layer and
        # an on-accent copy clipped to the fill), and a dot injected
        # asynchronously would land in one layer and not the other, so the two
        # would show different widths through the same clip.
        _read(os.path.join(HERE, "practice", "stage-ladder.js")),
    ]

    anchors = set()
    for src in anchor_sources:
        anchors.update(_re.findall(r'data-dd-info="([^"]+)"', src))
    # A key written through a template hole is not a key. The stage ladder
    # emits `data-dd-info="${esc(INFO_KEY[s.id])}"`, so the literal keys come
    # from that table instead — and they still have to be REAL keys, which is
    # the whole point of reading them here rather than skipping the file.
    anchors = {a for a in anchors if "${" not in a}
    ladder_js = _read(os.path.join(HERE, "practice", "stage-ladder.js"))
    info_key = _re.search(r"const INFO_KEY = \{(.*?)\};", ladder_js, _re.S)
    assert info_key, (
        "stage-ladder.js has no INFO_KEY table — the rung ⓘs are keyed "
        "somewhere this check cannot see"
    )
    rung_keys = set(_re.findall(r':\s*"([^"]+)"', info_key.group(1)))
    assert len(rung_keys) == 4, (
        f"INFO_KEY names {len(rung_keys)} rungs, expected 4 — a rung with no "
        f"ⓘ is a rung the learner cannot ask about"
    )
    anchors.update(rung_keys)
    # Registry keys are bare identifiers or quoted strings before a `: {`.
    keys = set(_re.findall(r'^\s*"?([A-Za-z][\w.-]*)"?:\s*\{', registry, _re.M))

    assert keys, "infotips-registry.js parsed to zero keys — did its shape change?"
    orphan_anchors = sorted(anchors - keys)
    assert not orphan_anchors, (
        f"data-dd-info anchors with no copy in infotips-registry.js: {orphan_anchors}"
    )
    orphan_keys = sorted(keys - anchors)
    assert not orphan_keys, (
        f"infotips-registry.js keys no element carries: {orphan_keys}"
    )

    # 🔴 INVERTED 2026-08-23. This used to require a dot beside every tab.
    # Seth: "there's information icons literally everywhere ... it's overkill".
    # All ten went, and the assertion is now that they stay gone — nothing else
    # here fails when one comes back, and two things quietly get worse: the
    # strip reads as ten labels each trailed by a stray "i", and `.tab`'s
    # `border-bottom` (the active underline) spans the label while the eye
    # reads label+dot as the tab, so the line looks offset to the left.
    assert "tab-info" not in index_html, (
        "a tab ⓘ is back in index.html. A tab's name is the description; the "
        "two tabs that need more than a name ARE pages of exactly that"
    )
    assert 'data-dd-info="tab.' not in index_html, (
        "a tab is carrying data-dd-info again — infotips.js would inject a "
        "dot for it even with no hand-written .tab-info in the markup"
    )
    for tag in _re.findall(r'<button[^>]*class="[^"]*\btab\b[^"]*"[^>]*>', index_html):
        assert "data-dd-info" not in tag, (
            f"a .tab carries data-dd-info; infotips.js forces a BUTTON anchor "
            f"to place=after, so this mints a sibling dot: {tag}"
        )

    # Load order: behaviour reads window.DD_INFOTIPS at IIFE-eval time.
    reg_pos = index_html.find('src="infotips-registry.js')
    beh_pos = index_html.find('src="infotips.js')
    assert reg_pos != -1, 'index.html missing <script src="infotips-registry.js">'
    assert beh_pos != -1, 'index.html missing <script src="infotips.js">'
    assert reg_pos < beh_pos, (
        "infotips-registry.js must load BEFORE infotips.js — the registry is "
        "read once, at eval time, and an empty one renders no dots at all"
    )
    assert 'href="styles/infotips.css' in index_html, (
        "index.html missing styles/infotips.css — dots render as bare text"
    )


# ── Nav drawer checks ─────────────────────────
# Below 900px the tab strip leaves the topbar and becomes a hamburger menu.
# The one rule that makes it safe is that the strip is MOVED, not copied:
# app.js captures `.tab`, `.auth-only` and `.guest-only` into static NodeLists
# at eval time, and a cloned strip is in none of them — its tabs would not
# switch pages, would never highlight, and would show Account and Split Tool
# to a signed-out visitor. None of that throws; it just quietly does the wrong
# thing, which is exactly what a watch check is for.
def check_nav_drawer():
    import re as _re

    nav_js = _read(os.path.join(HERE, "nav-drawer.js"))
    index_html = _read(os.path.join(HERE, "index.html"))

    stripped = _re.sub(r"/\*.*?\*/", "", nav_js, flags=_re.DOTALL)
    stripped = _re.sub(r"^\s*//.*$", "", stripped, flags=_re.MULTILINE)
    assert "cloneNode" not in stripped, (
        "nav-drawer.js clones the tab strip. It must MOVE the live <nav class="
        '"tabs"> (appendChild) — a copy is outside the NodeLists app.js captured '
        "at eval time, so its tabs neither switch pages nor respect auth visibility"
    )
    assert "appendChild" in stripped, (
        "nav-drawer.js no longer moves the tab strip into the drawer"
    )

    # The script has to run after app.js, which is what captures the tabs where
    # the markup put them. Moving a node keeps its listeners, so this ordering
    # is about the capture, not the move.
    app_pos = index_html.find('src="app.js')
    nav_pos = index_html.find('src="nav-drawer.js')
    assert nav_pos != -1, 'index.html missing <script src="nav-drawer.js">'
    assert app_pos != -1 and app_pos < nav_pos, (
        "nav-drawer.js must load AFTER app.js — app.js's tab NodeLists are "
        "captured at eval time and must see the strip in the topbar"
    )

    # One definition of "narrow". The breakpoint is duplicated by necessity —
    # CSS cannot move a node between parents, so the switch is a matchMedia in
    # JS while the practice split stacks from a media query — and drift between
    # the two is a real failure mode: a tab strip left in a topbar that has
    # already tightened for the drawer, or a hamburger that opens onto nothing.
    #
    # Read the ASSIGNMENT out of comment-stripped source, not the raw file. The
    # first version of this check searched `nav_js` for the literal string, and
    # nav-drawer.js explains its own breakpoint in a comment — so the assertion
    # was satisfied by the prose and would have kept passing after the query it
    # is guarding changed. A check that cannot fail is worse than no check.
    query = _re.search(
        r'NAV_DRAWER_QUERY\s*=\s*["\']\(max-width:\s*(\d+)px\)["\']', stripped
    )
    assert query, (
        "nav-drawer.js must define NAV_DRAWER_QUERY as a (max-width: <n>px) literal"
    )
    split_css = _read(os.path.join(HERE, "styles", "practice", "layout.css"))
    split_bp = _re.search(r"@media\s*\(max-width:\s*(\d+)px\)", split_css)
    assert split_bp, (
        "styles/practice/layout.css no longer has a max-width breakpoint to match"
    )
    assert query.group(1) == split_bp.group(1), (
        f"nav-drawer.js switches to the drawer at {query.group(1)}px but the "
        f"practice split stacks at {split_bp.group(1)}px — one definition of "
        f'"narrow", or the two layouts disagree about which one is on screen'
    )

    # The focus trap has to place EVERY Tab, not just the two edges of the ring.
    # The toggle is in the ring but sits outside the drawer and before it in the
    # DOM, so an edge-only trap let a forward Tab off the toggle fall through to
    # whatever the markup puts between them — for a signed-in visitor that is
    # `.topbar-auth`, behind the scrim. Reproduced live at 380px before the fix,
    # which is why this is pinned rather than left to review.
    assert "% ring.length" in stripped, (
        "nav-drawer.js's Tab handler no longer cycles the focus ring by index. "
        "An edge-only trap (`activeElement === edge`) leaks: the toggle is part "
        "of the ring but outside the drawer, so a forward Tab off it is handled "
        "by the browser and lands on the controls behind the scrim"
    )
    # The closed drawer must be unfocusable from CSS, not only from JS. The
    # script sets `.inert`, which does nothing before Safari 15.5 — and it still
    # carries a `MediaQueryList.addListener` fallback for Safari <14, so it
    # already assumes browsers where `inert` is a no-op. There, an off-canvas
    # panel is invisible to the eye and to nothing else: seven live tab stops.
    drawer_css = _read(os.path.join(HERE, "styles", "nav-drawer.css"))
    assert _re.search(r"visibility:\s*hidden", drawer_css), (
        "styles/nav-drawer.css no longer hides the closed drawer with "
        "`visibility`. `inert` alone is not enough — it is a no-op on the older "
        "Safari this component still writes fallbacks for, and the tabs stay in "
        "the tab order while the panel is off-canvas"
    )

    # Drawer mode is driven by a class the script adds, never by a media query
    # in this stylesheet — that is what keeps ONE definition of "narrow" (the
    # matchMedia above, checked against practice/layout.css). A `@media` block
    # appearing here would be a second breakpoint free to drift from it.
    assert "@media" not in _re.sub(r"/\*.*?\*/", "", drawer_css, flags=_re.DOTALL), (
        "styles/nav-drawer.css has grown a @media block. Every rule in it must "
        "stay scoped to `body.nav-drawer-mode`, the class nav-drawer.js adds — "
        "a breakpoint here is a second definition of narrow, and the width where "
        "it disagrees is a topbar tightened for a strip that is still in it"
    )

    tab_handler = stripped[stripped.find('event.key !== "Tab"'):]
    assert tab_handler, "nav-drawer.js no longer guards Tab at all"
    assert "toggle" in tab_handler.split("const ring")[1][:200], (
        "the focus ring must still start at the toggle — while the drawer is "
        "open the toggle is drawn as the × that closes it, and a close control "
        "you cannot Tab to is a trap rather than a cycle"
    )


# ── Solo-route checks ─────────────────────────
def check_solo_routes():
    index_html = _read(os.path.join(HERE, "index.html"))
    app_js = _read(os.path.join(HERE, "app.js"))
    solo_js = _read(os.path.join(HERE, "solo-route.js"))
    solo_css = _read(os.path.join(HERE, "styles", "solo-route.css"))
    vercel = json.loads(_read(os.path.join(HERE, "vercel.json")))

    # Every visible app tab gets a stable pathname spelling. Internal values
    # remain exact data-tab names so switchTab stays sole page owner.
    for tab in (
        "learn-about-app", "knowledge-graph", "split-tool",
        "account", "courses", "practice", "notebooks", "targeted-practice",
    ):
        assert f'data-tab="{tab}"' in index_html, f"missing tab {tab}"
        assert f'"{tab}"' in solo_js, f"solo-route.js missing route {tab}"

    for legacy in ("why-this-app", "how-to-use"):
        assert f'"{legacy}": "learn-about-app"' in solo_js, (
            f"/{legacy} was a linkable pathname before the 2026-08-23 merge and "
            "must still open the page those two tabs became"
        )

    assert 'classList.add("dd-solo")' in index_html, (
        "index.html must stamp solo mode before paint"
    )
    css_pos = index_html.find('href="styles/solo-route.css')
    responsive_pos = index_html.find('href="styles/responsive.css')
    assert css_pos > responsive_pos >= 0, (
        "solo-route.css must load after responsive.css so chrome stays hidden"
    )
    route_pos = index_html.find('src="solo-route.js')
    app_pos = index_html.find('src="app.js')
    assert 0 <= route_pos < app_pos, "solo-route.js must load before app.js"
    assert "DDSoloRoute?.read" in app_js and "DDSoloRoute?.apply" in app_js, (
        "app.js no longer boots + confirms pathname routes"
    )
    assert 'window.addEventListener("load", initConceptGraph' in app_js, (
        "direct Knowledge Graph boot must retry after deferred graph scripts load"
    )
    for selector in (".topbar", ".nav-drawer", ".guest-banner", ".tp-banner"):
        assert selector in solo_css, f"solo-route.css no longer hides {selector}"

    rewrites = vercel.get("rewrites") or []
    assert rewrites and rewrites[0].get("destination") == "/", (
        "deep-link rewrite must target /. cleanUrls redirects /index.html, "
        "which makes solo paths return Vercel NOT_FOUND"
    )
    assert rewrites[0].get("source") == "/((?!arena-book(?:/|$)).+)", (
        "deep-link rewrite must require a non-empty path and exclude arena-book. "
        "Matching / rewrites root to itself and makes the whole deployment 404"
    )



# ── Front door: the welcome fork + "Learn about the App" ──────────
def check_front_door():
    """The 2026-08-23 merge (Seth). Two tabs that both answered "what is this"
    became one, and the landing page became a two-arrow fork with nothing else
    on it. Every assertion here is a thing that fails SILENTLY — a page with no
    route in, a tab strip that comes back, a map that never draws — rather than
    raising anything at runtime."""
    index_html = _read(os.path.join(HERE, "index.html"))
    app_js = _read(os.path.join(HERE, "app.js"))
    learn_css = _read(os.path.join(HERE, "styles", "learn-about.css"))
    why_graph = _read(os.path.join(HERE, "concept-graph", "why-graph.js"))
    diagnostic = _read(os.path.join(HERE, "practice", "diagnostic-page.js"))

    # ONE tab, and the two it replaced are gone from the markup entirely.
    assert index_html.count('data-tab="learn-about-app"') == 1, (
        "there must be exactly one Learn about the App tab"
    )
    assert 'id="page-learn-about-app"' in index_html, "merged page missing"
    for dead in ('data-tab="why-this-app"', 'data-tab="how-to-use"',
                 'id="page-why-this-app"', 'id="page-how-to-use"'):
        assert dead not in index_html, f"{dead} came back; the merge is one page"

    # The disclosures. The lead paragraph stays OUTSIDE them on purpose: what
    # is unconditionally on screen is what the app is.
    assert index_html.count('class="lab-disclosure"') == 2, (
        "Learn about the App is two disclosures: the three markers, and How "
        "the app works"
    )
    hero = index_html.split('id="page-learn-about-app"')[1].split("<details")[0]
    assert "<h1>Why this app exists</h1>" in hero and 'class="hiw-lead"' in hero, (
        "the heading and the lead paragraph must sit ABOVE the first "
        "disclosure — everything else on the page is opt-in reading"
    )
    # Comment-stripped: this file's own comments narrate the merge and name
    # the old tab, and an assertion that a phrase is gone must not be fooled
    # by prose that is explaining why it is gone.
    markup = re.sub(r"<!--.*?-->", "", index_html, flags=re.S)
    assert "How the app works" in markup and "How to use it" not in markup, (
        'the second disclosure is titled "How the app works" (Seth), not '
        '"How to use it"'
    )
    # The map moved under "How the app works" and must have stayed there.
    how_block = index_html.split('id="lab-how"')[1].split("</details>")[0]
    assert 'id="wta-graph-cy"' in how_block, (
        "the concept map belongs inside the How-the-app-works disclosure"
    )
    assert 'container.closest("details")' in why_graph and '"toggle"' in why_graph, (
        "why-graph.js must draw on the <details> toggle as well as on the "
        "page's class: inside a closed disclosure offsetParent is null, so "
        "the page-class observer alone leaves the map on 'Loading the map...'"
    )

    # The fork. Two arms, both [data-goto-tab], and NOT a tab.
    assert 'id="page-welcome"' in index_html, "the welcome fork is missing"
    fork = index_html.split('id="page-welcome"')[1].split("</main>")[0]
    assert fork.count("data-goto-tab") == 2, (
        "the fork is exactly two choices and nothing else (Seth)"
    )
    assert 'data-goto-tab="learn-about-app"' in fork and 'data-goto-tab="diagnostic"' in fork, (
        "left arm reads about the app, right arm starts the placement test"
    )
    assert "optional" in fork, (
        "the reading path must say out loud that it is optional, or a fork "
        "reads as a prerequisite"
    )
    assert 'data-tab="welcome"' not in markup, (
        "#page-welcome is a fork, not a tab"
    )
    assert '"welcome")' in app_js and 'dd-welcome' in app_js, (
        "app.js must land a first-time visitor on the fork and stamp "
        "body.dd-welcome so the guest banner comes off that one screen"
    )
    assert "body.dd-welcome .guest-banner" in learn_css, (
        "the guest banner lives outside every .page, so only a body-class "
        "rule can take it off the fork"
    )

    # The strip. Basic mode has none; advanced mode is the whole way back.
    for selector in ("body.dd-basic-mode .tabs",
                     "body.dd-basic-mode .nav-drawer .tabs",
                     "body.dd-basic-mode .nav-toggle"):
        assert selector in learn_css, (
            f"{selector} missing: basic mode must have no tab strip, in the "
            "topbar OR parked in the drawer, and no hamburger to open an "
            "empty drawer with"
        )
    css_pos = index_html.find('href="styles/learn-about.css')
    drawer_pos = index_html.find('href="styles/nav-drawer.css')
    assert css_pos > drawer_pos >= 0, (
        "learn-about.css must load AFTER nav-drawer.css — its rule for the "
        "strip parked in the drawer ties on specificity with nav-drawer.css's "
        "own, and source order is the only thing that settles it"
    )
    assert 'class="dd-basic-nav"' in index_html and ".dd-basic-nav" in learn_css, (
        "the Account page needs the basic-mode escape row: with no strip, the "
        "cog is the only way off Practice and this row is the only way back"
    )
    assert 'data-goto-tab="practice"' in index_html.split('class="dd-basic-nav"')[1][:600], (
        "the escape row must lead back to Practice"
    )

    # 🔴 A NAME THAT MATCHES NO PAGE BLANKS THE APP. switchTab hides every
    # `.page` whose id is not `page-<name>`, so an unknown name leaves a topbar
    # over nothing, silently. The rename is the case we know about — a stale
    # `dd_recovered_tab` written by guest-session.js before a reload that
    # crosses a deploy — but the guard has to be general, because the next
    # rename will not come with a note.
    assert "renamedTabs" in app_js and '"why-this-app": "learn-about-app"' in app_js, (
        "switchTab must map the two retired tab names onto the page they "
        "merged into: a URL alias in solo-route.js cannot reach a name that "
        "arrives from sessionStorage"
    )
    assert "if (!document.getElementById(`page-${tabName}`))" in app_js, (
        "switchTab must fall back when the requested page does not exist — "
        "without it an unknown tab name hides every page and shows nothing"
    )

    # Placement hands off to Practice.
    assert 'switchTab("practice")' in diagnostic and "justFinished" in diagnostic, (
        "a finished placement must hand the learner to Practice — in basic "
        "mode there is no strip, so nothing else can"
    )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants, check_infotips,
              check_nav_drawer, check_solo_routes, check_front_door]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
