"""watch.py — health checks for Local_Deployed_Shared

Auto-generated by Modulario. Fill in the stub functions below with real
checks for this folder. Remove the marker comment on line 1 when done.
Runs via `mod watch` — exit 0 = PASS, exit non-zero = FAIL.
"""
import sys
import os
import json

HERE = os.path.dirname(os.path.abspath(__file__))

REQUIRED_FILES = [
    "questions.json",
    "questions_structured.json",
    "arena_prereqs_structured.json",
    "delta_numbers.npy",
    "numbers_stacked.png",
    "practice.js",
    "practice_engine.py",
    # practice.css was split into styles/practice/*.css (2026-07-12)
    "styles/practice/layout.css",
    "styles/practice/timer.css",
    "styles/practice/question.css",
    "styles/practice/feedback.css",
    "styles/practice/result.css",
    "styles/practice/misc.css",
    "index.html",
    "app.js",
    "courses.js",
]
REQUIRED_DIRS = [
    "practice",
    "arena",
    "content/ARENA_3.0-main",
    "content/ARENA_4.0-main",
    "chatgpt",
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


# ── Import checks ──────────────────────────────
# Folder is mixed Python/JS/data; verify the structural pieces are present and
# the JSON data files parse cleanly. No Python module import is meaningful here
# because most siblings pull heavy deps (numpy, requests, etc.) at import time.
def check_imports():
    missing = [f for f in REQUIRED_FILES if not os.path.isfile(os.path.join(HERE, f))]
    assert not missing, f"missing required files: {missing}"
    missing_dirs = [d for d in REQUIRED_DIRS if not os.path.isdir(os.path.join(HERE, d))]
    assert not missing_dirs, f"missing required subdirs: {missing_dirs}"

    for fname in ("questions.json", "questions_structured.json", "arena_prereqs_structured.json"):
        try:
            json.loads(_read(os.path.join(HERE, fname)))
        except json.JSONDecodeError as e:
            raise AssertionError(f"{fname} is not valid JSON: {e}")


# ── Public API checks ─────────────────────────
# The frontend depends on a few static asset paths and on the prereq question
# schema. Verify the question records expose the fields the practice runtime
# reads (starter_code, canonical_solution where expected, runtime contract).
def check_public_api():
    prereqs = json.loads(_read(os.path.join(HERE, "arena_prereqs_structured.json")))
    assert isinstance(prereqs, list) and prereqs, "arena_prereqs_structured.json must be a non-empty list"

    # Current extract_arena_prereqs.py schema — runtime_dependencies was
    # dropped from the generator (stale invariant removed 2026-07-06).
    required_keys = {"starter_code", "expected_artifact_type", "supports_visual_output", "task_type", "canonical_solution"}
    for q in prereqs:
        ex = q.get("exercise") or {}
        missing = required_keys - ex.keys()
        assert not missing, f"question id={q.get('id')} missing exercise keys: {missing}"


# ── Invariant checks ──────────────────────────
# Structural rules that must remain true for this folder.
def check_invariants():
    # The PNG fallback and source array must remain at canonical served paths.
    for asset in ("delta_numbers.npy", "numbers_stacked.png"):
        path = os.path.join(HERE, asset)
        assert os.path.getsize(path) > 0, f"{asset} is empty"

    # Each declared tab in index.html must have a matching <main id="page-${name}">,
    # and every auth-gated tab must be listed in app.js authRequiredTabs. Drift here
    # silently breaks navigation (clicking the tab hides every page).
    index_html = _read(os.path.join(HERE, "index.html"))
    app_js = _read(os.path.join(HERE, "app.js"))
    # learn / arena / course / papers tabs were removed from the SPA before
    # this session; keep this list aligned with the actual tab buttons in
    # index.html (and authRequiredTabs in app.js).
    expected_tabs = ("split-tool", "account", "courses", "practice", "targeted-practice", "statistics")
    # page-targeted-practice and page-statistics live in -dom.js modules
    # (extracted from index.html to keep it under the per-file LOC ceiling);
    # check those source files for the mount instead of index.html.
    runtime_mounts = {
        "targeted-practice": os.path.join(HERE, "targeted-practice", "targeted-practice-dom.js"),
        "statistics": os.path.join(HERE, "stats", "stats-dom.js"),
    }
    for tab in expected_tabs:
        assert f'data-tab="{tab}"' in index_html, f'index.html missing tab button data-tab="{tab}"'
        mount_src = runtime_mounts.get(tab, index_html)
        if isinstance(mount_src, str) and mount_src != index_html:
            mount_src = _read(mount_src)
        assert f'id="page-{tab}"' in mount_src, (
            f'<main id="page-{tab}"> missing — checked '
            f'{"runtime DOM module" if tab in runtime_mounts else "index.html"}'
        )
        assert f'"{tab}"' in app_js, f'app.js authRequiredTabs missing "{tab}"'

    # The Targeted Practice tab must sit between Practice and Statistics in
    # the nav. Order matters because the keyboard tab-cycle and the user's
    # mental model both follow left-to-right ordering.
    practice_pos = index_html.find('data-tab="practice"')
    targeted_pos = index_html.find('data-tab="targeted-practice"')
    stats_pos = index_html.find('data-tab="statistics"')
    assert -1 not in (practice_pos, targeted_pos, stats_pos), "missing one of practice/targeted-practice/statistics tabs"
    assert practice_pos < targeted_pos < stats_pos, (
        "tab order changed — Targeted Practice must sit between Practice and Statistics"
    )

    # The global Targeted Practice mode banner (#tp-banner) must live OUTSIDE
    # any <main> (it's a global indicator that persists across tab switches).
    # Cheap proxy: the banner element appears before the first real <main ...>
    # tag (skip HTML comments by matching `<main ` with trailing space).
    import re as _re
    banner_pos = index_html.find('id="tp-banner"')
    m = _re.search(r'<main\s', index_html)
    main_pos = m.start() if m else -1
    assert banner_pos != -1, "index.html missing #tp-banner global indicator"
    assert main_pos != -1 and banner_pos < main_pos, (
        "#tp-banner moved inside/after <main> — banner must stay above all pages"
    )

    # The banner's child elements + script/stylesheet links must stay in
    # index.html. Page-mount ids (#page-targeted-practice, #page-statistics,
    # #arena-unlock-page, #arena-unlock-continue-btn) live in the -dom.js
    # extraction modules — those are checked above + in the per-folder
    # watch.py scripts.
    for needle in (
        'id="tp-banner-meta"',
        'id="tp-banner-end"',
        'href="targeted-practice/targeted-practice.css',
        'src="targeted-practice/targeted-practice-dom.js',
        'src="targeted-practice/targeted-practice.js',
        'src="stats/stats-dom.js',
        'src="practice/arena-unlock-dom.js',
    ):
        assert needle in index_html, f"index.html missing required marker: {needle}"

    # Script load order — targeted-practice.js needs these to be already
    # evaluated. Most have const/let top-level bindings that ARE visible
    # cross-script but only after their <script> tag has executed.
    def _script_offset(needle):
        m = _re.search(rf'<script\s+src="{_re.escape(needle)}', index_html)
        return m.start() if m else -1

    tp_pos = _script_offset('targeted-practice/targeted-practice.js')
    assert tp_pos != -1, 'index.html missing <script src="targeted-practice/targeted-practice.js">'
    for dep in (
        'app.js',
        'arena/manifest.js',
        'arena/exercises.js',
        'stats/predicted-links.js',
        'stats/predicted-prereqs-temp.js',
        'practice/arena-unlock.js',
    ):
        dep_pos = _script_offset(dep)
        assert dep_pos != -1, f"index.html missing dep script: {dep}"
        assert dep_pos < tp_pos, (
            f"load-order broken: {dep} must come before targeted-practice.js "
            "(targeted-practice's catalog + ArenaUnlock.showFor handoff reads "
            "globals defined by these files)"
        )

    # Courses page contract: the tab renders the single ARENA course directly,
    # so only the detail-view shell that courses.js queries by id must remain
    # in index.html — there is no list view, no search input, and no results
    # container. courses.js and its fork gate must both load (script tags
    # present) so the tab is interactive, and courses.js must still embed the
    # ARENA detail content (chapter images + source links) the user expects.
    for marker in (
        'id="courses-detail-view"',
        'src="courses.js',
        'src="courses-fork-gate.js',
    ):
        assert marker in index_html, f"index.html missing {marker}"

    # The removed list view must not creep back in — these ids are what the
    # search/card UI hung off of.
    for gone in ('id="courses-search"', 'id="courses-results"', 'id="courses-list-view"'):
        assert gone not in index_html, (
            f"index.html still has {gone}: the Courses tab is ARENA-only and has no list view"
        )

    # courses.js resolves Colab hrefs through colabUpstreamHref(), which
    # stats/predicted-links.js defines, so that file must load first.
    courses_pos = _script_offset("courses.js")
    for dep in ("stats/predicted-links.js", "courses-fork-gate.js"):
        dep_pos = _script_offset(dep)
        assert dep_pos != -1, f"index.html missing dep script: {dep}"
        assert dep_pos < courses_pos, (
            f"load-order broken: {dep} must come before courses.js (courses.js "
            "resolves Colab hrefs via colabUpstreamHref and hands first clicks "
            "to window.CoursesForkGate)"
        )

    courses_js = _read(os.path.join(HERE, "courses.js"))
    for needle in (
        "ARENA_DETAIL",
        "learn.arena.education/static/images/arena-logo.png",
        "funda.png",
        "mechinterp.png",
        "/rl.png",
        "evals.jpeg",
        "science+of+misalignment.png",
        # Source links in the hero — the ARENA site and Callum's upstream repo.
        "https://www.arena.education/",
        "https://github.com/callummcdougall/ARENA_3.0",
        # Section rows link out to upstream Colab notebooks rather than the
        # local book mirror; the first click routes through the fork gate.
        "notebookPathForBookUrl",
        "colabUpstreamHref",
        "CoursesForkGate",
        "courses:github-owner-changed",
        # Chapter-sections modal: open/close logic, modal classnames, and
        # one representative section title per chapter so the modal data
        # cannot silently regress on any chapter.
        "openChapterModal",
        "closeChapterModal",
        "chapter-modal-backdrop",
        # Chapter 0 — Fundamentals (color #DC2626).
        "Prerequisites",
        "Ray Tracing",
        "VAEs & GANs",
        "#DC2626",
        # Chapter 1 — Transformer Interpretability (color #D97706).
        "Transformers from Scratch",
        "Intro to Mech Interp",
        "OthelloGPT",
        "Monthly Algorithmic Problems",
        "#D97706",
        # Chapter 2 — Reinforcement Learning (color #059669).
        "Intro to RL",
        "DQN & VPG",
        "RLHF",
        "#059669",
        # Chapter 3 — LLM Evaluations (color #2563EB).
        "Intro to Evals",
        "Dataset Generation",
        "LLM Agents",
        "#2563EB",
        # Chapter 4 — Alignment Science (color #4F46E5).
        "Emergent Misalignment",
        "Science of Misalignment",
        "Investigator Agents",
        "#4F46E5",
    ):
        assert needle in courses_js, f"courses.js missing required content: {needle}"

    prereqs = json.loads(_read(os.path.join(HERE, "arena_prereqs_structured.json")))

    # ID 27 (einsum bundle) must have a non-null canonical solution — was a known bug.
    id27 = next((q for q in prereqs if q.get("id") == 27), None)
    assert id27 and id27["exercise"].get("canonical_solution"), "id-27 canonical_solution must not be null"

    # Visual-output questions must have a canonical_solution to drive the preview.
    visual_missing = [
        q["id"] for q in prereqs
        if q["exercise"].get("supports_visual_output") and not q["exercise"].get("canonical_solution")
    ]
    assert not visual_missing, f"visual questions missing canonical_solution: {visual_missing}"

    # (runtime_unmet_dependencies check removed 2026-07-06 — the field was
    # dropped from the extract_arena_prereqs.py schema.)

    # Every function-implementation exercise must carry a canonical solution
    # (the solutions-notebook fallback in extract_arena_prereqs.py guarantees
    # this even for exercises with no trailing solution markdown).
    fn_missing = [
        q["id"] for q in prereqs
        if q["exercise"].get("task_type") == "function_implementation"
        and not q["exercise"].get("canonical_solution")
    ]
    assert not fn_missing, f"function questions missing canonical_solution: {fn_missing}"

    # export_questions_json.py must merge the same override layers as the
    # backend's _load_function_overrides(). If they ever drift, the validator
    # works against a different bank than the backend serves.
    exporter = _read(os.path.join(HERE, "pipeline", "export_questions_json.py"))
    for layer in (
        "function_mode_overrides.jsonl",
        "function_mode_overrides_round2.jsonl",
        "function_mode_overrides_round3.jsonl",
        "einops_prompt_rewrite_overrides.jsonl",
        "numpy_einsum_prompt_rewrite_overrides.jsonl",
    ):
        assert layer in exporter, (
            f"export_questions_json.py must merge {layer} (mirror of backend "
            f"_load_function_overrides override stack)"
        )


# ── Run all checks ────────────────────────────
if __name__ == '__main__':
    checks = [check_imports, check_public_api, check_invariants]
    for fn in checks:
        try:
            fn()
        except Exception as e:
            print(f"FAIL {fn.__name__}: {e}", file=sys.stderr)
            sys.exit(1)
